### ISSUE TITLE
Private beta

### ISSUE THREAD

**Issue by huyphams** [TablePlus/TablePlus-Windows#1]
The private beta TablePlus on Windows is here

![welcome](https://user-images.githubusercontent.com/3654622/41449694-d386f492-708c-11e8-8272-99d8134609c0.PNG)

TL;DR
```
1. Requirement: Windows 10 64 bit (we will support more platforms in public beta).
2. This is alpha version (private beta), it's INCOMPLETED (so please don't expect so much on it).
3. Do not use this version for PRODUCTION.
4. List of core feature so far:
- Native build.
- Native SSH support.
- Async queries.
- Compatible with OSX build.
6. We release an update EVERY WEEK and it maybe not compatible with the previous build.
7. We are not receiving bug report as well as the feature request until public beta.
8. Do not comment on this issue, please email me at huy@tableplusapp.com
```

The first experience on Windows

By popular demand, we are working on a Windows version for TablePlus and we want to bring the best experiences from its OSX version.

While building TablePlus Windows, we use the same approach, the same philosophy as in how we built TablePlus Mac. We don't want to build an app that does many things but masters none. We focus only on the most important features that the majority of our users need and use the most, such as SQL Editor, Data Table Editor, or Database Structure Editor… We put those core features in the front so that our users can access them as fast as possible, and we hide most of the trivial functionalities. So it still looks clean and simple.

In order to bring the best experiences to the app, we build it natively. Native SSH, native drivers support. It's the same with TablePlus OSX, but the overall experience on TablePlus Windows will be somewhat different from TablePlus Mac. The way it looks and feels, from the menu, tab, to its icon set or the transition, have to follow the Windows experience, even though it works the same way.

What's in this release?

This release allows you to perform some core functions of TablePlus:
- Create a connection to the database
- Browse and edit data inline

What do I need to do?

Since it's only a private beta, we are not receiving bug report as well as the feature request. You just need to download the app, try it out and get an overview of it. We will continue sending out the next updates and will probably start asking for your feedback from the public beta.

TablePlus Team.
Huy.

**Comment by huyphams** [comment]
[Download](https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0)
- Native build.
- Native SSH support.
- Async queries.

**Comment by huyphams** [comment]
#### Next update at 22-Jun-2018.

**Comment by huyphams** [comment]
Next update at 22-Jun-2018.
Feature added:
- Edit inline + commit change to the server.

**Comment by mrpauljbailey** [comment]
Looks like Dropbox is having some security issues around their certificate.  Can you provide an alternative download  option please.

![image](https://user-images.githubusercontent.com/10880716/41525493-1c9c25a0-72d9-11e8-9cff-b1f45485a4b2.png)

**Comment by eberkund** [comment]
Does the beta only work with PostreSQL?

**Comment by mrpauljbailey** [comment]
It appears so.

⁣Sent from BlueMail ​

**Comment by eberkund** [comment]
Okay, that's fine. I just wanted to make sure I wasn't missing an option somewhere to change it.

**Comment by moggybaer** [comment]
Is there any release plan?  I'm interested to test other DB's like MSSQLm MySQL and Oracle.
Do you work in Sprint Iterations?

**Comment by huyphams** [comment]
Hi Guys,
Please don't comment on this issue, if you have any question, feel free to email me at huy@tableplusapp.com.
All the drivers and more platform will be supported in the `Public Beta`.
I'm going to clean up comments on this topic.
Thanks.

**Comment by huyphams** [comment]
Update at 15-Jul-2018.

- Add driver MySQL.

Download: [Dropbox](https://www.dropbox.com/s/b629c3l72ryz5g0/TablePlusWin.zip?dl=0), [Google Drive](https://drive.google.com/open?id=1ULG0keRK5oAjpDz2sveIEtICmYEsW0Zq)

Next update: 30-Jul-2018.

**Comment by huyphams** [comment]
You guys can also follow the up-coming feature (the change logs) in this project: https://github.com/TablePlus/TablePlus-Windows/projects/1

**Comment by huyphams** [comment]
Update: 4-Aug-2018.

- Support edit/create group.
- Show connection error while testing/connecting.
- The Connect button in form is working now.
-  The Test button in form is working now.
- Truncate tail text in the data cell.
- Inline edit: Preview And Commit the changes.

Download: [Dropbox](https://www.dropbox.com/s/b629c3l72ryz5g0/TablePlusWin.zip?dl=0), [Google Drive](https://drive.google.com/open?id=1ULG0keRK5oAjpDz2sveIEtICmYEsW0Zq)

**Comment by huyphams** [comment]
Update 7-Aug-2018.

- Supported highlight syntax.
- Improved Preview SQL.
- Show column type in detail pane.
- Allow to set connection tag.
- General UI improvements.

Download: [Dropbox](https://www.dropbox.com/s/b629c3l72ryz5g0/TablePlusWin.zip?dl=0), [Google Drive](https://drive.google.com/open?id=1ULG0keRK5oAjpDz2sveIEtICmYEsW0Zq)

**Comment by huyphams** [comment]
Update 10-Aug-2018.

- Supported detect and run the statement under the cursor.
- Improve inline editing.
- Remember last SQL Query.
- Show query error message.

Download: [Dropbox](https://www.dropbox.com/s/b629c3l72ryz5g0/TablePlusWin.zip?dl=0), [Google Drive](https://drive.google.com/open?id=1ULG0keRK5oAjpDz2sveIEtICmYEsW0Zq)

**Comment by huyphams** [comment]
Update 19-Aug-2018.
 - Changed cell color when updated cell.
 - Supported delete rows.
 - A lot of small improvements.
Download: [Dropbox](https://www.dropbox.com/s/b629c3l72ryz5g0/TablePlusWin.zip?dl=0), [Google Drive](https://drive.google.com/open?id=1ULG0keRK5oAjpDz2sveIEtICmYEsW0Zq)

**Comment by huyphams** [comment]
Hi guys, this build is the latest build or Private Beta. We will have public beta next month. The public beta is stable enough for Production.
We're starting to receive bugs and features suggestion from the public beta.
Thanks,
Huy.


Download: [Dropbox](https://www.dropbox.com/s/b629c3l72ryz5g0/TablePlusWin.zip?dl=0), [Google Drive](https://drive.google.com/open?id=1ULG0keRK5oAjpDz2sveIEtICmYEsW0Zq)

Changelogs:
- Added Support Windows 32 bit system.
- Added SQL Server driver.
- Added row counter.
- Execute statement: Ctrl+ E.
- Reload workspace: Ctrl+ R.
- Commit the changes: Ctrl+ S.
- Preview the changes: Ctrl + P.
- Open new Workspace: Ctrl + N.
- Toggle detail pane: Ctrl + Space.

You need to install  DOT NET 4.7.2 in order to run TablePlus.
https://support.microsoft.com/en-us/help/4054530/microsoft-net-framework-4-7-2-offline-installer-for-windows

**Comment by bladefist** [comment]
@huyphams the latest build links are dead.  The Windows build on the official website is on build 15 still, while your changelog is much further ahead.  Also, barely anything works.  Is windows version dead?

**Comment by huyphams** [comment]
We released the windows a few days ago, here is the change logs of the Windows version:
https://tableplus.io/win/changelog
The build 15 was released 3 days ago.

Probably you're looking at the Mac changelog. It takes some time to catch up the Mac version.

**Comment by huyphams** [comment]
Sure, this one is easy, I can fix it. We're going to release a new version on Monday (and new Mac version too).
I can confirm that those two issues were included in that release.

**Comment by huyphams** [comment]
https://github.com/TablePlus/TablePlus-Windows/issues/12
