### ISSUE TITLE
csv with header export

### ISSUE THREAD

**Issue by Noetika** [TablePlus/TablePlus-Windows#10]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

run a basic query - perhaps 2 fields
try to export as csv with headers
if you use upper case instead of lower case on field names the export creates an empty file
should it be case sensitive?

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @Noetika the build which released tomorrow will fix this issue.

**Comment by huyphams** [comment]
Fixed on build 11.
