### ISSUE TITLE
Autocomplete of SQL commands and keywords should be UPPER CASE

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#100]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Any

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
88

3. The steps to reproduce this issue:
Autocomplete of any SQL command or keyword outputs the name in lower case like a field name, while the "SQL" popup screen from a table puts all those names in upper case, which for readability they really should be.

**Comment by jim256** [comment]
Couldn't agree more! Was just about to open an issue saying the same thing.

**Comment by huyphams** [comment]
We will release a new update next week, It will support this feature. Thank you.

**Comment by huyphams** [comment]
it's released in build 90.
