### ISSUE TITLE
Focus is changing to a different field while searching tables

### ISSUE THREAD

**Issue by bwat47** [TablePlus/TablePlus-Windows#101]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Microsoft SQL Server 2014

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.9.3 (89)

3. The steps to reproduce this issue:

- Connect to a database

- Select a table on the left sidebar

- Highlight any row within that table, and left click inside any field (so that your cursor is active inside a specific field)

- Now put your cursor in the table name search field on the top left and start typing.

You'll see that the 1st character you type correctly goes into the table search field, but then the focus automatically switches back to the table field where your cursor was previously active and subsequent characters go into that field

**Comment by huyphams** [comment]
I've fixed it, please download this hot patch: https://www.dropbox.com/s/9buss6n45wdf3o3/TablePlusSetup.exe?dl=0
Please let me know if you're still seeing it.

**Comment by bwat47** [comment]
Thanks, this does fix the issue for me!
