### ISSUE TITLE
duplicate display after insert error

### ISSUE THREAD

**Issue by jagDanJu** [TablePlus/TablePlus-Windows#103]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0.17

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
89

3. The steps to reproduce this issue:

- execute a statement without results:

![image](https://user-images.githubusercontent.com/3613218/65818553-d7d72280-e212-11e9-8529-5a03d710e9eb.png)

- Open the context menu
- click on "Add Row"
- try to insert some invalid data

![image](https://user-images.githubusercontent.com/3613218/65818497-2cc66900-e212-11e9-8c00-063c4ffad81c.png)

- try to insert some valid data

![image](https://user-images.githubusercontent.com/3613218/65818511-449ded00-e212-11e9-8423-efcf54d11e89.png)

- press Ctrl + S
- then 2 identical rows appear (BUG!)

![image](https://user-images.githubusercontent.com/3613218/65818583-12d95600-e213-11e9-8bd6-7a1fbed5e1a7.png)

- if you now click twice in the result lines, then the program hangs up and after some seconds it is closing

![image](https://user-images.githubusercontent.com/3613218/65818595-2be20700-e213-11e9-8dfc-65b43599c42b.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thank you @jagDanJu I've fixed it 👍

**Comment by huyphams** [comment]
Or you can download the hot patch here: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by jagDanJu** [comment]
@huyphams it works! Thank You.
