### ISSUE TITLE
Renaming table does not rename tab

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#104]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
89

3. The steps to reproduce this issue:
Open table
click on "Structure"
enter new name in "Name" field
Save
table renames in tables pane 
tab name stays with old name until you close it and reopen

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thank you, I've fixed it, you can download the hot patch here: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
