### ISSUE TITLE
Random tab switching on reloading connection

### ISSUE THREAD

**Issue by lszymkowiak** [TablePlus/TablePlus-Windows#105]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.4.7, 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
89

3. The steps to reproduce this issue:
Reloading connection (Ctrl+R) randomly switches to different opened tab or opens already closed tab. Restarting application helps, but after awhile it starts to do this again.

**Comment by huyphams** [comment]
Hi @lszymkowiak please download this hot patch, it should fix the issue, thank you
https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
