### ISSUE TITLE
Copy definition statement - outdated alert

### ISSUE THREAD

**Issue by israelidanny** [TablePlus/TablePlus-Windows#106]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6.14
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 2.9.3 (89) x64
3. The steps to reproduce this issue:
Right click on materialized view and click on 'Copy definition statement'

What appears is an alert stating:
```
Coming on Feb-2019
```

**Comment by huyphams** [comment]
Thank you @israelidanny it was supported in some drivers, I will add this function for PostgreSQL in the next release.

**Comment by jagDanJu** [comment]
Hey @huyphams,
are there any news here?

Kind Regards
