### ISSUE TITLE
possibility to limit select statement

### ISSUE THREAD

**Issue by jagDanJu** [TablePlus/TablePlus-Windows#108]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
any

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 90

3. The steps to reproduce this issue:
It would be good to have a way to limit the number of "select" results rows 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by rwhirn** [comment]
Isn't this the '*" button at the bottom of the rows pane?

**Comment by huyphams** [comment]
I think @jagDanJu mentioned this feature @rwhirn 
<img width="1320" alt="limit" src="https://user-images.githubusercontent.com/3654622/66258881-b630ea80-e780-11e9-8019-f558f9d2fb3f.png">

**Comment by rwhirn** [comment]
How is it different than this?

![image](https://user-images.githubusercontent.com/25158630/66259020-f3da4700-e771-11e9-9bc4-78171cc5c120.png)

**Comment by huyphams** [comment]
The problem is the paging limit is only for a certain table. But the limit query edit can be applied for `any custom queries`.
For example:

```
SELECT id FROM A JOIN B WHERE A.id = B.id
```

**Comment by rwhirn** [comment]
ahh, yes you have to manually type it or copy over from your initial SQL filter command popup.

**Comment by talalong** [comment]
Hi! just want to let you know that I am still waiting for this feature.

**Comment by rwhirn** [comment]
@talalong If you didn't know already its been done.
