### ISSUE TITLE
Filter loses "<" condition when adding another filter

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#109]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.17

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
89

3. The steps to reproduce this issue:
Open table with an id field
![image](https://user-images.githubusercontent.com/25158630/66149482-d756d700-e5d8-11e9-96ae-145c83e54562.png)

filter by id field using "<"
![image](https://user-images.githubusercontent.com/25158630/66149735-577d3c80-e5d9-11e9-8a26-25fba6758357.png)

click that filter's "+" button to add another filter and the "<" disappears for both the previous filter and the new filter
![image](https://user-images.githubusercontent.com/25158630/66149869-9b704180-e5d9-11e9-8487-38ecf8eb0363.png)

**Comment by huyphams** [comment]
This is one of the known issues, and it seems like it was a .Net bug, I'm still finding a way to workaround.

**Comment by huyphams** [comment]
Please try this hot patch, I've added a workaround for this issue:
https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
Thank you, please let me know if you're still seeing it.
