### ISSUE TITLE
Missing keyboard shortcuts

### ISSUE THREAD

**Issue by eberkund** [TablePlus/TablePlus-Windows#11]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
All

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 12

3. The steps to reproduce this issue:
Press ctrl+P and expect to see the "open anything palette".

**Comment by huyphams** [comment]
The open anything was not added to TablePlus Windows, we will add it soon, in this month. 
FYI: The next update will be released tomorrow with Fuzzy search and a lot of improvements.

**Comment by huyphams** [comment]
It's supported on the build 60! Thanks!
