### ISSUE TITLE
ESCape key does not "escape" field change

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#111]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
any

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
90

3. The steps to reproduce this issue:
ESCape key generally discards whatever you were doing.
E.g., if I edit a field, type over the date in the field, then realize I am in the wrong spot before clicking or tabbing out of the field, I should be able to hit ESCape and have my changes ignored and the previous value remain in the field.

Also, if I hit ctrl-s and the Alert popup to confirm comes up, when I hit the ESCape key it rightly performs the same function as hitting "Cancel" but if I click the SQL button to popup the SQL command for this set of filters the ESCape key has no effect on this popup. (I assume because there is no "Cancel" button).

**Comment by huyphams** [comment]
The escape should only escape the editor. We're working on Undo/Redo feature, which could help if you accidentally enter a wrong value.

**Comment by rwhirn** [comment]
I would disagree. If you are in Excel (also a grid) and you type an entry into a cell and hit ESCape the value remains unchanged and the cell restores to previous value. If you type into a TablePlus cell and hit ESCape it acts like a confirm and enters the incorrect value. 

Its not a deal-breaker, but I think it should act the same as Excel and at the very least, it should not act like you hit ENTER.

**Comment by huyphams** [comment]
The excel is on an other hand, it mostly handles number but TablePlus is a database tool, it has a wide range data types. Some users edit a huge text field and it can lead to data lost if they accidentally press ESC. Meanwhile, the Undo action is much more flexible for this situation can could easily resolve both of the cases.

**Comment by rwhirn** [comment]
I really have to **strongly** disagree. The escape key should **never** act as a "confirm" key and make a permanent entry that I didn't intend.  The escape key almost always "aborts"/"get me out of here" whatever you are doing. I must use the escape hundreds of times a day.  In TablePlus it almost never works the way you expect it to. When I click the SQL button and get a popup window showing the SQL for this filter my I hit "escape" to get out of that window, like I would any other modal popup - but it has no effect. And if something falls on my keyboard and types random characters into a field I would naturally hit escape to get out of the field without my entry being made. This is just a standard response to the escape key and I think it is really necessary here. It happens way too often.

**Comment by huyphams** [comment]
I've got good news for you @rwhirn I've changed the behavior, enjoy the patch: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by rwhirn** [comment]
Thanks so much! Its a lifesaver.
