### ISSUE TITLE
Find and replace not working 

### ISSUE THREAD

**Issue by Adam-mtd** [TablePlus/TablePlus-Windows#114]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.6.23

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 2.10 (90) x64

3. The steps to reproduce this issue: Highlighted section of code, ctrl + f, replace tab, change replace with text to desired text, then hit replace all, box comes up with "are you sure you want to replace all occurrences of X with X?". Click on OK, nothing happens, nothing happens when clicking replace either.

**Comment by huyphams** [comment]
Hi @Adam-mtd did you check the box: Match whole word?
I'm fixing some issue related to Find and Replace in multiple text editor tabs, improved the dark theme and turn off the `Match whole word` by default in this hot patch, if you have a chance, please give it a try and let me know the result: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by Adam-mtd** [comment]
Hi Huyphams, 
I did have ``match whole word `` ticked. The string that i'm trying to replace has quotations in it and that is what is causing it to not replace. I have unchecked the box and it removes it. The only issue with this is it removing the characters from the middle of strings without match whole word. I've also downloaded the patch and installed it.

**Comment by huyphams** [comment]
Could you give me an example and your expectation @Adam-mtd thank you.

**Comment by Adam-mtd** [comment]
Obviously a very simple example but.
" `select "
"     email_address "
" from  "
"      emails "
" where "
"      email_address = "example@email.com" " `

This is roughly the format of what i had copied out of the source code of the program the query exists in. The quotations marks at the beginning and end of each line needed removing, leaving the quotations around the "example@email.com", usually to do this i'd find and replace and match on whole word, that way only quotations on their own would be replaced, any that were part of something else would stay. However when using quotations combined with match whole word, nothing happens.

**Comment by huyphams** [comment]
I'm sorry, I still don't know how to do it with TablePlus, could you point out step by step with a similar text editor (like Sublime Text)?

If you want to achieve it in TablePlus, Please try to find and replace it with the input: " and the replace text is empty, and finally, put the quote back for the `example@email.com`
