### ISSUE TITLE
Crash in MSSQL BETWEEN query using unquoted numbers

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#115]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MSSQL Server 2014 (Express)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
90

3. The steps to reproduce this issue:
Open table 
Filter on primary id field using between
![image](https://user-images.githubusercontent.com/25158630/66364145-5c7e1b00-e94e-11e9-8a9b-de1b7c9338b3.png)

more debug
![image](https://user-images.githubusercontent.com/25158630/66364192-7ae41680-e94e-11e9-9cde-bb09fb70ad5f.png)

**Comment by rwhirn** [comment]
Oh yes, I remember now. I've seen this before.
That primary key field, csono is a "char(10)" type field
If I try to do a between using unquoted numbers it crashes

**Comment by huyphams** [comment]
Thank you very much @rwhirn I've patched it : https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
I also put some improvements to show data length in table structure in that build, hope it helps.

**Comment by rwhirn** [comment]
> I also put some improvements to show data length in table structure in that build, hope it helps.

That's great! I was going to ask about that. :)

**Comment by rwhirn** [comment]
Works perfectly! Thx.
