### ISSUE TITLE
With Cassandra Table Plus only show 1 table

### ISSUE THREAD

**Issue by niko44** [TablePlus/TablePlus-Windows#116]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Cassandra 2.2.8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
This bug appear since the build 88

3. The steps to reproduce this issue:
Only open a connection to a Cassandra database and you will see aonly one table (the first one).

![66382414-730e8b80-e9bb-11e9-9376-eda32e2a0a3a (1)](https://user-images.githubusercontent.com/13762589/66394534-b1b13f80-e9d5-11e9-9dc1-806e09a54aa0.jpg)
![66382413-730e8b80-e9bb-11e9-9572-cea07d305428](https://user-images.githubusercontent.com/13762589/66394576-ce4d7780-e9d5-11e9-8288-fdd158b606b7.jpg)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi, thank you for letting me know.
TablePlus is using this query on Cassandra 2 to get the table list: 

`SELECT keyspace_name, table_name FROM system_schema.tables where keyspace_name= <the keyspace name>`

Could you please run this query and let me know the result:
- Does it list all the table?
- Does the keyspace_name from the result are all the same?

**Comment by niko44** [comment]
hum :
PS C:\ACOSS\apache-cassandra-2.2.8\bin> .\cqlsh 10.223.192.83 9042

WARNING: console codepage must be set to cp65001 to support utf-8 encoding on Windows platforms.
If you experience encoding problems, change your console codepage with 'chcp 65001' before starting cqlsh.

Connected to cassandradmz at 10.223.192.83:9042.
[cqlsh 5.0.1 | Cassandra 2.2.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
WARNING: pyreadline dependency missing.  Install to enable tab completion.
cqlsh> SELECT keyspace_name, table_name FROM system_schema.tables where keyspace_name='x2d6032cc_c5f6_4c23_8fa4_611fd4dd1fe0_group_3'
   ... ;
`InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace system_schema does not exist"`
cqlsh>

**Comment by huyphams** [comment]
Sorry, I posted the wrong query, it should be:
`SELECT keyspace_name, columnfamily_name FROM system.schema_columns where keyspace_name= <your_key_space>`

**Comment by niko44** [comment]
Yes, it's works :
![image](https://user-images.githubusercontent.com/13762589/66396998-36528c80-e9db-11e9-8841-a1dd5a9ec5c3.png)

**Comment by huyphams** [comment]
Hi @niko44 thank you, please download this hot patch, it should solve the issue: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by niko44** [comment]
Great!!! Thank you very much ;)

**Comment by ChristineChetty** [comment]
I am trying to connect to Cassandra using Table Plus. I have 3 node cluster running on aws.

My host is public Ip, port 9042. Using SSH. What would the Server address be, AND THE PORT 9160?
