### ISSUE TITLE
When restricting columns cannot change order of columns

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#118]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.0.20

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
92

3. The steps to reproduce this issue:
Open a table
click on "Columns"
select some fields
rearrange order of the fields
click apply
fields display in order they exist in table

![image](https://user-images.githubusercontent.com/25158630/67124567-67d80e80-f1b8-11e9-991c-f16e66ac128c.png)

**Comment by huyphams** [comment]
The column filter has nothing to do with the table view column position. You can change the column order by dragging it directly in grid.
