### ISSUE TITLE
Missing underscore in column names after sorting

### ISSUE THREAD

**Issue by lszymkowiak** [TablePlus/TablePlus-Windows#119]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.4.7,

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
92

3. The steps to reproduce this issue:
Sort column with underscore in name
![Adnotacja 2019-10-23 090431](https://user-images.githubusercontent.com/1734546/67366893-ab45ca80-f574-11e9-948d-f0e25d6727bb.png)
![Adnotacja 2019-10-23 090502](https://user-images.githubusercontent.com/1734546/67366919-b8fb5000-f574-11e9-9f7e-ad4b1407c200.png)

**Comment by huyphams** [comment]
Thank you @lszymkowiak I've fixed it!

**Comment by huyphams** [comment]
Meanwhile, you can download the hot patch here: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
