### ISSUE TITLE
cockroachdb support

### ISSUE THREAD

**Issue by bladefist** [TablePlus/TablePlus-Windows#12]
The mac version recently got this. It's built upon the postgres driver.  I need this and will be a paying customer once it's added.  

https://github.com/TablePlus/TablePlus/issues/648

https://github.com/TablePlus/TablePlus/issues/374

Thanks!

**Comment by huyphams** [comment]
Almost there , please wait until Monday (y)
<img width="1122" alt="cockroach" src="https://user-images.githubusercontent.com/3654622/46221176-93eadc80-c376-11e8-96e8-5a0d3ac6a3f2.PNG">

**Comment by bladefist** [comment]
Very excited!  Will this support schema modifications,  query autocomplete and data editing? Just what you have is good enough but the more the merrier.

**Comment by bladefist** [comment]
@huyphams did you release the binary for this? I just downloaded it from the main website and no worky. Thanks.

**Comment by huyphams** [comment]
It's already supported. Have you tried to create a CockrachDB connection?

**Comment by bladefist** [comment]
figured it out. You have to select a database in the connection create process. If you leave it blank, it will not work, it will open the main window up w/ everything blank and not working.

**Comment by huyphams** [comment]
Hmm, this is one of the know issues, when the database is blank, the command `SHOW DATABASES;` return no result => the database listing empty.

**Comment by bladefist** [comment]
You could default to `system` or `defaultdb`

That is odd though.

**Comment by huyphams** [comment]
TablePlus has an auto-updater. You just need to click on update and it will download and self-replace the binaries (portable).
"You could default to system or defaultdb" => Sure I will give it a try.
