### ISSUE TITLE
Filter field names disappear after reconnect

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#120]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB10.0.20

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
92 (2.10.2)

3. The steps to reproduce this issue:
When disconnected from the database
click on a table (one that has remembered filters from last use)
get popup that MySQL has gone away
click "Reconnect"
table pane populates
but filter fields are now empty and the dropdown is empty except for Raw SQL and Any Column
must close that table and reopen to get field names back

**Comment by huyphams** [comment]
Hi, thank you. I've patched it: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by rwhirn** [comment]
all fixed, thx!
