### ISSUE TITLE
Feature Request: Better closing icon for tabs

### ISSUE THREAD

**Issue by HymanZHAN** [TablePlus/TablePlus-Windows#122]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
PostgreSQL 11.5

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
92

**3. The steps to reproduce this issue:**
Just launch the program

**Description:**
Not a huge thing but could you design a dedicated icon for the "X" on the tab? Also adjust the positioning please.

Screenshot:
![image](https://user-images.githubusercontent.com/26806995/67611446-c0367f80-f767-11e9-9aae-044120a45464.png)

Using a letter "X" as the "close icon" makes the UI feel cheap and developer art. I understand it's still early days for the Windows version but as a paying customer who paid $99 I would expect something more polished.

**Comment by huyphams** [comment]
Hi @HymanZHAN we've fixed it already. it will be released in the next update.

**Comment by HymanZHAN** [comment]
@huyphams Great to hear that. Thanks!

**Comment by huyphams** [comment]
We released the build 94 which includes this fixes. Thanks!
