### ISSUE TITLE
new closing icon is not shown

### ISSUE THREAD

**Issue by jagDanJu** [TablePlus/TablePlus-Windows#123]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0.17
Windows 10 Pro - Version 1903 - Build: 18362.418

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
94

3. The steps to reproduce this issue:
the new closing icon is not shown

![image](https://user-images.githubusercontent.com/3613218/67623255-4e237080-f823-11e9-8bec-d3ae0ba7fefe.png)

![image](https://user-images.githubusercontent.com/3613218/67623245-3815b000-f823-11e9-9174-e10ee6d99422.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @jagDanJu let us check.

**Comment by huyphams** [comment]
Hi @jagDanJu please try this patch https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0 let us know how's it going thanks.

**Comment by jagDanJu** [comment]
@huyphams Unfortunately not...

**Comment by huyphams** [comment]
Thank you, I've updated the icon search patch, hope it works on this patch: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by jagDanJu** [comment]
@huyphams Hmpf... Sorry, but it didn´t work..

**Comment by jagDanJu** [comment]
@huyphams try it on my laptop (Windows 10 Enterprise - Version 1903 - Build: 18362.418) and it works.. Any idea?

**Comment by huyphams** [comment]
The one which does not work is the Windows 10 server?

**Comment by jagDanJu** [comment]
Nope.. It's my workstation.. 
I'm tried it now on my windows server 2012R2 and there it also do not work

**Comment by huyphams** [comment]
Thank you, I'm investigating it.

**Comment by huyphams** [comment]
Hmm, I'm not sure if it could fix, could you give it a try @jagDanJu https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
Thank you!

**Comment by jagDanJu** [comment]
hey @huyphams,
the patch don´t work...

**Comment by huyphams** [comment]
Thank you @jagDanJu for trying so many patchs, I've tried an other approach in this build: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0 could you please try it and let me know the result

**Comment by jagDanJu** [comment]
that´s fine ;)
Unfortunately it does not work..
can i help you with more information?

**Comment by huyphams** [comment]
it seems like a big on the Windows platform. I can reproduce it now by installing it on my Windows 10 32 bit machine.

**Comment by jagDanJu** [comment]
Ah okay!
I only have 64 bit systems.
What I find funny is that the same build is running on the laptop and the workstation, but it does work on the laptop and not on the workstation
the only difference is that the laptop is a windows 10 enterprise and the workstation has a windows 10 pro

**Comment by huyphams** [comment]
Not sure about your, but this fix works on my windows 10 32 bit: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by jagDanJu** [comment]
Jep, thats work! Great. Thx guy!
