### ISSUE TITLE
Hex blobs no longer legible

### ISSUE THREAD

**Issue by KBulmer** [TablePlus/TablePlus-Windows#125]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
94

3. The steps to reproduce this issue:
TablePlus no longer converts binary strings to utf8 before displaying them, like it did in version 90 and earlier.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks, we're fixing it.

**Comment by huyphams** [comment]
Hi @KBulmer please apply this patch, it should fix the issue: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by KBulmer** [comment]
Works great! Thanks for fixing it so quickly!
