### ISSUE TITLE
Reconnect abandons changes that were yet to be committed

### ISSUE THREAD

**Issue by rohanc** [TablePlus/TablePlus-Windows#126]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgresql 9.6.8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.1.1 (94)
3. The steps to reproduce this issue:

I often leave my PC on overnight, during which time it sleeps and then resumes. Somehow during the process, the database connection to my locally-hosted virtual machine running Postgresql stops working. This seems fair enough. Because I have also left TablePlus running, I pickup where I left off and make changes to data. Here's where the problem starts:

Step 1: Starting with a stale connection, try to make changes to a database field in the detail panel.
Step 2: Press CTRL+S to Commit changes. Note that an alert dialog box pops up with no error message. (That deserves an Issue in itself.)
Step 3: Select "Reconnect" from the Connection menu. All changes are abandoned!

I consider this an important bug because it means I lose some work, everytime it happens.

**Comment by huyphams** [comment]
It's fixed on this patch (https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0) or on the version 3.5.1
Thanks.
