### ISSUE TITLE
Suggestion for Row Copy

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#129]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
any

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
94

3. The steps to reproduce this issue:
![image](https://user-images.githubusercontent.com/25158630/67994399-1c3f4f00-fc13-11e9-98de-56c08d5e7d1d.png)
The right click on row and "Copy As..." is an _**amazing**_ feature. One thing you might add: "Copy as  Tab Separated Values". Just like "Plain Text" but if there were tabs instead of commas between each field then you can paste that directly into Excel and it recognizes the tabs as separators and puts each field into its own cell.

**Comment by huyphams** [comment]
Currently, the default delimiter copy as CSV is `,` 
The next update will have some changes.
1. Added CSV preferences in the setting where you can change the default delimiter.
2. Change the default from , to tab.

Here is how is it on the macOS.
<img width="921" alt="csv" src="https://user-images.githubusercontent.com/3654622/67996236-2ff7af00-fc2d-11e9-9529-b62deba3927d.png">

In the meantime, you can just use Control + C to copy CSV with tab, the downside is that there is no include header option.

**Comment by huyphams** [comment]
I decided to simplify it:
TablePlus now has options: copy as TSV and TSV with header.
You can download the patch here: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by rwhirn** [comment]
That works great
