### ISSUE TITLE
Tableplus shuts down mysql

### ISSUE THREAD

**Issue by ZayRTun** [TablePlus/TablePlus-Windows#13]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
Mysql 5.7.19

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):  
Build 16

3. The steps to reproduce this issue: 
After filling the required fields to create a connection, once i press test button it says the connection is okay but right after that mysql shuts down.  And the same thing happens when i click on the connect button. Just shuts mysql down.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by ZayRTun** [comment]
I am currently using Mysql workbench it works. I was wondering if the issue is coming from wamp cause I am using mysql that i got thru wamp server

**Comment by ZayRTun** [comment]
I've got it working finally. i had to uninstall wamp server and all that comes with it then installed php and mysql 8 individually. And now its working. By the way loving the GUI of TablePlus and would suggest for SQL functions like NOW() to be able to insert into the tables that would make it more awesome...

**Comment by huyphams** [comment]
Hey thanks, sure, we're working on a big update for Windows with a lot of new features.

**Comment by huyphams** [comment]
Close because it was an old MySQL bug.
