### ISSUE TITLE
SQL Query Editor Autocomplete uses wrong table when "_" in name

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#131]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.17

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
94

3. The steps to reproduce this issue:
Here's my query with autocomplete
![image](https://user-images.githubusercontent.com/25158630/68346628-3fa64600-00ba-11ea-90a2-2e9a9cf017de.png)

Here's the structure of table I am querying
![image](https://user-images.githubusercontent.com/25158630/68346720-7aa87980-00ba-11ea-9525-a32d570c0cc3.png)

Here's the structure of table TablePlus **_thinks_** I'm querying
![image](https://user-images.githubusercontent.com/25158630/68346754-8f850d00-00ba-11ea-8d55-0eb694ad0f81.png)

**Comment by huyphams** [comment]
Thanks @rwhirn I've patched it: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by huyphams** [comment]
Please let me know if you're still seeing it thanks!
