### ISSUE TITLE
Pixelated icons in welcome screen

### ISSUE THREAD

**Issue by tmthn** [TablePlus/TablePlus-Windows#132]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 10.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
96

3. The steps to reproduce this issue:
I am using a Dell XPS 15" notebook with high resolution display and a second 27" monitor with a normal resolution display panel. The images within the welcome screen are in this setup always pixelated.

![screenshot](https://user-images.githubusercontent.com/5840314/68476358-be21f580-022a-11ea-8fd2-b4a58bd8e413.png)

**Comment by huyphams** [comment]
Hi @tmthn could you please try this patch and see how is it going?
https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
Thank you!

**Comment by tmthn** [comment]
Hi @huyphams seems to be fixed! I installed the regular update from within the app.
