### ISSUE TITLE
Feature Request: User Permission Management

### ISSUE THREAD

**Issue by jordonbrill** [TablePlus/TablePlus-Windows#133]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 96

3. The steps to reproduce this issue: N/A

Would it be possible to add user permission management?

**Comment by huyphams** [comment]
Hi @jordonbrill We're working on it!

**Comment by huyphams** [comment]
Hey @jordonbrill you can try this patch, we've added the user management for MySQL:
https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
