### ISSUE TITLE
Really slow working with large database

### ISSUE THREAD

**Issue by ngocphamm** [TablePlus/TablePlus-Windows#134]
1. Which driver are you using and version of it:
SQL Server. Not 100% sure about version but I think it's SQL Server 2017.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.11.1 build 96

3. The steps to reproduce this issue:
* Connect to a large (or very large, I don't know how big this is considered) database 
* See TablePlus struggles: loading initial table list after connecting, filtering through the "Search for items" box on top of the table list, or do Open Anything.

Few diagnostic info
* This does not happen with SQL Server Management Studio (SSMS), or DBeaver. Connecting, and instant filtering (DBeaver) are still fast.
* Our database has **827 tables, 234 views, and 2924 stored procedures** at the moment.

Also, I noticed that views and tables are mixed together in the list. Is this an expected behavior, and should I open a separate issue for that?

**Comment by huyphams** [comment]
Hi @ngocphamm thank you for letting us know, could you please try this patch and see how's it going?
https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
Thank you!

**Comment by ngocphamm** [comment]
Looks promising already!

* App start: Still quite slow saying "Collecting database information..."
* After that, filtering using the box at the top of the left side bar feels a lot faster
* However, Ctrl-P is still lagging pretty bad
* Then after 10 minutes, I came back to the app and try Ctrl-P/filter box, and it was lagging again, then crashed.

Thanks for the quick attempt! This is really appreciated!

**Comment by huyphams** [comment]
I've updated the build above @ngocphamm still the same link, the open anything is must faster now.

**Comment by ngocphamm** [comment]
Yes both filter box and Open Anything are a lot faster now!

2 things
1. So Escape doesn't close Open Anything? It does in the Mac version
2. How can I update a Stored Procedure in SQL Server? I can open it with Open Anything but I don't see any button to "save" it. Actually I can't even edit it. The Stored Procedure content being displayed in the app is readonly it seems.

**Comment by huyphams** [comment]
Currently, we do not support that feature in the Windows version, but we're working on it.
> App start: Still quite slow saying "Collecting database information..."
TablePlus uses these queries:

- Load table listing:
```
SELECT s.name AS table_schema,t.name AS table_name,'BASE TABLE'AS table_type FROM sys.tables AS t JOIN sys.schemas AS s ON t.schema_id=s.schema_id UNION SELECT s.name AS table_schema,t.name AS table_name,'VIEW'AS table_type FROM sys.views AS t JOIN sys.schemas AS s ON t.schema_id=s.schema_id;
```

Could you please run this query and let me know the result?

**Comment by ngocphamm** [comment]
The 2  queries you posted above are the same. 

It runs in 131ms here. Could be the SQL Server caching? I'm not sure. I don't have control of that server so I can't really do anything to debug that. Sorry.

**Comment by huyphams** [comment]
I don't know what was the root cause. Basically, when initializing, TablePlus ran 4 queries:

- Get the server version:
```
SELECT @@version;
```

- Schema list:
```
SELECT name FROM sys.schemas;
```
- Function list:
```
SELECT s.name AS function_schema,o.name AS function_name,m.definition AS create_statement,CASE WHEN o.type='P'THEN'PROCEDURE'ELSE'FUNCTION'END AS function_type FROM sys.sql_modules m INNER JOIN sys.objects o ON m.object_id=o.object_id INNER JOIN sys.schemas s ON o.schema_id=s.schema_id WHERE o.type!='V';
```
- Table list:
```
SELECT s.name AS table_schema,t.name AS table_name,'BASE TABLE'AS table_type FROM sys.tables AS t JOIN sys.schemas AS s ON t.schema_id=s.schema_id UNION SELECT s.name AS table_schema,t.name AS table_name,'VIEW'AS table_type FROM sys.views AS t JOIN sys.schemas AS s ON t.schema_id=s.schema_id;
```

Could you run 4 queries and let me know how long does it take?

**Comment by huyphams** [comment]
I gave the wrong query in the previous comment https://github.com/TablePlus/TablePlus-Windows/issues/134#issuecomment-553539420 sorry about that. these 4 queries above are correct and I think the issue is on the function list.

**Comment by ngocphamm** [comment]
Probably the query to get function list. The result set appears immediately (I don't know how many, though), but the status bar has "Fetching: xx.xxx S" that only stop around 15 seconds.

**Comment by huyphams** [comment]
This is improved version:
```
SELECT s.name AS function_schema,o.name AS function_name,CASE WHEN o.type='P'THEN'PROCEDURE'ELSE'FUNCTION'END AS function_type FROM sys.objects o INNER JOIN sys.schemas s ON o.schema_id=s.schema_id WHERE o.type!='V';
```
I will apply this on in the new update, thank you for testing the app.

**Comment by ngocphamm** [comment]
Yay this one is pretty fast (~500ms here), but I'm browsing the list it returns and I see those `FK_....` one being listed as `FUNCTION`. Pretty sure those are foreign keys. 🤔

**Comment by huyphams** [comment]
I fixed it now, thank you very much!
Download patch: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by ngocphamm** [comment]
The new build looks good! Thank you for your super fast response!
