### ISSUE TITLE
Deleting within cell-edit deletes entire row

### ISSUE THREAD

**Issue by dwyer14** [TablePlus/TablePlus-Windows#136]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**MariaDB 10.4.6**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**96**

3. The steps to reproduce this issue:
- Enter into a cell
- Remove at least one character using delete (not backspace)
- Exit the cell
- Note that row is marked for deletion (turns red)

**Comment by huyphams** [comment]
Hey @dwyer14 thank you for letting me know. I fixed this issue, you download and apply this path: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by dwyer14** [comment]
Great, thanks for the speedy fix! 🎉
