### ISSUE TITLE
How do I view my current database name?

### ISSUE THREAD

**Issue by qttq23** [TablePlus/TablePlus-Windows#137]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server 2017

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
TablePlus version 2.11.1

3. The steps to reproduce this issue:
> connect database management system> select a database > go to somewhere else and do something...>return to TablePlus and forget the name of database selected.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi, it right on the title bar.
<img width="1386" alt="abc" src="https://user-images.githubusercontent.com/3654622/69880927-bc83a480-12a1-11ea-8807-d36d5a98e5ff.png">
If you have any further questions, please email nick@tableplus.com thank you.
