### ISSUE TITLE
MySQL "export multiple tables" is whacky

### ISSUE THREAD

**Issue by dwyer14** [TablePlus/TablePlus-Windows#138]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.23

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
v100

3. The steps to reproduce this issue:
- Open connection w/ multiple tables
- Select multiple tables
- Right click > Export...
- SQL tab > Export
- Compare column names across multiple tables
(All columns are the same, regardless of table.)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by dwyer14** [comment]
Also, it seems to cap the number of columns pulled based on that first table.
First export row, which has six columns:
```sql
INSERT` INTO `db`.`table1` (`id`,`donation_id`,`access_key`,`expires_at`,`created_at`,`updated_at`) VALUES ('1','6','1',NULL,NULL,NULL);
```
Last export row, which should have 23 columns:
```sql
INSERT INTO `db`.`table2` (`id`,`donation_id`,`access_key`,`expires_at`,`created_at`,`updated_at`) VALUES ('4762','81a5d7ae-c91a-4b67-98fe','3',NULL,'ch_1DgGjAA-xyz','10000');
```

**Comment by huyphams** [comment]
Hey thank you, I fixed it, could you please try this patch: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0 and see how is it going?

**Comment by huyphams** [comment]
Nevermind, still have some issues. I'm fixing it.

**Comment by huyphams** [comment]
Hi @dwyer14 if you have a chance, please try this patch: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0 thank you!

**Comment by dwyer14** [comment]
That fixed it! Got the latest update (build 102) installed, and all seems well. Thanks for the quick fix! 🎉

**Comment by huyphams** [comment]
Thanks for the confirmation, please email me at nick@tableplus.com we would like to offer you a free license (or upgrade the current license if you already have one). 👍 thank you so much!
