### ISSUE TITLE
Columns Select Broken

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#139]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MS SQL Server 2014 (Express)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
102

3. The steps to reproduce this issue:
Open table
click "Columns"
select "All Columns"
First Problem: I used to use this for writing queries, it would give a comma separated list of all fields. I would copy and paste that into a SQL query window and delete any fields I did not want in my query (see Ability to get All Fields in a query #99). Now it does some weird colored display of field names and they are not copyable for pasting.
Select All and hit Delete to clear out the list.
Select a field and nothing gets entered in Columns Box. Hit Clear has no affect. Closing Columns and opening again has no effect. Closing table and opening again and clicking Columns has no effect, in fact now all the fields are gone from the dropdown.
Finally, this whole dropdown method is really hard to use. If I want to select 20 fields to display, that means I have to move mouse to the dropdown and click, scroll down to the field I want move mouse and click, then the dropdown closes so I have to move mouse back to the dropdown and repeat twenty times. If it were a regular side by side selection window where all fields are listed on the left and you can select as many as you want and move them to the selection window on the right (and vice versa) it would be much easier to use. And please put back the comma separated list of fields in regular text that is copyable.

**Comment by rwhirn** [comment]
Also, now there _**really**_ is no way to get the base query over into the SQL Command window. I used to copy the filter query, which says "SELECT *" even though it is _**not**_ all fields (see SQL Button doesn't show columns selected #65). Then I would go to the Columns window and copy the fields I had selected and put that all into a SQL Command window.

**Comment by huyphams** [comment]
We're working on version 3.0, so the hot patch could be delayed a little bit. This issue could be resolved very easy by the following solutions:

1. Added an all field into the auto-suggestion popup, if we select it, it will auto add all the fields automatically.
2. Support an ability to copy text in the token fields.

We're also implementing the query assistance (new features) which also helps you to write queries faster.

**Comment by huyphams** [comment]
The 1st option.
![2019-12-15 00 52 04](https://user-images.githubusercontent.com/3654622/70858278-997a0700-1ed5-11ea-9e4a-2bd0733a4a49.gif)

**Comment by huyphams** [comment]
You can try this patch @rwhirn https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
TablePlus now supports all field in auto-completion
<img width="975" alt="auto-completion" src="https://user-images.githubusercontent.com/3654622/70866402-8bf96700-1f3f-11ea-9e45-e6a7646d541b.png">

We're working on the `2. Support an ability to copy text in the token fields.`

**Comment by rwhirn** [comment]
This helps, but the dropdown selection method is still not good for selecting more than a couple fields.
A multi-selection box is much more useful
![image](https://user-images.githubusercontent.com/25158630/70869492-16969200-1f51-11ea-8647-287e39dbdc89.png)

**Comment by huyphams** [comment]
That was the `query assistance` I've mentioned before @rwhirn we're working on it.

**Comment by huyphams** [comment]
1 and 2 have been implemented and released in the release 3.0
We're working on query assistance and some other stuff, so I'm closing this issue for now.
