### ISSUE TITLE
Opening new SQL Tabs re-opens old tabs

### ISSUE THREAD

**Issue by bladefist** [TablePlus/TablePlus-Windows#14]
On latest, 16.

I close a query tab.  Open a new one.  It shows my old tab queries.  

We also need a way to save/open .sql files.

Thanks!

**Comment by huyphams** [comment]
Hey @bladefist I don't understand, can you please clarify again. TablePlus saves the last SQL query in SQL Tab. 
This is a standard behavior because many users use it to save their temporary work.
We also need a way to save/open .sql files. => Sure, I will add it.

**Comment by bladefist** [comment]
I thought this was a bug at first but it's more likely a feature, thanks.
