### ISSUE TITLE
SQL Dump should include CREATE TABLE and DROP IF EXISTS statements

### ISSUE THREAD

**Issue by bertoost** [TablePlus/TablePlus-Windows#140]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 8.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

V2.12.10 (102)

3. The steps to reproduce this issue:

- Select the tables to export
- Right click and choose "Export" from the menu
- Click on tab "SQL" and no options are shown

It should be possible to chose to include "create table" statements and "drop if exists".

The exported dump file also contains the database name inside INSERT INTO statements and that should not be there. Since the name can be different on the server where you want to import the dump again.

For now using HeidiSQL instead, but really would like to use my licensed TablePlus on Windows as well

Thanks in advance.

**Comment by huyphams** [comment]
All those features are planned. We will release it very soon! thanks @bertoost
