### ISSUE TITLE
Delete rows shortcut key missing Windows

### ISSUE THREAD

**Issue by daugaard47** [TablePlus/TablePlus-Windows#141]
In version Build 96 you added a delete row shortcut key.

In latest version TablePlus 3.0 - Build 110 | Windows version, the delete shortcut key is not working, missing or changed.

Can you please advise or bring this back. Simple delete key would be ideal.

Other than that, I'm loving TablePlus!

**Comment by huyphams** [comment]
Hi, thank you for the feedback. The shortcut keys are still there, but there was an focusing issue. I've fixed it, could you please try this patch and see how's it going?
https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by daugaard47** [comment]
That worked great! Thank you for the quick response and fix. Much appreciated!
