### ISSUE TITLE
Console Log view in Windows?

### ISSUE THREAD

**Issue by zzz2496** [TablePlus/TablePlus-Windows#143]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 302 (110)
3. The steps to reproduce this issue:

Where is the Console Log view on Windows version of TablePlus? And there is no query timer (time elapsed in query execution).

Thanks.

**Comment by huyphams** [comment]
It's being developed @zzz2496 we're going to release this feature in Jan-2020.

**Comment by huyphams** [comment]
You can download the patch which supports console log here: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
Please let me know if you see any issue.
Thanks

**Comment by zzz2496** [comment]
Thank you for your response.
