### ISSUE TITLE
Suggestion: Drop shadow and/or darker border for light theme

### ISSUE THREAD

**Issue by bwat47** [TablePlus/TablePlus-Windows#144]
Since the UI re-design (which I quite like overall), I've found that it can be difficult to differentiate tableplus from other open windows. I attached a screenshot as an example.

![image](https://user-images.githubusercontent.com/1442520/71520941-a5c67280-288c-11ea-91e2-2ff955f140ce.png)

It seems like this could be mitigated if the tableplus light theme either had a darker colored 1px window border, and/or had a drop shadow around the window.

For example, I attached a screenshot of an app that both has a black 1px border, and a drop shadow and it stands out much more clearly against other open windows: 

![image](https://user-images.githubusercontent.com/1442520/71521070-1f5e6080-288d-11ea-942e-9a291c7e0692.png)

**Comment by huyphams** [comment]
Thanks @bwat47 
Please download and try this patch: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
it has the drop shadow.

**Comment by bwat47** [comment]
Thanks, that looks much better!

**Comment by bwat47** [comment]
Note: I noticed one minor issue with this build:

When you hover your mouse over the minimize/maximize/close buttons on the top right, the highlight effect doesn't display unless you specifically place your mouse cursor at the very bottom of the button

**Comment by huyphams** [comment]
Yep, I've noticed it too, I'm fixing it. but it's not a big deal, you can use it. I will send a hotfix build shortly.

**Comment by huyphams** [comment]
I just fixed it: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
Thank you
