### ISSUE TITLE
Windows version limits 3 tabs unless you purchase

### ISSUE THREAD

**Issue by bladefist** [TablePlus/TablePlus-Windows#15]
I'm ready to purchase, got credit card in hand... Where do I input the license key?

**Comment by Tungtono** [comment]
Hey @bladefist, please click on register button from the welcome screen, it will pop out this box to enter license key:
<img width="659" alt="screen shot 2018-10-13 at 5 52 22 am" src="https://user-images.githubusercontent.com/10219818/46897422-b6b7dd80-ceac-11e8-8cc9-85b225d112d9.png">
