### ISSUE TITLE
Wrong hint

### ISSUE THREAD

**Issue by george-jk** [TablePlus/TablePlus-Windows#150]
1. driver: MariaDB 10.1.38

2. TablePlus 3.1.2 build 112

3. issue:

When hover "reload" button it display "Open anything (Control + P)" hint.

![image](https://user-images.githubusercontent.com/50808777/71780457-3e669c00-2fcb-11ea-8ac1-a95c78bca54b.png)

**Comment by huyphams** [comment]
Hi @george-jk thank you. I've fixed this issue recently.
