### ISSUE TITLE
Clicking on the status bar does not display more details

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#151]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
112

3. The steps to reproduce this issue:
Click on the status bar. The documentation says that allows you to view more details and reassign color.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by son11592** [comment]
Hi @libcub, please update the application to the latest version. This feature has been added.
