### ISSUE TITLE
Missing toolbar buttons

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#152]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
112

3. The steps to reproduce this issue:
The Show Workspaces and User Management buttons are missing from the toolbar.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @libcub the docs currently is using for the macOS version. We've not published the document for Windows yet. And it also has a different design when compared with the macOS.

**Comment by libcub** [comment]
Oops, I see that User Management is only for MySQL right now.

**Comment by huyphams** [comment]
The Windows has User Management, you can open it by Click Menu > Connection > User management.

**Comment by libcub** [comment]
Oh, gotcha. Maybe put a note to that effect at the top of the documentation?

**Comment by huyphams** [comment]
Yeah, actually we already have it locally, we will deploy it later, along with the Website version 3.0
