### ISSUE TITLE
Allow GUI editor to accept lowercase "no" (and ideally just "n") for is_nullable

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#153]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
112

3. The steps to reproduce this issue:
Ctrl-S does not commit.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @libcub thank you for the feedback I appreciate it, however, please try to make it cleaner. I can't reproduce the issue with `Ctrl-S does not commit.`

**Comment by libcub** [comment]
Sorry, I should have given more detail. In the GUI editor, I change is_nullable on a column and hit enter. The changed item turns yellow as expected. When I type Ctrl-S nothing happens. Same thing if I edit in the right panel. Running a direct ALTER TABLE does change the nullability.

Ctrl-S does work if I change column_name, so perhaps the problem is specific to is_nullable. Clicking the Commit button also does not work for is_nullable.

**Comment by libcub** [comment]
This is also the case when adding a column after first. I can add the first column as is_nullable. Subsequent columns I define as is_nullable=NO change to YES when I commit.

**Comment by huyphams** [comment]
Hi @libcub could you please try this hot-patch and see how's it going: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
Thank you!

**Comment by libcub** [comment]
No, sorry, it didn't fix the problem.

**Comment by huyphams** [comment]
Hi @libcub thanks for confirming, however, I couldn't reproduce the issue anymore. If I change the is_nullable to YES or NO the command is generated correctly. Could you make a gif that demonstrates the issue? thank you!

**Comment by huyphams** [comment]
I've made a gif that the steps:
![2020-01-08 01 44 09](https://user-images.githubusercontent.com/3654622/71953443-9d3d3880-31b8-11ea-9f2e-62791a61d6c4.gif)

**Comment by libcub** [comment]
Okay, I played around more. I see now the actual issue is case. Entering "NO" works. Entering "no" does not work. So it is much less of an issue. Would it be possible to allow lowercase "no"? I'll change the title of the issue.

**Comment by huyphams** [comment]
Sure, I've updated the hot-patch: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0 it should fix the issue. Thanks @libcub

**Comment by libcub** [comment]
Thanks!
