### ISSUE TITLE
Incorrect hover text for Refresh button

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#154]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
112

3. The steps to reproduce this issue:
Hover the mouse pointer over the refresh button. The text is "Import anything (Control + P)".

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks, @libcub it's duplicate with https://github.com/TablePlus/TablePlus-Windows/issues/150 and also fixed recently (but not release).
