### ISSUE TITLE
Reload Icon

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#159]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Any

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
112

Tooltip on mouseover the "Reload" icon says "Open anything (Control + P)"

**Comment by huyphams** [comment]
Hi @rwhirn thank you for the feedback. It's duplicated with https://github.com/TablePlus/TablePlus-Windows/issues/154 and https://github.com/TablePlus/TablePlus-Windows/issues/150 
I've fixed it in: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
