### ISSUE TITLE
Reordering from the GUI doesn't affect on copy

### ISSUE THREAD

**Issue by Arlington1985** [TablePlus/TablePlus-Windows#161]
1. Which driver are you using and version of it: PostgreSQL 10.11

2. Which TablePlus build number are you using: 112

3. The steps to reproduce this issue: Execute the Select SQL which reproduces 100+ results. Copy one unique number from the first line or write it down somewhere. Then try to reorder them with the help of caption of the result table. Then copy again from the first row and the same field which you copied before. You will see although you reordered it again the after double click you will get previously copied value. 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @Arlington1985 thank you for the feedback. I can reproduce and fix it. If you have a chance, please install this patch and let me know the result: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by Arlington1985** [comment]
Hi @huyphams. Sorry, but I don't have a DEV instance(server) and I don't want to install it on PRD. I prefer to download from the official source.

**Comment by Arlington1985** [comment]
And thank you for your quick fix

**Comment by huyphams** [comment]
Sure, you can download it here: https://tableplus.com/release/windows/tableplus_latest

**Comment by Arlington1985** [comment]
I tested, but still has the same bug

**Comment by Arlington1985** [comment]
I think you might be not propagated yet, because I still see release 112 after reinstalling.

**Comment by huyphams** [comment]
I'm not sure why it still happening at your end but here is mine, I just downloaded the build above.
![2020-01-08 01 42 18](https://user-images.githubusercontent.com/3654622/71953325-446da000-31b8-11ea-8a39-f42344cfaa96.gif)

**Comment by Arlington1985** [comment]
I think you misunderstood me. You are changing order of the column, but my issue was different. Try to query comments table and then reorder it by the row, means ORDER BY any_field but with clicking two times to the caption of the columns. Then try to copy from there and check if it's coping correctly or the first line from the previous order, which was originally query was executed

**Comment by huyphams** [comment]
I've tried with `order by` and sorting, please check the gif below. am I missing something @Arlington1985 
![2020-01-08 09 35 56](https://user-images.githubusercontent.com/3654622/71982309-8e777580-31fa-11ea-8bd7-e3dfb6a22d8a.gif)

**Comment by Arlington1985** [comment]
Double click to value inside column and try to copy only the column value. You will see then difference

**Comment by huyphams** [comment]
Got it, originally, TablePlus does not support sorting a result from multiple tables (Actually it works but the sort result is incorrect. If you sort numbers, it treats the number as string). I've fixed it thanks @Arlington1985
