### ISSUE TITLE
Suggestion: Execute of the statement without selecting statement itself

### ISSUE THREAD

**Issue by Arlington1985** [TablePlus/TablePlus-Windows#162]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 10.11

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 112

3. The steps to reproduce this issue:
I would like to have a new future, like in TOAD, which allows the execution of the SQL in the current line or till the line where ";" stands if no selected lines. Currently, it tries to execute the whole script in the open window. It will help execute the script without marking the lines. Very useful feature and saves a lot of time, especially when you used to work only with keyboard or just using the touchpad, so not necessarily need to mark the statement

**Comment by huyphams** [comment]
Hi @Arlington1985 TablePlus has already supported this feature. However, it works a bit different with TOAD. You have to separate queries by the semicolons.

**Comment by huyphams** [comment]
Here is the demonstrate gif:
![2020-01-08 01 39 02](https://user-images.githubusercontent.com/3654622/71953185-c4473a80-31b7-11ea-8a20-830f83918314.gif)
