### ISSUE TITLE
[Feature Request] Don't open new tab every time you select a table

### ISSUE THREAD

**Issue by Deadpikle** [TablePlus/TablePlus-Windows#165]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Windows 3.1.4 (112) - x64

3. The steps to reproduce this issue:

* Open up any database (tested with MS SQL and SQlite)
* Click some table names
* Every click of a new table name opens a new tab, thus quickly limiting the number of tabs you can have in the free version.

Desired behavior: Work like macOS, where an unused tab is replaced with the new table that you selected.

**Related issue**: https://github.com/TablePlus/TablePlus/issues/397

P.S. Thanks for the great software! Also, the recent UI update on Windows improves things a lot. :)

**Comment by libcub** [comment]
This seems to be resolved for me, using PostgreSQL 12.1 and TablePlus build 128.

**Comment by AnsonH** [comment]
Seems like TablePlus is still opening a new tab every time I click on a table name. I'm using Windows 10, MariaDB 10.4.14 and TablePlus build 140. I believe this issue(?) is still unresolved

**Comment by Loyen** [comment]
TablePlus 3.10.1 (142). When clicking on tables from a MySQL connection it opens permanently and not just as a preview. On MacOS it just previews the tab unless I doubleclick or do a modification of some sort.

**Comment by mtaki14** [comment]
@Loyen That sounds perfect. Also a big plus is the familiarity factor, when coming from something like VS Code, that works in the same manner.

**Comment by huyphams** [comment]
The "Only keep the modified tabs" has been implemented 💯
