### ISSUE TITLE
Highlight Data or Structure button, showing which one is current, as in Mac version

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#166]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
112

3. The steps to reproduce this issue:
Display a table. Click on Data and Structure buttons. Their display does not change.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @libcub, it has been implemented in this build patch along with many other improvements: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by libcub** [comment]
I installed the patch, but the buttons didn't change.

**Comment by huyphams** [comment]
Thank @libcub for trying the build, here is it in mine setup, are you talking about the structure button or something else?
<img width="415" alt="a" src="https://user-images.githubusercontent.com/3654622/72440958-2f78aa00-3780-11ea-9301-190ab7d85fb7.PNG">
<img width="316" alt="b" src="https://user-images.githubusercontent.com/3654622/72440960-30a9d700-3780-11ea-9190-d427eb82e1ff.PNG">

**Comment by libcub** [comment]
Yes, it works in the new update!
