### ISSUE TITLE
Add GUI functionality for COMMENTs

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#167]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
112

3. The steps to reproduce this issue:
Display the structure of a table. There is no place to add a comment.

Add a comment to a column or table in an SQL Query tab, run it, and commit it. Go back to the table structure display. Click refresh. The comment does not display.

It does look like comments are displayed for indexes.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
It does display now, and we can also add a comment via GUI. Thanks

**Comment by libcub** [comment]
It's great to see column-level comments with the new release! Table-level comments are still not showing though. I hope you can add those in at some point.

**Comment by disabledman** [comment]
Does this column comment display feature also to the MS-SQL ? 
Because I can't find it out. (Windows Version)
