### ISSUE TITLE
After opening or saving a file, change the tab name to the file name

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#168]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
112

3. The steps to reproduce this issue:
After opening or saving a file, the tab name is "SQL Query".

Automatically change it to the file name.

Related to Mac issue [#1519](https://github.com/TablePlus/TablePlus/issues/1519)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by skwl** [comment]
I would like to see this also. It would be very helpful for the tab name to match the sql file name.

**Comment by KobaMaksym** [comment]
+1 regarding tab name to match the sql file name
