### ISSUE TITLE
Reconnect tab if it's disconnected

### ISSUE THREAD

**Issue by bladefist** [TablePlus/TablePlus-Windows#17]
Latest version.

If I close my laptop and come back later, all of my tabs are dead and I have to close them and re-connect to the database. There should be auto-reconnect or at least manual way to reconnect the tabs.

Thanks, you're doing a great job on this product!

**Comment by huyphams** [comment]
Thanks, I will add it in the next update 👍

**Comment by huyphams** [comment]
I have added the reconnect function, you can trigger it by pressing: control + shift + R.

**Comment by bladefist** [comment]
Verified! Thanks
