### ISSUE TITLE
Bug: Primary key index order incorrect

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#174]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
112

3. The steps to reproduce this issue:
CREATE TABLE test ( 
   a TEXT NOT NULL,
   b TEXT NOT NULL
);

Open the table in the Structure view. Enter:
b a
in the Primary box. Commit.
The index is created as:
a,b
and the Primary box change to:
a b

**Comment by huyphams** [comment]
Hi @libcub we've fixed this issue recently, you can try this patch: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
It also fixes the issue https://github.com/TablePlus/TablePlus-Windows/issues/173

**Comment by libcub** [comment]
Great--thanks!
