### ISSUE TITLE
Comma Separated Field Names

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#180]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
any

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
114

3. The steps to reproduce this issue:
I have brought this up a couple times. I use comma separated list of field names _**all the time**_. I originally asked for the "SQL" button to display the correct SQL command. If I have a hundred fields in my record and I select 3 of them with the "Columns" button, then filter the table with some criteria, then click the "SQL" button, it shows the query with the proper filters but _**not the proper fields**_. It just shows "SELECT *". That is _**not**_ the SQL query being displayed on the screen, so that is a **bug**, not an enhancement.

In order to get around this fault I would go into "Columns" select either "All Fields" and delete the fields I didn't want, or if just a few fields select them one by one (but anything more than a few and this is incredibly tedious), then copy the comma separated list from here to use in a custom SQL query or for a custom export.

Now you have gotten rid of the comma separated list in "Columns" and replaced it with these weird objects that can be dragged but then disappear when they are dropped.

Can I please get my list of fields back - you just don't realize how important that is in every day usage. I almost _**never**_ want to work with "SELECT *".

**Comment by huyphams** [comment]
Thanks @rwhirn , the current build has supported copy already, I just wanna make sure that you're aware of it, could you point me out why it does not work for you?
![2020-01-22 19 43 04](https://user-images.githubusercontent.com/3654622/72944536-8cabc700-3d4f-11ea-8258-98064ac0c338.gif)

**Comment by rwhirn** [comment]
ok, but obviously its not intuitive since I didn't realize it could be done and there was no way for me to know it had been changed. Its not intuitive to copy something that doesn't look like a comma separated list and expect it to past as a comma separated list.
