### ISSUE TITLE
Can't Add Record with NULL fields

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#181]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server 2014

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
114

3. The steps to reproduce this issue:
Possibly related to issues #160 and #164 
![image](https://user-images.githubusercontent.com/25158630/73032665-53ce2980-3e05-11ea-8a13-18ad1c00c0a1.png)
Add row by duplicating (Ctrl-d)
Change key
Attempt save (Ctrl-s)
In my case it won't save because while NULL is valid in these fields, "empty" attempts to set a relation to another table and that "empty" relation is invalid.

**Comment by libcub** [comment]
This is also happening for me, in PostgreSQL 12.1
