### ISSUE TITLE
Oracle Connection For TablePlus Windows

### ISSUE THREAD

**Issue by justonwater** [TablePlus/TablePlus-Windows#182]
It's possible to have the Oracle Connection for TablePlus Windows ?

**Comment by huyphams** [comment]
Duplicate of https://github.com/TablePlus/TablePlus-Windows/issues/193

**Comment by huyphams** [comment]
Hi, we are working on a different product which support Oracle now, it's beta if you have a chance, please try it:
http://boltsql.com/
