### ISSUE TITLE
Cannot connect mysql via SSH - An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by Mickeel** [TablePlus/TablePlus-Windows#183]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Mysql
Where to find the driver version?

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Tableplus build 114

3. The steps to reproduce this issue:
- add new mysql connection
- connect via SSH without SSH key or with SSH key
- Error 

System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at TablePlus.Source.Service.SSH.StartSocket() in C:\Users\maverick\Documents\tableplus-windows\TablePlus\TablePlus\Source\Service\SSH.cs:line 390

Noted: If the bug is related to data, please attach an example SQL data.

Solution I tried:
- disable Windows 10 Firewall and netsh int ip reset resetlog.txt
- I got no antivirus in the moment
- added tableplus to firewall exception for private and public connection

Is this a problem of my windows blocking it?

**Comment by huyphams** [comment]
It seems like Windows 10 forbid TablePlus from using socket, have you tried to run TablePlus under admin privilege?

**Comment by Mickeel** [comment]
Hi @hyuphams, I didnt.

But I just recently restarted my computer and it works.
I also tried turning back on firewall + restart.
for final one, I also removed tableplus from the firewall app exception and it still works good. Not sure what happened. But case closed.

Thanks a lot for the prompt response.

**Comment by Mickeel** [comment]
Hi @hyuphams,

Just noticed it only happen if we are using eclipse and use the ant-build. Somehow eclipse binded the port and prevent tableplus from using it. Closing eclipse clear this.

Hope it helps.

Thanks

**Comment by huyphams** [comment]
TablePlus uses a random available port (it will be changed every time the user create a tunnel) so it's impossible that they are using the same port.

**Comment by huyphams** [comment]
Hi, please try this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thanks
