### ISSUE TITLE
Add Version History/Changelog page for Windows version to TablePlus website

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#184]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 114

3. The steps to reproduce this issue:
Add Version History/Changelog page for Windows version to TablePlus website, similar to the one for the Mac version

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
it's here on the Windows page: https://tableplus.com/windows 
Win: https://tableplus.com/win/changelog
Mac: https://tableplus.com/osx/changelog
Linux: https://tableplus.com/linux/changelog
