### ISSUE TITLE
Column Sorting not working with NULL in LEFT JOIN

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#188]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.0.20

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
114

3. The steps to reproduce this issue:
Custom query in SQL Editor - a SELECT with 3 LEFT JOINs to other tables
Click on the column heading of a field in the 3rd/last JOINed table
NULL fields randomly scattered within results and other results missing
![image](https://user-images.githubusercontent.com/25158630/73977994-049df380-48f1-11ea-99f5-3d8d47784cea.png)

**Comment by rwhirn** [comment]
Using ORDER BY on this field produces correct results
![image](https://user-images.githubusercontent.com/25158630/73978186-74ac7980-48f1-11ea-9a49-3ecd4d5ae767.png)

**Comment by libcub** [comment]
@rwhirn Isn't A2-1 in the first image with id 209?

**Comment by rwhirn** [comment]
@libcub oh, yeah, you mean A2-10, it is, so they are just way out of order, which is what I thought in the first place.
