### ISSUE TITLE
Editing Data Fails for Cockroach driver

### ISSUE THREAD

**Issue by bladefist** [TablePlus/TablePlus-Windows#19]
I made a new table in cockroach, key and value, both text.

I go into the grid/spreadsheet editor view, and I tried to add a key and value, I get an insert error.  I then added them via sql query and tried to edit them in the grid, and I get a unique constraint error.

**Comment by huyphams** [comment]
Thanks @bladefist  let me check it.

**Comment by huyphams** [comment]
Do you have a step by step reproduce the bug @bladefist ? I have tried to create a text table key value, it works
![screen shot 2018-11-24 at 8 51 47 pm](https://user-images.githubusercontent.com/3654622/48969023-c8071480-f02a-11e8-925a-a77f40ba4d06.png)

**Comment by bladefist** [comment]
@huyphams So you can click +Row and type in a key and a value, ctrl+s and it saves?

**Comment by bladefist** [comment]
![image](https://user-images.githubusercontent.com/1520456/48969102-29919980-efbf-11e8-905e-28ead018dd68.png)

**Comment by huyphams** [comment]
Yup, after changing the value, ctrl + S and it saves. Can you check the generated statement by Ctrl + Shift + P?

**Comment by bladefist** [comment]
Ok, after closing the table and re-opening it's working.  The generated statement had two insert statements w/o any columns, any values.  Just like the error message I uploaded shows.  

I made a new table, and at the moment I cannot reproduce this.  Something happened before that got it messed up.  I'll provide more info if it happens again.

**Comment by huyphams** [comment]
Sure, I will double check all again. Thanks for the details.
