### ISSUE TITLE
TablePlus crashes when tabbing from column_default to foreign_key of a new column

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#190]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 114

3. The steps to reproduce this issue:
Open a table, click on Structure, then + Column. Enter column_name, data_type, is_nullable, and column_default, using tab to get from one field to the next. After entering a column_default value, tab again. This should move the cursor to the next item (foreign_key), but instead TablePlus crashes and exits. (Upon restarting TablePlus and reconnecting to the database, the partially specified column is absent.)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by libcub** [comment]
Unsure if related to #191.

**Comment by huyphams** [comment]
Hi @libcub please try this patch and see how's it going: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thank you!

**Comment by libcub** [comment]
Yes, this fixed the problem! Thanks for your speedy resolution!
