### ISSUE TITLE
Cannot connect to Oracle Database as it is not in the list for creating new connections!

### ISSUE THREAD

**Issue by bharnach** [TablePlus/TablePlus-Windows#193]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Do not know?
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 116
3. The steps to reproduce this issue:
Oracle does not appear in the Create New Connection list
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi, TablePlus Windows does not support Oracle, please see the full list here: https://tableplus.com/windows

**Comment by petrdsvoboda** [comment]
Is support for Oracle on the roadmap?

**Comment by belgacea** [comment]
Would love to buy this client for Oracle connections.
As it seems available for the [MacOS](https://github.com/TablePlus/TablePlus/issues/226) beta for, is it still coming for windows ?

**Comment by huyphams** [comment]
Hi, we are working on a different product which support Oracle now, it's beta if you have a chance, please try it:
http://boltsql.com
