### ISSUE TITLE
Horizontal scrolling with mouse is broken (v3.2.0)

### ISSUE THREAD

**Issue by dwyer14** [TablePlus/TablePlus-Windows#194]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
MySQL, MSSQL (doesn't seem driver-specific)

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
Build 116 / v3.2.0
Issue just started after installing update.

**3. The steps to reproduce this issue:**
- Load up a table with a decent number of columns (so it overflows).
- Scroll horizontally by click-dragging scrollbar. Should work fine.
- Scroll horizontally using mouse wheel—I'm on a MX Master 3. Crashes app.

**Comment by huyphams** [comment]
Thanks @dwyer14 let me check it.

**Comment by dwyer14** [comment]
No problem; will be curious to hear if you're able to reproduce that or not...seemed like a pretty weird edge-case.

**Comment by huyphams** [comment]
I will check it with my friend, he has an MX Master 3, hopefully, I can reproduce the issue 😁

**Comment by dwyer14** [comment]
Haha, perfect. 👌

**Comment by huyphams** [comment]
Hey @dwyer14 could you please install this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

**Comment by dwyer14** [comment]
Nope, still seems to be crashing on horizontal scroll.

**Comment by dwyer14** [comment]
Tried accessing some data again this afternoon, and I don't know that this is actually limited to horizontal scrolling. That definitely triggers it, but the app seems to also crash randomly, when it's just sitting there (ie, I'm not interacting with anything). I loaded up an MSSQL table and the app just randomly crashed ~1 minute later.

**Comment by huyphams** [comment]
is there any chance of getting a crash log? you can send it here or send it to nick@tableplus.com thank you!

**Comment by dwyer14** [comment]
Happy to do that, but I'm not getting a crash report. It just locks up and force closes after a few seconds. Are logs stored somewhere on the system, or is it just supposed to dump when it crashes?

**Comment by huyphams** [comment]
Ah sorry, I've an updated build for you" https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0 Please try this build and see how it goes.

**Comment by dwyer14** [comment]
Nope, still crashing on horizontal scroll.

**Comment by lucas-varela** [comment]
+1 on this, using MX Master 2S. Cannot test this right now, but this might actually be caused by the Logitech Options software.

**Comment by son11592** [comment]
I'm using MX Master 2S but everything worked fine. But I'm not using Logitech options, can you share it to me?

**Comment by lucas-varela** [comment]
Sure thing, just download it from their website: 

https://www.logitech.com/en-us/product/options

**Comment by dwyer14** [comment]
That's an excellent suggestion, guys. @huyphams - Sorry I didn't think of that to begin with! 
Updating Logitech Options seems to have fixed the issue on both MySQL and MSSQL. 👍

**Comment by rafael-franca** [comment]
@caseydwyer What's your version of Logitech Options? I have the same issue.

Logitech MX Master 3
Logitech Options: 8.10.154
TablePlus: 3.5.1 (124)
Windows 10 (2004) build 19041.264

**Comment by caseydwyer** [comment]
@rafael-franca W10 is up to date, and my current versions seem to match yours:
* TablePlus - 3.5.1 (build 124)
* Logitech Options - v8.10.154
Horizontal scroll seems to be working fine. Sorry about that, not sure what to tell you.

**Comment by rafael-franca** [comment]
Thanks, @caseydwyer. I'll trying to reinstall the app.

**Comment by rafael-franca** [comment]
In latest update (3.5.3 126) I don't see this bug.

**Comment by huyphams** [comment]
Hi guys, please try this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thanks!

**Comment by rafael-franca** [comment]
@huyphams Works great!

Thanks!
