### ISSUE TITLE
TablePlus crashes when opening Structure tab of Views

### ISSUE THREAD

**Issue by spruke** [TablePlus/TablePlus-Windows#196]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Postgres 11.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 116

3. The steps to reproduce this issue:

Open a View in Postgres. It loads okay in the data tab but crashes when Structure is selected so the view can be edited.

This has only begun happening to me since I upgraded to 116. It functioned okay on 112.

**Comment by huyphams** [comment]
Hi @spruke I'm sorry about the issue, could you please try this patch and see how it goes?
https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thank you!

**Comment by spruke** [comment]
@huyphams I do not have the rights to install an unsigned executable on the work computer I use TablePlus on :(

**Comment by huyphams** [comment]
Hi @spruke all TablePlus updates are signed, even the one on dropbox link.

**Comment by spruke** [comment]
It worked! Thank you so much!
