### ISSUE TITLE
Feature: search table

### ISSUE THREAD

**Issue by Salmondx** [TablePlus/TablePlus-Windows#2]
It will be cool if you add a search table function in the `Tables` section. For databases with lots of tables I think its a must-have feature.
E.g. when you are not focusing an input element and start typing, it automatically starts a table search (like in Sequel Pro).

Thanks!

**Comment by Tungtono** [comment]
It will be supported in the future releases.

**Comment by huyphams** [comment]
It's supported in build 6, thanks @Salmondx
