### ISSUE TITLE
Reloading Data Removes Search Filtering

### ISSUE THREAD

**Issue by jny986** [TablePlus/TablePlus-Windows#20]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MYSQL 5.7.23

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

version 1.0 build 28

3. The steps to reproduce this issue:

When reloading the data from the database (Ctrl + R) the data is refreshed but the filtering of the tables using the search is cleared with the search term still in the search input

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @jny986 I will check and fix it now.

**Comment by huyphams** [comment]
Hey @jny986 can you check it again on the newest build 40? seems it was fixed.

**Comment by huyphams** [comment]
Hi, we fixed it on the build 48. Thanks for reporting.
