### ISSUE TITLE
Right click not working in SQL editor

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#200]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 116

3. The steps to reproduce this issue:
Right click on text in an SQL Editor window. No context menu appears. So, for example, I can't save it as a favorite.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by son11592** [comment]
Hi @libcub, you can save the current queries as a new favorite by clicking on the right arrow of the execute button. (see attachment below).

![image](https://user-images.githubusercontent.com/4739616/76826175-5883ec80-684e-11ea-938c-05b41d90535b.png)
