### ISSUE TITLE
Typo in Preferences

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#201]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 116

3. The steps to reproduce this issue:
Open Preferences. Click on the Locations tab. In the text at the bottom there is a typo: "chagne"

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by son11592** [comment]
Hi @libcub, we will fix it and release in the next update. Thanks

**Comment by libcub** [comment]
Thanks!
