### ISSUE TITLE
Settings missing for Favorites (Queries)

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#202]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 116

3. The steps to reproduce this issue:
Open Queries in the item list sidebar. Open the dropdown menu at the bottom. The options are New File, New Folder, and Add Folder to Favorites. The documentation shows a Settings option for the Mac version; it does not appear in the Windows version.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by son11592** [comment]
Hi @libcub, this feature is supported in MacOS, neither in Windows. Currently, if you double click on a query, it will be inserted into current query editor tab or opened in a new one (if the activated tab is no t a query editor tab).

However, this feature will be added into the Windows version soon. 
Thanks.

**Comment by libcub** [comment]
I'm not talking about that. What I am referring to is the functionally described [here](https://docs.tableplus.com/query-editor/customize-query-editor).
