### ISSUE TITLE
Inconsistent terminology: "Queries" vs. "Favorites" vs. "Favorite"

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#203]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 116

3. The steps to reproduce this issue:
The middle section in the item list sidebar is called "Queries". Everywhere else (I think) it is called "Favorites", except in the dropdown menu in the SQL Query pane, where it is called "Favorite".

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by son11592** [comment]
Hi @libcub, previously, the `Queries` tab is called `Favorites`, some of texts are incorrect. We will update all of them in the next update. Thanks.
