### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#205]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 120

3. The steps to reproduce this issue:
I can't find the plugin in the menus. Is this feature not in the Windows version yet?

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by son11592** [comment]
Hi @libcub, this feature is not available on Windows version.

**Comment by huyphams** [comment]
it's not available but it will, the current beautify feature on Windows is a plugin.

**Comment by daugaard47** [comment]
> it's not available but it will, the current beautify feature on Windows is a plugin.

Is this a plugin that's available now? Do you have a link?

**Comment by libcub** [comment]
@daugaard47: I think Huy means that the current Beautify button feature in the Windows version was written as a plugin that is automatically installed with the main program. So it seems that plugin functionality in the Windows version is partially implemented.

**Comment by huyphams** [comment]
It's supported now.
