### ISSUE TITLE
File naming in backup database doesn't work

### ISSUE THREAD

**Issue by cmerijn** [TablePlus/TablePlus-Windows#206]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.1.44

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 120 on Windows 10

3. The steps to reproduce this issue:
When exporting a database with Menu > File > Backup, I can't set the file name and i cant use the patterns. It just says untitled after I click OK. When I select the database, it does change to the database name, but if I want to change the pattern it just says untitled again.

**Comment by son11592** [comment]
Hi @cmerijn, can you try to use `tab` or `enter` to complete each pattern string. It will show like this
![image](https://user-images.githubusercontent.com/4739616/77415431-1120d180-6df5-11ea-80ff-c7677546a333.png)

**Comment by cmerijn** [comment]
Ah that does work, thank you!
