### ISSUE TITLE
Can't use apostrophe in filter

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#207]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.17

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
120

3. The steps to reproduce this issue:
![image](https://user-images.githubusercontent.com/25158630/77705947-0ac65d00-6f8f-11ea-85f4-b74ce7382c8e.png)

**Comment by son11592** [comment]
Hi @rwhirn, thank you for your feedback. I'm working on this issue, I'll give you an update soon.
