### ISSUE TITLE
Support MongoDB

### ISSUE THREAD

**Issue by huyphams** [TablePlus/TablePlus-Windows#208]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MongoDB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 120

3. The steps to reproduce this issue:

- Support MongoDB

Noted: If the bug is related to data, please attach an example SQL data.

Import from https://github.com/TablePlus/TablePlus/issues/1807

**Comment by pydupont** [comment]
Sorry, I didn't realise that there was a separate repo for the windows version. 

Thanks :)

**Comment by armancodes** [comment]
MongoDB is not currently supported. It's so useful if it will be available on Windows.

**Comment by neilcamilleri** [comment]
Any updates on this? Will it be implemented sometime in the near future?

**Comment by suabahasa** [comment]
I hope tableplus can grow the supported database as navicat-premium.

**Comment by KugelbergDK** [comment]
Hey, just want to bump this. Mongodb on windows will be game changer for me. 
Any updates?

**Comment by iexa** [comment]
Any update on this?

**Comment by YemreGurses** [comment]
Any updates?

**Comment by 3to1null** [comment]
Really looking forward to MongoDB support on windows! Any updates on it?

**Comment by whoisYeshua** [comment]
Any updates?

**Comment by suabahasa** [comment]
TablePlus 4.2.6 - Build 176
Release date: 15 August 2021.

- Added MongoDB driver.
- Fixed issue on Windows 11.
- Other bug fixes and improvements.

**Comment by wxlg1117** [comment]
perfect...
