### ISSUE TITLE
Multi-table SQL export ignores custom filename

### ISSUE THREAD

**Issue by caseydwyer** [TablePlus/TablePlus-Windows#210]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**MySQL 5.7.16**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**Build 122**

3. The steps to reproduce this issue:

- Select one table, export as SQL -> works. ✅
- Select multiple tables, export as SQL -> says completed, but no file created. ❌

**Comment by son11592** [comment]
Hi @caseydwyer, I cannot reproduce this issue, it worked correctly with my latest build. Could you try to export again?

**Comment by caseydwyer** [comment]
Ahhh, I realize what was happening. I had `db-name.sql` on my desktop already. Was giving the export a custom name, but TablePlus isn't respecting the file name you enter—it just reverts back to full DB name. As a result, the `db-name.sql` file I had on my desktop was being overwritten. Confirmed this with MySQL and MSSQL.

**Still a bug**, but a little less critical, IMHO. Dunno if this helps, but the "Save as type:" dropdown—in the Save As dialog—is blank, and has no options available.

Thanks @son11592!

**Comment by son11592** [comment]
Hi @caseydwyer, thank you for your help. I'm working on it.

**Comment by huyphams** [comment]
It's fixed @caseydwyer please install this patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thank you!

**Comment by caseydwyer** [comment]
Yup, all is well. 👌 Thanks guys!
