### ISSUE TITLE
CSV Import fails when data contains single quotes

### ISSUE THREAD

**Issue by AndyMarshman** [TablePlus/TablePlus-Windows#212]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**Microsoft SQL Server**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**341 (122)**

3. The steps to reproduce this issue:
Try to import any CSV file that has been saved from MS Excel where there is a single quote within a cell. E.g. A surname column of O'Neil, or O'Leary. 
The import will fail with the following error:-
_**Incorrect syntax near 'Leary'.
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.**_

Regards

Andy

**Comment by son11592** [comment]
Thạn you, @AndyMarshman. I'm checking this issue.

**Comment by huyphams** [comment]
Please download this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please let us know if you're still seeing the issue.
