### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by clarkfactory** [TablePlus/TablePlus-Windows#213]
1. MriaDb 10.4.11

2. TablePlus 3.4.2

3. I export all tables data and structure.
   And delete all tables.
   I get an error when I import that sql file. 

![Screenshot_4](https://user-images.githubusercontent.com/64057292/79854074-dd40c800-8403-11ea-8ed7-e2816bfeae69.png)

**Comment by son11592** [comment]
Hi @clarkfactory, thank for you feedback. I will check this issue.

**Comment by clarkfactory** [comment]
Hi, @son11592, thank you so match.
I understood cause a little.
This error seems to be due to insert syntax.
It seems that a sql file like this is output if table is no data at export in TablePlus.
![Screenshot_5](https://user-images.githubusercontent.com/64057292/79891243-ae464880-843b-11ea-8ac0-6d4cdfa72099.png)

**Comment by son11592** [comment]
Hi @clarkfactory, this issue has been fixed. The next update will include it. Thank for your help.

**Comment by clarkfactory** [comment]
Hi @son11592, Thank you for fixed.
