### ISSUE TITLE
SSH Error - Invalid private key

### ISSUE THREAD

**Issue by marezelej** [TablePlus/TablePlus-Windows#216]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
I am using the Mysql connection.
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 122
3. The steps to reproduce this issue:
I generate my connection via SSH and select my private key. When I try to connect, I got the error on the title.
![image](https://user-images.githubusercontent.com/30838853/80159406-4873d100-85a1-11ea-964c-c17a4db9cf69.png)
I can connect over SSH and using Mysql too.
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by son11592** [comment]
Hi @marezelej, thank for your feedback. I will check this issue now.

**Comment by marezelej** [comment]
I solved it!!
I was connecting to a laravel vapor created database, by default the
jumpbox (used for ssh connection) says the user is "vapor", which worked
fine on mysql workbench.
However, on their documentation they use table plus in one example and use
the "ec2-user" username! Using that user it worked fine for me.
Thank you!
