### ISSUE TITLE
Filtering with IN on text-based values broken

### ISSUE THREAD

**Issue by caseydwyer** [TablePlus/TablePlus-Windows#218]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MSSQL/MySQL (happens to both)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 122

3. The steps to reproduce this issue:
* Apply an **IN** filter to a string-based column. 
* Search for 2+ terms, separated by columns.
* Note the SQL query joins the terms. See example below.

**Example:** Column `first_name`, filter using `IN`, value of `Tom,Jack`

Resulting SQL query:
```
SELECT * FROM `db`.`donations` WHERE `first_name` IN ('Tom,Jack')
```
Expected SQL query:
```
SELECT * FROM `db`.`donations` WHERE `first_name` IN ('Tom','Jack')
```

Very possible I'm just unaware of a delimiter on the IN filter...but this kind of feels like a bug? Tried adding my own array brackets, single and double quotes in a bunch of combinations. Nothing seemed to work.

**Comment by huyphams** [comment]
It was a bug, the IN filter should accept the syntax 'A', 'B' let us fix it.

**Comment by huyphams** [comment]
Hi @caseydwyer this patch should correct the issue: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0 Please let me know if you're still seeing it. Thanks

**Comment by caseydwyer** [comment]
Yup, all set! 👌 Thanks @huyphams!
