### ISSUE TITLE
Menu Cursor Bug

### ISSUE THREAD

**Issue by cpreston321** [TablePlus/TablePlus-Windows#219]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.27
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 122

3. The steps to reproduce this issue:
Click Menu go to any of the options in the dropdown. When you try to access the submenu it keeps disapearing. The only way I can access the sub menu if I move my cursor fast enough over the sub menu.

Noted: If the bug is related to data, please attach an example SQL data.
![cap](https://user-images.githubusercontent.com/6619884/80828733-c8a6c180-8bb3-11ea-8a7c-d5cb8ccffeff.jpg)

**Comment by son11592** [comment]
Hi @cpreston321, thank for your feedback. I will take a look on it now.

**Comment by cpreston321** [comment]
Seems to only be a bug when the sub menu is to the right on larger screens. When you minmize the application it works fine when it goes to the right.

**Comment by huyphams** [comment]
Hi @ZiiMs if you have a chance, please try this hot patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please let me know if you're still seeing the issue.
