### ISSUE TITLE
Updated data in sql select does not change on the screen

### ISSUE THREAD

**Issue by myfirmapp** [TablePlus/TablePlus-Windows#227]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Postgresql 9.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

124

3. The steps to reproduce this issue:

select data: select * from tableA
edit data in row: change data from A to B in one column
save change
the data is changed and saved but on the screen in the table the data does not change
you need to reload the request to see the change

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by son11592** [comment]
Hi @myfirmapp, thank for your feedback. I will check this soon.

**Comment by huyphams** [comment]
Hey @myfirmapp thank you for letting us know. we have fixed it on this patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

**Comment by myfirmapp** [comment]
This update solve the problem.
Thanks.
