### ISSUE TITLE
Search/replace does not working

### ISSUE THREAD

**Issue by chrisptree** [TablePlus/TablePlus-Windows#229]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10 (mysql)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.5.3 (128)

3. The steps to reproduce this issue:
In the SQL Editor, just press Ctrl+F and it does not show the search form.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Ops, sorry about the issue, please try this patch, it should fix the issue: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thanks!
