### ISSUE TITLE
Output of rows affected does not display correctly

### ISSUE THREAD

**Issue by chrisptree** [TablePlus/TablePlus-Windows#231]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.5.3 (128)
3. The steps to reproduce this issue:
Make any SQL statement that will produce a affected rows and you will see the text `nn rows affected` is displayed as we cannot see correctly the text.
![image](https://user-images.githubusercontent.com/8090476/83420013-f4f07080-a3f3-11ea-8acb-8b558bf68c4a.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
It has been fixed in this hot patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0 Please let me know if you're still seeing the issue @chrisptree thank you so much for letting me know.

**Comment by chrisptree** [comment]
It is now OK.

Thanks

Christian Poirier
Analyste de l'informatique
Service des technologies de l'information
Université TÉLUQ
1 800 665-4333 p. 5215
christian.poirier@teluq.ca<mailto:christian.poirier@teluq.ca>
teluq.ca<https://www.teluq.ca/>

Soyez un acteur important dans l'amélioration de nos services : exprimez-vous à qualite@teluq.ca<mailto:qualite@teluq.ca>.

De : Henry Pham <notifications@github.com>
Envoyé : 1 juin 2020 10:40
À : TablePlus/TablePlus-Windows <TablePlus-Windows@noreply.github.com>
Cc : Poirier, Christian <Christian.Poirier@teluq.ca>; Mention <mention@noreply.github.com>
Objet : Re: [TablePlus/TablePlus-Windows] Output of rows affected does not display correctly (#231)


It has been fixed in this hot patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0 Please let me know if you're still seeing the issue @chrisptree<https://github.com/chrisptree> thank you so much for letting me know.
