### ISSUE TITLE
Querie Folders not renamable after update

### ISSUE THREAD

**Issue by michaeljstack** [TablePlus/TablePlus-Windows#232]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
NA
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.5.5 (128) x64
3. The steps to reproduce this issue:
Right Click on a querie folder and try to rename the folder.
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by son11592** [comment]
Hi @michaeljstack, thank for your feedback. I will check it now.

**Comment by michaeljstack** [comment]
Thank you for the quick response. Another note after the update it renamed all folders to 'Drive C'

**Comment by son11592** [comment]
@michaeljstack, I found the root cause, the update will be sent to you soon.

**Comment by huyphams** [comment]
Hi @michaeljstack please try this hot patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please let us know if you're still seeing the issue. Thanks!

**Comment by michaeljstack** [comment]
That worked
