### ISSUE TITLE
Ability to copy cell value no longer exists when right clicking on a cell in the results.

### ISSUE THREAD

**Issue by michaeljstack** [TablePlus/TablePlus-Windows#233]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
NA
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.5.5 (128) x64
3. The steps to reproduce this issue:
Run a query, right click on a cell, Only copy is available, there used to be copy cell value.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @michaeljstack if you have a chance, try this patch https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please let me know if you're still seeing the issue.

**Comment by michaeljstack** [comment]
After installing the patch I still do not get the option to copy just the single cell value
![2020-06-03 16_21_11-Window](https://user-images.githubusercontent.com/45638413/83698450-4cd6d500-a5b6-11ea-9df1-a00d3d52a858.png)
