### ISSUE TITLE
Using horizontal mouse scroll crashes the application

### ISSUE THREAD

**Issue by Tazaf** [TablePlus/TablePlus-Windows#235]
As the title says, every time I'm attempting an **horizontal scroll** on a TablePlus table window using my mouse scroll wheel (_see below_), the application displays a busy cursor icon, freezes, then completely crashes after a few seconds.

The mouse I'm using is a [Logitech M720](https://www.logitech.com/fr-ch/product/m720-triathlon). It has a type of scroll wheel that you can skew right or left until earing a "click!" sound to perform horizontal scroll.

The problem **does not** occur when performing an horizontal scroll using the Surface Book **trackpad**. Unfortunately, I don't have any mouse to try and test if it's related to the Logitech model specifically or mouses in general.

Is there any kind of log that I could give you guys for you to have a little bit more information?

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
The issue is not related to a particular driver.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 128

3. The steps to reproduce this issue:
Well... that's kind of difficult to give you precise step... But here's what I'm doing, which triggers the bug every time:

   1. Open TablePlus
   2. Connect to any database
   3. Click on any table in the database to display its data
   4. Attempt an horizontal scroll with the mouse wheel
   5. Wait for the crash to happen
   6. Witness the crash

**Comment by huyphams** [comment]
Hi @Tazaf could you please try this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thank you!
