### ISSUE TITLE
Feature Request: Allow Database Server sort order

### ISSUE THREAD

**Issue by jonopeo** [TablePlus/TablePlus-Windows#238]
Currently, there is no way to re-order the servers in TablePlus. Or at least none that myself or my colleagues have found. As we work with Hundreds of servers, scrolling through a list is not always an efficient way to find a particular server (Especially when these will be added in a random order). It would be nice to have an automatic sort by Alphabetical or the option to drag servers in a more particular order (Similar to how JetBrains products do it). This would be a really nice Quality of Life improvement.

**Comment by huyphams** [comment]
Hi @jonopeo you can sort database order by dragging them. We're adding an ability to sort it by name, tag and type.

**Comment by jonopeo** [comment]
@huyphams Ah my apologies, the sort methods will be a really nice addition 👍
