### ISSUE TITLE
Export bug

### ISSUE THREAD

**Issue by clarkfactory** [TablePlus/TablePlus-Windows#239]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MriaDb 10.4.11

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
TablePlus 3.6.1 (130)

3. The steps to reproduce this issue:
I export all tables from export menu of left pane.
And when this SQL file import it fails.
The cause is duplication of CREATE statement and INSERT statement. 
Please check it.

![Screenshot_14](https://user-images.githubusercontent.com/64057292/84969068-e4116000-b152-11ea-952a-b587affe7127.png)
![Screenshot_15](https://user-images.githubusercontent.com/64057292/84969154-11f6a480-b153-11ea-8ef4-e0a116817187.png)
![Screenshot_12](https://user-images.githubusercontent.com/64057292/84968634-f6d76500-b151-11ea-83c4-cfa3122b6aea.png)

**Comment by huyphams** [comment]
Hi @clarkfactory thank you for the feedback. If you have a chance, please install this patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
if you're still seeing the issue, please let us know. Thanks again.

**Comment by itz-minomo** [comment]
Hi @huyphams
I put a patch and this bug has been fixed.
thank you very match.

**Comment by clarkfactory** [comment]
Hi @huyphams
I put a patch and this bug has been fixed.
thank you very match.
