### ISSUE TITLE
EXPORT CSV has MySQL comments in it

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#244]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.17

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
130

3. The steps to reproduce this issue:
right click on table
select  Export
on CSV tab check "Convert NULL to EMPTY"
check "Put field names in the first row"
Delimiter ,
Quote "
Line break \r\n
Decimal .
Click "Export..."
--
Result:
"RTYPE","CCODE","TPIDC","FILL7"
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */; 

"H","G",173921702573,""

**Comment by son11592** [comment]
Hi @rwhirn, thank for your report. I will check it now.

**Comment by huyphams** [comment]
Hi @rwhirn if you have a chance, please try this hotpatch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thank you so much!

**Comment by rwhirn** [comment]
All good! Thanks.
