### ISSUE TITLE
Dragging maximized window

### ISSUE THREAD

**Issue by Toadie1** [TablePlus/TablePlus-Windows#247]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Postgres 10.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 130

3. The steps to reproduce this issue:
Every Windows application when its maximized can be dragged by titlebar and moved to another position/display.
TablePlus didn't. 
When I want to drag it, I have to double-click on window title to switch from maximized to window view and then drag it somewhere. Its annoying.

**Comment by son11592** [comment]
Hi @Toadie1, we found the problem. The next update will contain this feature. Thank for your support.

**Comment by huyphams** [comment]
Thanks @Toadie1 please try this path: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0 it should fix the issue, thank you!
