### ISSUE TITLE
Bug of focus

### ISSUE THREAD

**Issue by clarkfactory** [TablePlus/TablePlus-Windows#249]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MriaDb 10.4.11

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
TablePlus 3.6.2

3. The steps to reproduce this issue:
For example, Import a SQL file and OK button clicked.
Then the focus goes out of TablePlus.
So I need to click TablePlus's icon one more.
Please confirm.

![Screenshot_17](https://user-images.githubusercontent.com/64057292/86552458-0c86c000-bf83-11ea-84a5-76e63a63ae8c.png)

**Comment by son11592** [comment]
Thank @clarkfactory for your feedback. I found the problem, the next update will contain this fixed.

**Comment by huyphams** [comment]
Hi @clarkfactory please apply this patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0 it should fix your issue! thank you!

**Comment by huyphams** [comment]
Also this issue: https://github.com/TablePlus/TablePlus-Windows/issues/247
