### ISSUE TITLE
many rows slow down Tableplus

### ISSUE THREAD

**Issue by jagDanJu** [TablePlus/TablePlus-Windows#25]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.5
Windows 10 + Windows Server 2012 R2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 42

3. The steps to reproduce this issue:
If I copy many lines into the input box for the statement, then the performance suffers.
Every click is insanely slow. It slows down after only a few hundred lines.

Data:
open Excel (or something else) and generate 3000 rows, then copy and paste the content to the input box for the sql statement

**Comment by huyphams** [comment]
Thanks @jagDanJu, we're improving it.

**Comment by huyphams** [comment]
Hey @jagDanJu if you have a chance, please check the newest build 86 and let me know if you're still seeing it.
Thanks

**Comment by jagDanJu** [comment]
Hey @huyphams 
I tested it with 10,000 lines and its very fast as expected.
I would say it fits now.
