### ISSUE TITLE
Forced TLS V1.1 while connecting to digitalocean DB

### ISSUE THREAD

**Issue by Sekator500v2** [TablePlus/TablePlus-Windows#253]
1. Driver is: MySQL
2. Build is: 132
3. You just need to set SSL mode to REQUIRED and try to connect to any DB hosted on digitalocean

Then you will receive an error "Invalid SSL" without any explanation. I've tried to connect using mysql shell and everything is fine SSL working OK.

Then I've captured all traffic using WireShark and I see that your program trying to connect using deprecated TLS v1.1 and ofcourse server rejected connection.

So is there any chance to set desired TLS version?

P.S. Seems like Mac version doesn't have this problem. Cuz my friend successfully connected to the same base.

**Comment by huyphams** [comment]
Tablelus Windows uses Open SSL 1.0.2o so it should support TLS 1.2, let me check if there is a way to use the latest TLS. thanks @Sekator500v2

**Comment by Sekator500v2** [comment]
Thanks a lot. When you have some beta or nightly build just let me know. I will check it very quickly.

**Comment by huyphams** [comment]
Hi @Sekator500v2 if you have a chance, please try this patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

**Comment by Sekator500v2** [comment]
Hi, thanks but didn't work. See screenshot, same result.
![Annotation-2020-07-10-131420](https://user-images.githubusercontent.com/24682968/87144240-19bbeb80-c2b0-11ea-8127-74836f265f23.png)

**Comment by Sekator500v2** [comment]
I went through the code and I see that libmysql.dll has only TLS V1 & V1.1. It is really hard to disassemble and maybe I’m wrong. But is there any chance you can update this lib? Also, version is 5.7.24

**Comment by huyphams** [comment]
I can confirm that the current MySQL lib which was distributed by Oracle only supports v1 and v1.1 and they said that if we want to support v1.2 we must build ourselves compile MySQL from the source.
I will try to compile the source and get back to you soon. Thanks!

**Comment by huyphams** [comment]
<img width="925" alt="Screen Shot 2020-07-11 at 3 04 15 PM" src="https://user-images.githubusercontent.com/3654622/87219706-d16ffc80-c387-11ea-8eee-c1cbe553472c.png">

**Comment by huyphams** [comment]
Hi @Sekator500v2 please install this hotpatch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0 and then change the SSL mode to PREFERRED TablePlus now supports TLS 1.2, please let me know if you're still seeing the issue.

**Comment by Sekator500v2** [comment]
Yep, it’s working now! And according to WireShark is  TLS v1.2
Thanks a lot!
