### ISSUE TITLE
Copied column name from data view missing a character

### ISSUE THREAD

**Issue by ManelyDave** [TablePlus/TablePlus-Windows#255]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Mysql 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

132

3. The steps to reproduce this issue:

In a table data view with a column named Accepted_Terms_Date__c (note two underscores before the c), right column name and choose 'Copy Name'. The copied text will be Accepted_Terms_Date_c (with only one underscore). The column header is displayed properly, only the copied text is incorrect.

**Comment by huyphams** [comment]
Hi @ManelyDave thank you for the feedback. If you have a chance, please install this patch, it should sort out the issue. https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
