### ISSUE TITLE
Connection to local SQL Server instance

### ISSUE THREAD

**Issue by malsama** [TablePlus/TablePlus-Windows#26]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQL Server

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Latest

3. The steps to reproduce this issue:

Has anyone managed to connect to a local MSSQL instance (so not a remote SQL Server)? If so, please share your settings, because I still can't.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @malsama here is mine:
<img width="562" alt="screen shot 2019-01-09 at 2 58 10 pm" src="https://user-images.githubusercontent.com/3654622/50884984-03b13e80-141f-11e9-941d-bc6dd6f40bd7.png">

**Comment by malsama** [comment]
<img width="416" alt="screenshot 2019-01-09 at 10 30 19" src="https://user-images.githubusercontent.com/44016531/50890201-0a798a80-13fa-11e9-9416-cffcfd06065f.png">

I've tested with:
- 32/64 bits version
- SQL Server 2014 64 bits with "Allow remote connections" on.
- localhost, 127.0.0.1 and computername; all tested with and without added sql instance name. Eg. localhost and localhost\SQLEXPRESS.
- db user as authentication
- port 1433

**Comment by huyphams** [comment]
Thanks @malsama we will double check it, perhaps there is something wrong in our connection string.

**Comment by huyphams** [comment]
Hey @malsama could you try to double the splash?
for an example: the host would be: localhost\\SQLEXPRESS
Thank you so much

**Comment by malsama** [comment]
I've tried that, but got the same error.

FYI, I personally use this connection string in my ASP app:

<add name="DefaultConnection" providerName="System.Data.SqlClient" connectionString="Data Source=mycomputername\SQLEXPRESS;Initial Catalog=mydbname;User ID=myusername;Password=mypassword;MultipleActiveResultSets=True" />

I don't include the port number.

NB: Could you make the fields wider? Especially the host field is too small to contain a value like in this example.

**Comment by huyphams** [comment]
I'm using this connection string:  string connetionString = $"Data Source={p.Host},{p.Port};Initial Catalog={p.Db};User ID={p.User};Password={p.Pass};";
I will try to remove the port params if it's default port 1433.

**Comment by malsama** [comment]
I just tested it in my ASP app including the port number and then I get the same error there. After removing it the connection worked. So indeed removing the port addition, when it's the standard port, might work.

**Comment by huyphams** [comment]
Thank you so much @malsama , I have no idea why Microsoft doesn't allow user set port=1433 but it will work if the port is customized but interesting 👍

**Comment by huyphams** [comment]
I've removed the port in this build: https://www.dropbox.com/s/ealt5w189kecr2q/TablePlus_x64.zip?dl=0
Could you test it and let me know the result @malsama?

**Comment by malsama** [comment]
I've tested it by leave the port field empty, and now I get a different error:

<img width="414" alt="screenshot 2019-01-09 at 11 15 04" src="https://user-images.githubusercontent.com/44016531/50892926-f3d63200-13ff-11e9-835a-af729cfef808.png">

**Comment by huyphams** [comment]
No, please enter 1433. I will handle empty later.

**Comment by malsama** [comment]
Ok, that's working now. Nice.

**Comment by huyphams** [comment]
It's released on the build 44. Thanks.
