### ISSUE TITLE
Duplicate row (and copy & paste) not copying primary key columns

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#261]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
132

3. The steps to reproduce this issue:
Display a table in data view
Select a row.
Try to duplicate or copy+paste that row.
Only non-primary key fields copy. Primary key fields are empty.

I would guess you do this because we don't want duplicate primary keys. However, I have many rows which are very similar, including in their primary key fields, and including those fields in the duplicate/copy+paste would mean much faster data entry for me.

Perhaps make this a setting?

**Comment by huyphams** [comment]
We can easily do it with the macOS version copy/paste but it seems it does not work on Windows, we will fix this. Copy/paste should keep all the data.

**Comment by son11592** [comment]
Hi @libcub, this feature has been added into Windows version. The update will be sent to you soon. Thank you for your feedback.

**Comment by huyphams** [comment]
Copy/paste now will keep the primary fields.

**Comment by libcub** [comment]
Great--thanks!
