### ISSUE TITLE
No Triggers button

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#263]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
132

3. The steps to reproduce this issue:
Display a table's structure view. There is no Triggers button, like there is in the Mac version.

**Comment by libcub** [comment]
Is there currently another way to display triggers in the interface?

**Comment by son11592** [comment]
Hi @libcub, we are working on this feature. It will be released soon. Thank you.

**Comment by huyphams** [comment]
It's released now, thanks
