### ISSUE TITLE
random column name doesn't show

### ISSUE THREAD

**Issue by MegaraSoftware** [TablePlus/TablePlus-Windows#264]
Maria DB 10.1.25
Table Plus 3.7.2

random column name doesn't show

![Anmerkung 2020-07-22 184059](https://user-images.githubusercontent.com/32955987/88203985-ed5a8480-cc4a-11ea-9829-27921b42ea8f.jpg)

**Comment by huyphams** [comment]
Hi @MegaraSoftware I'm sorry about the issue, could you please try this patch and see how it goes? https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

**Comment by MegaraSoftware** [comment]
Thx, this version fix this problem
