### ISSUE TITLE
Crashes as soon as I drag the client

### ISSUE THREAD

**Issue by Limess** [TablePlus/TablePlus-Windows#265]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Redshift? Doesn't seem to be relevant here though

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

136

3. The steps to reproduce this issue:

Drag the window after opening, the window crashes. It doesn't seem to matter what screen I'm on.

I'm not sure what additional info I can provider here. Can I get log files from anywhere? This is my first time trying the client on Windows and I'm immediately seeing this issues.

**Comment by huyphams** [comment]
Hi @Limess are you using a Logitech mouse? Is it crash when you drag the window with the trackpad?

**Comment by Limess** [comment]
yes, I'm using a Logitech G Pro Wireless mouse.

**Comment by huyphams** [comment]
Hi @Limess could you please try this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thanks!

**Comment by Limess** [comment]
Tried this, seems to fix it in all instances 🎉

**Comment by huyphams** [comment]
Thanks!
