### ISSUE TITLE
Cannot Connect with SSH

### ISSUE THREAD

**Issue by MattGrundy** [TablePlus/TablePlus-Windows#267]
1. MySQL but happens with all of the ones I've tried

2. 136

3. Create a connection using SSH with a keyfile (may be for password too) and then there's an alert:
```
System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at TablePlus.Source.Service.SSH.StartSocket() in C:\Users\huy\Documents\tableplus-windows\TablePlus\TablePlus\Source\Service\SSH.cs:line 393
```

Installed on Windows 10 version 2004, openSSH is enabled on my machine too

**Comment by dnl-jst** [comment]
Got the same problem.

**Comment by hoonzis** [comment]
I am not sure whether this is linked, but this happened to me after installing Git on windows and choosing openSSH as the default SSH library that git shoudl be used.
I have removed git, restarted the PC and it all works. Installed git again with the Windows Cryptography library as ssh implementation and seems to be working so far.

**Comment by sjardim** [comment]
Had the same problem today, I suspect it was caused by an upgrade to GitHub desktop. I reinstalled TablePlus and tried again but no luck, only after I restarted the machine (Win 10) it worked again.

**Comment by huyphams** [comment]
Hi guys, please try this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

Thanks

**Comment by saborrie** [comment]
@huyphams I have this issue but I'm not installing anything onto my computer from dropbox - is this patch available in TablePlus via an official update?

**Comment by saborrie** [comment]
from #418
> La solución fue ejecutar estos comandos en el PowerShell net stop hns net start hns
this was the fix

```
~ $ net stop hns
The Host Network Service service is stopping.
The Host Network Service service was stopped successfully.

~ $ net start hns
The Host Network Service service is starting.
The Host Network Service service was started successfully.
```
