### ISSUE TITLE
Multiple Table Export

### ISSUE THREAD

**Issue by jny986** [TablePlus/TablePlus-Windows#27]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
     Mysql 5.7.6
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
    Build 46
3. The steps to reproduce this issue:
    Want to be able to export selected tables from a database to a single file

Thanks for all the great work that you are doing

**Comment by huyphams** [comment]
Thanks @jny986 sure, we will support this feature on the next release 31-Jan-2019.

**Comment by jny986** [comment]
Great Thanks for all your hard work!
