### ISSUE TITLE
Saving Diagram is not working properly.

### ISSUE THREAD

**Issue by iyashpal** [TablePlus/TablePlus-Windows#273]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
: Maria DB 10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
: 138

3. The steps to reproduce this issue:
: I have generated a diagram by selecting 5 tables. In diagram generator window it looks like this:
![image](https://user-images.githubusercontent.com/19922707/90784214-a9789f00-e31e-11ea-9d4d-cae08c16f8ae.png)

Which looks great. But after saving the diagram to PNG or SVG it messes up. I have attached two files please see.

[untitled-diagram.zip](https://github.com/TablePlus/TablePlus-Windows/files/5103702/untitled-diagram.zip)

**Comment by dvkndn** [comment]
Thank you @iyashpal :D I confirm this is our styling error (when exporting to image, the data type column some how lost its styles).

I'll look into it. Let me update here when it's fixed :D

**Comment by iyashpal** [comment]
Sure, Thanks

**Comment by dvkndn** [comment]
Hi @iyashpal just want to let you know that the issue is fixed thank to your feedback. The fix will be in our upcoming update for the plugin

**Comment by dvkndn** [comment]
@iyashpal we've just updated the plugin :D Please update it (2.7) in the Plugin Manager (Ctrl + L)

**Comment by iyashpal** [comment]
@dvkndn now it's working as expected.

Thank you
