### ISSUE TITLE
Triggers not visible and trigger functions can't be opened

### ISSUE THREAD

**Issue by jaanoras** [TablePlus/TablePlus-Windows#274]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 10.11

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 138

I'm using windows 10 and I cant see table-s triggers nor can I open trigger related functions, they just wont open. 
I have purchased licence and tried to update. Is this normal on Windows?

**Comment by son11592** [comment]
Hi @jaanoras, thank you for your feedback. We are planning for this feature and it'll be available on Windows version soon.

**Comment by jaanoras** [comment]
There has been almost 4 months, multiple updates, still no triggers. Any ideas when will it happen?

**Comment by huyphams** [comment]
It is released now, thanks
