### ISSUE TITLE
Save Layout Settings

### ISSUE THREAD

**Issue by jny986** [TablePlus/TablePlus-Windows#28]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    MYSQL 5.7.24
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
    46
3. The steps to reproduce this issue:
    Have the layout of the program save so that we do not need to re-setup each time that we open the program

**Comment by huyphams** [comment]
TablePlus now remember its layout (Windows position, maximum, left, right, query panes) etc.. let me know if you're still seeing the issue.
