### ISSUE TITLE
Installed Diagram Generator plugin not showing up

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#282]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 138

3. The steps to reproduce this issue:
I installed the Diagram Generator plugin, but it is not showing. Where should I it?

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by dvkndn** [comment]
Hi @libcub when you right click on a table in your sidebar, do you see the menu option "Generate Diagram"?

**Comment by son11592** [comment]
Hi @libcub, you can use it when right click on any tables.
![image](https://user-images.githubusercontent.com/4739616/91537930-40f27900-e941-11ea-9cc7-aff6038adccf.png)

**Comment by libcub** [comment]
Oh, yes, I see it there--thanks!
