### ISSUE TITLE
Missing Postgres schemas in Open anything dialog

### ISSUE THREAD

**Issue by Toadie1** [TablePlus/TablePlus-Windows#287]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgresSQL 11.1
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 138
3. The steps to reproduce this issue:
The schema name is missing in dialog. Pictures should be self descriptive...
![Win](https://user-images.githubusercontent.com/22539609/92234397-422c2480-eeb2-11ea-8750-1efe1fb81207.png)
![Mac](https://user-images.githubusercontent.com/22539609/92234400-42c4bb00-eeb2-11ea-8895-489947cd381e.jpg)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @Toadie1 please try this hot patch it would support that feature: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
