### ISSUE TITLE
Go To Last Record

### ISSUE THREAD

**Issue by jny986** [TablePlus/TablePlus-Windows#29]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    MYSQL 5.7.24
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
   46
3. The steps to reproduce this issue:
   Have a button to go the the last row/record

**Comment by huyphams** [comment]
I see that we can use control + Up/Down to move up/down the table. Have you tried it?
Sorry for the late response because I was busy for the update 48 (just release it today).

**Comment by jny986** [comment]
Hi Huy

There is the next and past row but if I want to get to last of 500000
records it takes a long time.

**Comment by huyphams** [comment]
Hi @jny986 we released build 50 and supported go to page offset. So I will close this issue, feel free to reopen it if you still have any issue with paging.

**Comment by oraneedwards** [comment]
Hi @jny986 

If I double clicked a table to open the records - to get to the last page of a table I have to open the filter then type in the specific offset value. In a table that has millions of records, i'm slower than I want to be. Either:

1. I have to get the specific record count (which is usually estimated in table plus) then use it as offset.
2. I have to list all records then go to end of page
3. I have to write a select *  to order by id descending

Here how another tools does it:

<img width="215" alt="image" src="https://github.com/TablePlus/TablePlus-Windows/assets/3387272/5114a602-339e-4f50-9a17-4bd1296a6ade">

A single button to navigate to the end.


PS - I love TablePlus

**Comment by huyphams** [comment]
Hi @oraneedwards is there any reason why you don't want to click the header column (such as ID or timestamp) to sort DESC?

**Comment by oraneedwards** [comment]
@huyphams You're right. The first time I tried it took a while to buffer, but that approach is working perfectly fine now.

Thanks for the fast response!
