### ISSUE TITLE
BUG: First database selection not working

### ISSUE THREAD

**Issue by woochoo** [TablePlus/TablePlus-Windows#295]
1. Which driver are you using and version of it : 
        - MariaDB 10.1.x (multiple versions of 10.1.x

2. Which TablePlus build number are you using :
        - 140
        - Several prier versions too. Been using Table Plus for close to 2 months.
3. The steps to reproduce this issue:

**Bug Details:**
Saving a default database name in the connection settings opens that database, on successful connection, just fine. If I start a connection with no default database specified, and then use the database viewer to select a database, I see a problem.

The first database I select fails to load anything into the side bar, nothing in the UI changes at all. Re-selecting it again produces the same result. When I select a different database from the database viewer both the first and newly selected databases suddenly show on the left. The originally selected database tab, that would not show before, is unusable though. No tables appear, no functions, nothing. I then must right click to remove, then re-add from the database viewer to use.

**Steps to Reproduce:**

1. Create connection with no default DB
2. Connect to it
3. Open Database list
4. Select database (nothing shows in the left panel)
6. Select same database again (it still won't appear)
7. Select a different database from the list (both will appear)
8. Select the tab of the first database you selected (tables and functions do not show)

**Temporary Workaround:**
Always connect to an undesired DB first, then select the desired DB second. Optionally, right click the undesired, and unusable, DB tab from the left sidebar and close.

**Screenshots:**

![image](https://user-images.githubusercontent.com/15110093/92950172-dd2c7d80-f421-11ea-99dd-a37f2502e1c6.png)

![image](https://user-images.githubusercontent.com/15110093/92949963-8b83f300-f421-11ea-84e7-a5cb3ce5df91.png)

**Comment by woochoo** [comment]
Can somebody please respond to this? This issue is the main reason I don't use TablePlus as my primary and I paid for a license.

**Comment by huyphams** [comment]
Have you tried our latest release 146 @woochoo? thanks

**Comment by huyphams** [comment]
Please let us know if you're still seeing the issue, thanks!

**Comment by woochoo** [comment]
Hi @huyphams ,

This issue has not been fixed. I have now tested with MySQL 5.7 and MariaDB 10.1, 10.2, 10.3 . I have a screen recording of it in action but it won't allow me to upload. I can email you if you want.

.

**Comment by huyphams** [comment]
Yes please, my email is nick@tableplus.com

**Comment by huyphams** [comment]
I think the link wasn't updated at the time you downloaded the patch, please try with this link: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
I'm sorry.

**Comment by woochoo** [comment]
This fixed it for me. Thank you!
