### ISSUE TITLE
BUG: Unable to set multiple foreign keys at a time

### ISSUE THREAD

**Issue by woochoo** [TablePlus/TablePlus-Windows#296]
1. Which driver are you using and version of it : 
        - MariaDB 10.1.x (multiple versions of 10.1.x

2. Which TablePlus build number are you using :
        - 140
        - Several prier versions too. Been using Table Plus for close to 2 months.

3. The steps to reproduce this issue:

**Bug Details:**
After setting a foreign key inside a table, before saving, if I attempt to add a second foreign key the UI does appear to allow this, however it does not work. The second key will not appear as a change in the UI and the first key added will be updated with the parameters set for the second key. 

Attempting to resolve this by updating the overwritten key, and saving just the 1 key first, without discarding changes completely, produces a broken SQL query where the reference columns are missing.

**Steps to reproduce:**
1.	Add foreign key to a column (do not promote changes yet)
2.	In the same table, but on a new column, create a second foreign key (it will overwrite the first)
3.	Fix the first key again and promote changes (reference columns missing from table)

**Temporary Workaround:**
Set foreign keys 1 at a time, saving after each one. If you accidently add a second before saving the first, then perform a full refresh (CTRL+SHIFT+R), when asked to discard changes, say yes, then start over.

**Adding first key:**
![image](https://user-images.githubusercontent.com/15110093/92950985-406adf80-f423-11ea-9f13-16ef18ade89c.png)

**Adding second key:**
![image](https://user-images.githubusercontent.com/15110093/92951074-67c1ac80-f423-11ea-8886-61501bc87f9f.png)

**Result:**
![image](https://user-images.githubusercontent.com/15110093/92951164-90e23d00-f423-11ea-94e1-8ecfb9e6988b.png)

**Broken Query That Requires Full Refresh (with discard changes) to fix:**
![image](https://user-images.githubusercontent.com/15110093/92951377-de5eaa00-f423-11ea-815b-88d502bba4d4.png)

**Comment by woochoo** [comment]
Is there no update on this?

**Comment by huyphams** [comment]
I think it's also resolved on our latest release 146.

**Comment by huyphams** [comment]
Please let us know if you're still seeing the issue.
