### ISSUE TITLE
Windows version does not show the structure of a stored procedure

### ISSUE THREAD

**Issue by evok01** [TablePlus/TablePlus-Windows#297]
1. MS SQL Server 2017

2. build 140

3. Any stored procedure that you open, then click `Structure`, instead of the definition of the stored proc, it creates a CREATE TABLE script.
The macOS version does not exhibit this behavior.

**Comment by evok01** [comment]
Just in case, I went ahead and attempted a complete uninstall, then reinstall - same issue.

**Comment by son11592** [comment]
Hi @evok01, I could not reproduce with those steps. Please give me some photos of this issue. It may help us find out the problem Thank you.

**Comment by evok01** [comment]
I had forgotten about following up with this but just ran into it again earlier, so this time I recorded a video of what I'm seeing.

![recording](https://user-images.githubusercontent.com/59443998/101659640-4c5f4100-3a14-11eb-83d4-78249e1db6a2.gif)

**Comment by evok01** [comment]
My test was using SQL Server 2019, but I get this same behavior with any version of SQL Server. I also have updated to the latest version of TablePlus - 3.12.0 (150)

**Comment by huyphams** [comment]
Hi @evok01 please install this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

**Comment by evok01** [comment]
@huyphams That did it. Checked both views and stored procedures, and they show the definition. Thank you 👍
