### ISSUE TITLE
Key Bindings

### ISSUE THREAD

**Issue by jny986** [TablePlus/TablePlus-Windows#30]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    MYSQL 5.7.24
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
    46
3. The steps to reproduce this issue:
    Including more keybindings and a list of keybindings for windows.
   eg keybinding for inserting null, cmd + p equivalent

**Comment by eberkund** [comment]
Duplicate of #11

**Comment by huyphams** [comment]
It's all supported now. Thanks!
