### ISSUE TITLE
Bug in escaping of SQL queries

### ISSUE THREAD

**Issue by rohanc** [TablePlus/TablePlus-Windows#300]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 9.6.8.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.9.1 (140)

3. The steps to reproduce this issue:

Try to execute this query from within the TablePlus SQL query view. Don't pay too much attention to what it does. This bug report is about a suspected bug in how TablePlus escapes this before sending it to the server.
```
CREATE OR REPLACE FUNCTION public.ss_medical333()
  RETURNS TABLE(sortcol text) AS
$BODY$
DECLARE cmd TEXT;
   piece text;
BEGIN
FOREACH piece IN ARRAY colnames
LOOP
END LOOP;
cmd=$$
  $$;
END
$BODY$
LANGUAGE plpgsql STABLE;
```

The following error message is generated:

Query 2: ERROR:  unterminated dollar-quoted string at or near "$BODY$
```
LANGUAGE plpgsql STABLE;
  
  
"
LINE 3: $BODY$
        ^
```

No such error is generated if I paste this into the command-line psql tool, which simply responds with:
`CREATE FUNCTION`

It also works when I submit it using pgAdmin3, so I think the problem is in TablePlus and not a syntax error in the query itself.

Do you know what's going on here?

**Comment by huyphams** [comment]
Hi @rohanc please try this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thank you!

**Comment by rohanc** [comment]
Hmm, I couldn't replicate on version 3.10.0 (142). Was that patch already pushed to production?

**Comment by huyphams** [comment]
No, this patch is a new one, it's 3.10.1
