### ISSUE TITLE
[Bug] Cannot set default value for bit type

### ISSUE THREAD

**Issue by mtaki14** [TablePlus/TablePlus-Windows#301]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

SQL Server 12.0.2000.8 (Express)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

140 (windows)

3. The steps to reproduce this issue:

I have a bit type column with default value set to null. I am trying to change it to 0 (False) and the change doesn't go through. When I commit the change either through mouse click or through the keyboard shortcut, nothing happens.

The Preview SQL window shows empty.

**Comment by son11592** [comment]
Hi @mtaki14, I found that issue and fixed it. The update will be sent to you soon. Thank you for supporting us.
