### ISSUE TITLE
SSH invalid privatekey windows

### ISSUE THREAD

**Issue by huyphams** [TablePlus/TablePlus-Windows#302]
Moved from: https://github.com/TablePlus/TablePlus/issues/2104
 
I'm having trouble with connecting to a MySQL database over SSH using TablePlus on Windows. I manually selected the private key and entered the ip address and user to connect with. After trying to connect or testing I get the "invalid private key" message.

I've verified that the key is correct by manually connecting using Powershell
The permissions are read-only (don't know if that matters)
I've tried running TablePlus as administrator
I've also tried to rename the key to something with an extension (id_rsa -> id_rsa.priv) to ensure this isn't some weird Windows issue.
I read there should be an option to enable ssh logging, but I can't seem to find this option on the Windows version.
Build: 140
Windows build: 2004

Can someone help me with this issue?

**Comment by dantaeusb** [comment]
I was able to find a workaround by converting SSH key to the older RSA format (`-m rsa` flag for openssh, more details here: https://stackoverflow.com/questions/53134212/invalid-privatekey-when-using-jsch) but it doesn't seem to help really. Instead of throwing "Invalid Key", it throws the same error that occurs when you try to use password-protected key: `'waiting for initial communication packet', system error: 10060`, basically it still doesn't work at all but now has no idea what's happening and just not able to establish connection. Tried MariaDB, MySQL, Redis -- different errors, same meaning. I think its support for ssh is just broken / outdated.

**Comment by huyphams** [comment]
We used the newest version of libssh (which is also used by github.com) so I don't think it was broken or outdated, I believe it was misconfigured or some other issue, unfortunately, turn on debug log does not easy. We have debug log on macOS and Unix but not on Windows due to this reason.

**Comment by dantaeusb** [comment]
Anyway I can help? I love TablePlus in general and really want to use it, but paying $60 and being unable to do basic things is frustrating.

I'll try to disable other ssh-related windows features/programs, I've seen folks in relevant issues been talking about reverting git for windows helped in some cases, maybe it's some kind of interference here. I'll update this issue if I'll be able to find anything.

**Comment by huyphams** [comment]
I'm using TablePlus on Windows too, and the SSH work just fine (there are also a lot of users on Windows). I'm using a key which was generated by the command `ssh-keygen -t rsa -b 4096 -C "your_email@example.com"`
Make sure that the key works before put it in TablePlus.

**Comment by dantaeusb** [comment]
Sure thing, I was able to ssh -> mysql-client / redis-cli without any problem, it works just fine. Couple of notes about my config: I'm on Insider Preview, WSL2 enabled and using OpenVPN to our cluster. So it's "over SSH over VPN" connection, but shouldn't be a problem theoretically.

**Comment by dantaeusb** [comment]
I want to mention that on another Windows installation with the same Windows Dev Ring version everything works fine so far (same key, same host, same TablePlus version). Uninstalling Git for Windows on another environment had no effect, however I want to mention that I decided not to install it on a new environment.

For anyone having similar problem -- I used workaround with ssh tunneling (`ssh -fNL local_port:localhost:3306 remote_user@remote_host`)

**Comment by rizaldirnm** [comment]
I found this: https://stackoverflow.com/questions/65145221/mysql-could-not-connect-the-ssh-tunnel-access-denied-for-none

Maybe will help you.
```
The solution here was to convert the OpenSSH private key to an RSA private key.
ssh-keygen -p -m PEM -f C:/Users/username/.ssh/id_rsa
```

@dantaeusb

**Comment by huyphams** [comment]
If you have a chance, please install this patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
And enable SSH debug log in Menu > Help > Enable SSH Debug Log to see the issue.

**Comment by dantaeusb** [comment]
Oh I'm sorry, I'm not having that Windows machine with me right now. I would assume there was some incompatibility in rare occasions with other ssh libraries. For the last year, everything was fine for me on all platforms. I'll try to reproduce that if I'll have a chace.
