### ISSUE TITLE
UUID Generator Plugin

### ISSUE THREAD

**Issue by colinhall17** [TablePlus/TablePlus-Windows#306]
Table Plus Version 3.10.10 (142)

I installed the UUID Generator Version 1.0 which looking at the docs will give me an option to enter a UUID in the context menu but there is no option appearing.

![tplus](https://user-images.githubusercontent.com/5073205/96555211-651e6680-12af-11eb-818d-d90ef56bab56.png)

**Comment by huyphams** [comment]
Hi @colinhall17 please install this hot patch https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0 it should be supported now.
