### ISSUE TITLE
Copy All Column Values (varchar) quotation marks

### ISSUE THREAD

**Issue by Toadie1** [TablePlus/TablePlus-Windows#307]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MS SQL Server 2008

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.10.11 (146)

3. The steps to reproduce this issue:
1) Connect to any MS SQL database
2) Select some rows from any table
3) Right-click on varchar column and select Copy All Column Values
4) Paste the values to some textbox (Notepad, Filter row etc.) 
- The values are wrapped in double quotation marks and the query is not executable.
- The values should be wrapped in single quotation marks.

Thank you

![image](https://user-images.githubusercontent.com/22539609/96738960-8ff7e000-13bf-11eb-9116-5484f0975337.png)
![image](https://user-images.githubusercontent.com/22539609/96739062-ac941800-13bf-11eb-8447-637f0df804b7.png)

**Comment by Toadie1** [comment]
Same behavior is in Postgres
<img width="418" alt="TablePlus Bug" src="https://user-images.githubusercontent.com/22539609/107297053-db1f2700-6a72-11eb-9957-5b2c6e36e53b.png">

**Comment by Toadie1** [comment]
Hello @huyphams, May I ask if a solution to this problem is already in the development plan? The problem is very annoying and I think the repair would not be difficult.
Thanks

**Comment by huyphams** [comment]
Please update to our latest release 3.12.20 it should fix the issue.
