### ISSUE TITLE
Quickfilters don't work when applied on a field that is NULL

### ISSUE THREAD

**Issue by mtaki14** [TablePlus/TablePlus-Windows#308]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Mysql 5.7.31-1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 146

3. The steps to reproduce this issue:

While in Data view, right-click on any field that is NULL. Choose any quick filter. The result is that nothing happens.

**Comment by son11592** [comment]
Hi @mtaki14, thank you for your report. I found the problem and already fixed it. The update will be sent to you soon.

**Comment by huyphams** [comment]
Hi @mtaki14 please try this patch https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
it should solve the issue

**Comment by mtaki14** [comment]
Issue seems to be resolved, thank you
