### ISSUE TITLE
Req: Colorize left side connection tabs with dev/stage/prod colors

### ISSUE THREAD

**Issue by jhoffmann** [TablePlus/TablePlus-Windows#310]
Using TablePlus 3.11.10 (146) - x64 - Windows 10

On the 'Open Connection' window, it allows you to categorize your connections as local, development, staging, and production, and they're color coded which is fantastic.

I think it would be a great feature if the open connections tab on the left side of the window would indicate that, simply by making the database icons green/blue/yellow/red.  Either that, or add the color classification tag to the titlebar, something that makes it apparent when type of instance that's currently active.

**Comment by son11592** [comment]
Hi @jhoffmann, the latest version has been colorized. Please update your app to the latest version and feel free to let me know if you have any concerns.

PS: You can colorize your connection in the connection editing form or click on the status bar of the workspace.

![image](https://user-images.githubusercontent.com/4739616/97824795-7f186a00-1cef-11eb-8284-5be8960885e0.png)

![image](https://user-images.githubusercontent.com/4739616/97824901-c7378c80-1cef-11eb-806d-feb298d9d1b7.png)

**Comment by jhoffmann** [comment]
Looks amazing!  Check for updates still tells me 146 is the latest release though, but I'll definitely enjoy it when the update is available!
