### ISSUE TITLE
Row Detail Sidebar Fields in Random Order

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#311]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MS SQL 2014 Express
MySQL 5.7.17
MariaDB 10.0.20

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
146

3. The steps to reproduce this issue:
Normal table display
There doesn't seem to be any rhyme or reason to the order in which fields are displayed in the sidebar
![image](https://user-images.githubusercontent.com/25158630/97734165-c95ada80-1aa6-11eb-82e6-bfdfd8dc0059.png)
![image](https://user-images.githubusercontent.com/25158630/97734237-e1325e80-1aa6-11eb-958e-f9b8c00e4f33.png)

**Comment by rwhirn** [comment]
@huyphams Any chance I can get some attention on this? Is there something I am doing or have done that would cause this?

**Comment by huyphams** [comment]
Hi, thank you for reminding me. I've fixed this issue already. Please wait for the next update

**Comment by rwhirn** [comment]
Thanks @huyphams!

**Comment by huyphams** [comment]
I just wanna confirm. Did you change the column position on the table view or they are intact? (by dragging it)

**Comment by rwhirn** [comment]
@huyphams I may have moved one field at one time, but I thought of that and tried doing the "Reset Positions and Widths" and that did not help.

I assume since a new version just came out that you went ahead on this before I got back to you here. So far it looks to be fixed. I tried moving a field again and it did not affect the sidebar in any way.
