### ISSUE TITLE
History Search Sorts By Alphabetical Date

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#314]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.17

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
146

3. The steps to reproduce this issue:
Enter anything in "Search" box on History
Results are in alphabetical order of date name. 
November comes before October which comes before September
September 3, 2019 comes after September 28, 2020 but before September 30, 2019
![image](https://user-images.githubusercontent.com/25158630/98306569-b5711600-1f89-11eb-861d-42eac36714b6.png)
Should be sorted by date descending:
2020-09-28
2019-09-30
2019-09-03

**Comment by son11592** [comment]
Hi @rwhirn, the result will be sorted by the created date of the containing folder. The update will be sent to you soon. Thank you for your feedback.

**Comment by rwhirn** [comment]
Looks good. Thank you!
