### ISSUE TITLE
[Feature Request] Windows - Add a Shortcut key to create a new database quickly

### ISSUE THREAD

**Issue by Mutahhar** [TablePlus/TablePlus-Windows#316]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.24

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Tableplus 3.10.11 (146) for Windows

**It is a feature request to add a shortcut key to create a new database quickly.**

**Comment by huyphams** [comment]
You can press control + K and click add database.

**Comment by Mutahhar** [comment]
@huyphams 
yes, that involves more steps, and the use of a mouse or trackpad to click on the add database button. 
I want a keyboard-only shortcut with a single step.
