### ISSUE TITLE
Add support to import mysql dumps

### ISSUE THREAD

**Issue by rogeliobazh** [TablePlus/TablePlus-Windows#32]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5.7.18
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 48
3. The steps to reproduce this issue:
Now csv option is the only one for made imports.

**Comment by huyphams** [comment]
Hi @rogeliobazh we're working on this feature. it will be released soon!
