### ISSUE TITLE
Alert/Safe Mode 2 always showing alert dialog even on SELECT query

### ISSUE THREAD

**Issue by ajfick** [TablePlus/TablePlus-Windows#320]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 
Build 146

3. The steps to reproduce this issue:
- Connect to any DB
- Turn on Alert Mode 2 OR Safe Mode 2
- Get a warning for any query, even if just `SELECT * FROM table`

After reverting to the previous build, the issue goes away.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @ajfick I'm sorry about the issue, please try this hotpatch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

**Comment by rwhirn** [comment]
@huyphams Also didn't the "New Issue Title" field used to popup any other issues with similar titles so you didn't duplicate someone else's issue? What happened to that? It's not working.
