### ISSUE TITLE
CLIPBRD_E_CANT_OPEN Error when copying in sql editor

### ISSUE THREAD

**Issue by chrisindfw** [TablePlus/TablePlus-Windows#321]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySql

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 3.11.1 (148) x64

3. The steps to reproduce this issue:
- Open SQL editor
- Type
- Try to copy some text from the editor
- Copy error appears with details of "OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))"

This does not happen every time but it has been increasing. This seemed to have started a number of updates ago.

**Comment by chrisindfw** [comment]
Will this be addressed, deferred, etc? I did not see any notes with the closure.

**Comment by huyphams** [comment]
Hi @chrisindfw we have fixed it in the newest release 150
