### ISSUE TITLE
Feature request: Redis driver for windows client.

### ISSUE THREAD

**Issue by moxplod** [TablePlus/TablePlus-Windows#33]
Love tableplus and bought a licence - I use the windows version only. 
Wanted to request the redis driver.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
NA

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
windows build 50

3. The steps to reproduce this issue:
NA

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by nblackburn** [comment]
The Windows version has some catching up to do 😄

**Comment by huyphams** [comment]
It's supported in recently builds 😄
