### ISSUE TITLE
Safe mode 2 prompting for password even when executing SELECTs

### ISSUE THREAD

**Issue by kristiannotari** [TablePlus/TablePlus-Windows#331]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 11.8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 148 (also occurred in previous build)

3. The steps to reproduce this issue:

- create a connection to a PostgreSQL 11.8 database
- set safe mode 2
- try a select query

---

When using safe mode 2, which should prompt for password everytime except when executing select/explain/show queries, if I execute a select query (example: `SELECT * FROM table;`) I'm being prompted for password anyway. Also tried to change safe mode to 1 and to change it back to safe mode 2, with no success.

Is this the expected behaviour?

**Comment by huyphams** [comment]
Hi @kristiannotari please try this path and see how thing goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thank you!

**Comment by kristiannotari** [comment]
It works! Is it the next release or something? Am I supposed to keep working on the version you gave me or after this test I have to rollback to the public version then wait for this version to release?

**Comment by huyphams** [comment]
It's the hot patch, you can keep it @kristiannotari thank you for confirmation.
