### ISSUE TITLE
Cannot manipulate rows in Data view, when the table has a BINARY (Guid) primary key

### ISSUE THREAD

**Issue by Kermittt** [TablePlus/TablePlus-Windows#333]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):   MySQL 8.0.21

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):  build 148

3. The steps to reproduce this issue:
- Create a table with a BINARY(16) primary key.
- Add some rows to the table where the primary key is assigned a comb guid.
- Open the Data view for the table in TablePlus.
- Attempt to delete or modify any of the rows.
- Press commit.
- Red highlights for unsaved changes are cleared, but the modifications are lost and rows all return to their original state.

It is a fairly common practice for Guid primary keys to be stored as BINARY(16) in MySQL.  It would be extremely helpful if TablePlus could provide better support for this configuration.  Currently I am forced to write SQL queries which make use of a custom function to make a simple manual updates to one of these rows for testing.  IMHO a good solution for this would be some way to assign input and output functions to specific column types, so that whenever TablePlus needs to work with, or display the value, it is automatically passed through the appropriate functions to translate the value.

An example tutorial describing this usage pattern...
https://www.mysqltutorial.org/mysql-uuid

**Comment by huyphams** [comment]
Hi @Kermittt it's supported on our macOS version, we will bring this to Windows on the release next week.
