### ISSUE TITLE
Cant see Foreign Keys on table plus

### ISSUE THREAD

**Issue by moxplod** [TablePlus/TablePlus-Windows#34]
Not sure if that is not part of the feature set?

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Sql server 2016

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Windows 50

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks, @jny986 for the hint but I think it could be the arrow (likes the macOS version). I'm working on this feature. Click the arrow to navigate to linked row.
<img width="440" alt="foriegn key" src="https://user-images.githubusercontent.com/3654622/54169829-f0fec880-44a6-11e9-9fb1-90b907570ff6.png">
