### ISSUE TITLE
Support URL schemas

### ISSUE THREAD

**Issue by huyphams** [TablePlus/TablePlus-Windows#342]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): mysql

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): build 160

3. The steps to reproduce this issue: Try to launch TablePlus on Windows with a connection string

I'd like to launch TablePlus with a connection string, as is done easily on macOS as explained in https://github.com/TablePlus/TablePlus/issues/227#issuecomment-364486169

On macOS, you'd do this per #227
```
query="mysql://root:root@127.0.0.1:${DDEV_HOST_DB_PORT}/db" 
open "$query" -a "/Applications/TablePlus.app/Contents/MacOS/TablePlus" 
```

but how do you do it on Windows? 

The context: [ddev](https://github.com/drud/ddev) is a docker-based local development tool that happily launches tableplus on macOS using the technique above (and can heidisql on Windows because it has the technique) . We'd like to be able to support TablePlus on Windows and WSL2 as well.

**Comment by huyphams** [comment]
Now TablePlus supports open connection with url schema:

```
TablePlus.exe <URL>
```

**Comment by rfay** [comment]
@huyphams could you please give instructions about how to use this feature?

The result of this command
```
`/c/Program Files/TablePlus/tableplus.exe' mysql://root:root@127.0.0.1:49165/db
```

is "file path is not existed", which BTW should be "File path does not exist" in English.

**Comment by huyphams** [comment]
Hi @rfay I'm sorry, it was a bug and we have fixed it. I will build a patch later today.

**Comment by huyphams** [comment]
Hi @rfay if you have a chance, please install this hotpatch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thanks

**Comment by rfay** [comment]
I'm only working on this so that [ddev](https://github.com/drud/ddev) can support TablePlus on Windows and WSL2 as well as macOS. So I don't need a hotpatch, I just need a supported release with this feature in it. If you could notify here when a release is out that has been tested, and provide info on how to use the feature, that would be fantastic. Thanks!

**Comment by huyphams** [comment]
Yeah thanks, this fix will be included in the next update. We use the same URL format as the macOS version so you just copy the URL schema from the work that you've done before. If it does not work, it's our fault and we will fix it.
