### ISSUE TITLE
Custom Themes 🎨

### ISSUE THREAD

**Issue by luciano-work** [TablePlus/TablePlus-Windows#343]
Hi 👋
I realy love TablePlus and would like to create some custom colors themes. This is possible or a new feature?
All the best!

**Comment by son11592** [comment]
Hi @luciano-work, TablePlus has just added the `Theme & Colors` tab in the Preferences window to allow customize the color of the data table and the SQL editor. The next release will contain this feature. Hope you like it. 

### SQL Editor customized colors
![image](https://user-images.githubusercontent.com/4739616/104594579-eebdb480-56a3-11eb-8bbc-a0c6505448b9.png)


### Table Data customized colors
![image](https://user-images.githubusercontent.com/4739616/104594628-0137ee00-56a4-11eb-8168-19404f62860f.png)

**Comment by luciano-work** [comment]
Woo! This is amazing. 
Thank you 👍🏻
