### ISSUE TITLE
Crashes when I right-click on a cell in an unhighlighted row whose value is NULL

### ISSUE THREAD

**Issue by eli-s-r** [TablePlus/TablePlus-Windows#346]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0.21

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 150

3. The steps to reproduce this issue:

- Open TablePlus and connect to a database
- Open any table where one row has some NULL value for a field
- **Without left-clicking on any row or cell**, right-click on a cell whose value is NULL (for example, any of the four NULL cells in the image below)
- The program will then crash

![image](https://user-images.githubusercontent.com/64713921/101994332-ae77aa80-3c8f-11eb-84e3-0ea77f743a66.png)

**Comment by son11592** [comment]
Hi @eli-s-r, thank you for your feedback. I have fixed it. The update will be sent to you soon.

**Comment by eli-s-r** [comment]
Thank you so much!!

**Comment by huyphams** [comment]
HI @eli-s-r please install this patch, it should resolve the issue: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thank you!
