### ISSUE TITLE
DATE column appears as DATETIME column (SQL Server)

### ISSUE THREAD

**Issue by keithramnanan** [TablePlus/TablePlus-Windows#347]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Microsoft SQL Server

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 142

3. The steps to reproduce this issue: SELECT from a table that has a column of datatype: DATE

--
Displaying results for a table with data type DATE column, appears as data type DATETIME. 
12/15/2020 12:00:00 AM (wrong) 
12/15/2020 (right)

**Comment by son11592** [comment]
Hi @keithramnanan, this is has been fixed. The update will be sent to you soon. Thank you for your feedback.

**Comment by huyphams** [comment]
Please check out our latest release 154, it should fix the issue.
Thanks
