### ISSUE TITLE
Title bar background color not working properly on dark mode

### ISSUE THREAD

**Issue by mkismy** [TablePlus/TablePlus-Windows#348]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Not specific to a driver

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 150

3. The steps to reproduce this issue:
- Set to dark mode in Windows settings.
- Open TablePlus and connect to any server / driver.
- Title bar background color is white despite the content background in black, which makes the icons hard to see.
<img width="953" alt="Screenshot 2020-12-13 211108" src="https://user-images.githubusercontent.com/8445575/102011682-355c7e00-3d89-11eb-8098-3cedecb6db99.png">

It works fine on the welcome screen
![Screenshot 2020-12-13 212840](https://user-images.githubusercontent.com/8445575/102011873-6d17f580-3d8a-11eb-9837-3afde166c3a1.png)

**Comment by huyphams** [comment]
Hi @mkismy did you import the connection from the macOS or somewhere? TablePlus will use the custom color instead of the default.
Please click the title and change the color back

**Comment by huyphams** [comment]
<img width="1675" alt="Screen Shot 2020-12-13 at 7 41 34 PM" src="https://user-images.githubusercontent.com/3654622/102012147-3b4b6280-3d7b-11eb-8cec-b28b5b1e856f.png">

Please let me know if you're still seeing the issue, then I will reopen the issue.

**Comment by mkismy** [comment]
HI, yes I did import the connection settings from macOS.
Changing the color from title bar did work. Thanks.

Just out of curiosity, are there any way to reset title bar color to default?

**Comment by huyphams** [comment]
Unfortunately, there is no way to reset all at once. However, you can choose to color within the title bar, TablePlus will switch to darker or lighter automatically

**Comment by mkismy** [comment]
Understood. Thanks anyway.
