### ISSUE TITLE
Crash after invalid find value

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#349]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server 2014

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
150

3. The steps to reproduce this issue:
As shown in this picture, I select "IN" and type my text value I'm filtering for which is "ONL" and click "Apply". I get an "Invalid column name 'ONL'" error. I meant to select "=". I click "OK", change the "IN" to "=" and click "Apply" and TablePlus crashes.
![image](https://user-images.githubusercontent.com/25158630/102667221-81733e00-414e-11eb-9e21-35cef69dfc2e.png)

**Comment by rwhirn** [comment]
@son11592 What are you confused about?
 I selected "cclass IN ONL" which is of course invalid because ONL needed to be quoted 'ONL'
 So I changed it to "cclass = ONL" and when I click "Apply" the program crashes. It is easily replicable.

**Comment by rwhirn** [comment]
Thought I would give an update on this issue since its been awhile.
Using Build 158 
It doesn't crash now, but it still messes up TablePlus so badly that you have to quit and restart.
If I use "=" the query works fine
![image](https://user-images.githubusercontent.com/25158630/113920708-c0370d80-97aa-11eb-8c79-aafa809ad4ce.png)
Now if I do "IN", I get an error  
![image](https://user-images.githubusercontent.com/25158630/113920894-feccc800-97aa-11eb-91a2-2193a66f1af6.png)
Now everything is messed up
there are no field names in the field name dropdown anymore
![image](https://user-images.githubusercontent.com/25158630/113921213-566b3380-97ab-11eb-96d9-74b561659949.png)
(this is what was in there before)
![image](https://user-images.githubusercontent.com/25158630/113920544-86fe9d80-97aa-11eb-8f06-410c4ac89e6b.png)
and if I try to change back to "=" it gives the same error even tho it worked before
![image](https://user-images.githubusercontent.com/25158630/113921457-a4803700-97ab-11eb-82f0-ddff30cd7060.png)
Clicking "Unset" and then "Apply" brings it back to proper operation

**Comment by rwhirn** [comment]
@huyphams @son11592
Not sure if you have looked into this or not.

**Comment by huyphams** [comment]
It's fixed in the newest update, please let me know if you still see the issue.

**Comment by rwhirn** [comment]
Yes. All good. Thanks.
