### ISSUE TITLE
System Theme (Dark / Light based on windows 10 color theme)

### ISSUE THREAD

**Issue by suabahasa** [TablePlus/TablePlus-Windows#352]
Please add a new theme option following the windows 10 theme.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): -, general

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 152

3. The steps to reproduce this issue: -

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @suabahasa thank you for the feedback. Please do not remove the template issue questions. it helps me to keep track of the issue.

**Comment by suabahasa** [comment]
I have edited and add the template issue.

**Comment by huyphams** [comment]
It will be released in the next update, thanks!
