### ISSUE TITLE
SQL Server BIT values return to Null when committing None Null Value. 

### ISSUE THREAD

**Issue by APet74** [TablePlus/TablePlus-Windows#354]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQL Server V 14.0.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 152

3. The steps to reproduce this issue: Create a Table with a BIT column, attempt to set values in the bit column using data view. When committing 0/1 (False/True) resets the value to null. I can edit values in any other column but my bit columns reset to NULL every time I commit data to them. 

Noted: If the bug is related to data, please attach an example SQL data.

https://i.imgur.com/7gtvSmd.gif

**Comment by son11592** [comment]
Hi @APet74, this is has been fixed. The update will be sent to you soon. Thank you for your feedback.

**Comment by APet74** [comment]
Thank you.

**Comment by huyphams** [comment]
Please check out our latest release 154, it should fix the issue.
Thanks
