### ISSUE TITLE
ERROR:  parse error - invalid geometry

### ISSUE THREAD

**Issue by rados71** [TablePlus/TablePlus-Windows#355]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 12.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 152

3. The steps to reproduce this issue:
I want to copy a table row with a goem field. During copying, the GEO position transmits a comma, not a dot, and then it reports an error when pasting. If I replace the commas with dots, it did it.
The Apple version does not make this mistake.
Wrong line:
504	29	"{""en"": ""1.1.1.1""}"	"{""status"": ""OK"", ""address"": ""1.1.1.1"", ""dimming"": 100, ""icon_name"": ""lighting"", ""fill_color"": {""status"": ""#1eff00"", ""dimming"": ""#edfeff"", ""_default"": ""#34ebfe""}}"	SRID=4326;POINT(**18,302576244 48,249586051**)	399.435.435.435.435.457.500.503.504	2020-05-21 10:24:17	2020-11-01 16:54:12	NULL	3a48ad50-9b4d-11ea-b1ac-65eb4371b065	"{""thingsboard_uuid"": ""3a48ad50-9b4d-11ea-b1ac-65eb4371b065""}"

**The same as SQL statement:**
INSERT INTO "public"."entity" "fk_entity_type_id", "name", "attributes", "geom", "tree_path", "created_at", "updated_at", "level", "thingsboard_uuid", "interface") VALUES
(29, '{"en": "1.1.1.1"}', '{"status": "OK", "address": "1.1.1.1", "dimming": 100, "icon_name": "lighting", "fill_color": {"status": "#1eff00", "dimming": "#edfeff", "_default": "#34ebfe"}}', ST_GeomFromText('SRID=4326;POINT(**18,302576244 48,249586051**)'), '399.435.435.435.435.457.500.503.504', '2020-05-21 10:24:17', '2020-11-01 16:54:12', NULL, '3a48ad50-9b4d-11ea-b1ac-65eb4371b065', '{"thingsboard_uuid": "3a48ad50-9b4d-11ea-b1ac-65eb4371b065"}');

After corection is ok.
504	29	"{""en"": ""1.1.1.1""}"	"{""status"": ""OK"", ""address"": ""1.1.1.1"", ""dimming"": 100, ""icon_name"": ""lighting"", ""fill_color"": {""status"": ""#1eff00"", ""dimming"": ""#edfeff"", ""_default"": ""#34ebfe""}}"	SRID=4326;POINT(**18.302576244 48.249586051**)	399.435.435.435.435.457.500.503.504	2020-05-21 10:24:17	2020-11-01 16:54:12	NULL	3a48ad50-9b4d-11ea-b1ac-65eb4371b065	"{""thingsboard_uuid"": ""3a48ad50-9b4d-11ea-b1ac-65eb4371b065""}"
**The same as SQL statement:**
INSERT INTO "public"."entity" ("fk_entity_type_id", "name", "attributes", "geom", "tree_path", "created_at", "updated_at", "level", "thingsboard_uuid", "interface") VALUES
( 29, '{"en": "1.1.1.1"}', '{"status": "OK", "address": "1.1.1.1", "dimming": 100, "icon_name": "lighting", "fill_color": {"status": "#1eff00", "dimming": "#edfeff", "_default": "#34ebfe"}}', ST_GeomFromText('SRID=4326;POINT(**18.302576244 48.249586051**)'), '399.435.435.435.435.457.500.503.504', '2020-05-21 10:24:17', '2020-11-01 16:54:12', NULL, '3a48ad50-9b4d-11ea-b1ac-65eb4371b065', '{"thingsboard_uuid": "3a48ad50-9b4d-11ea-b1ac-65eb4371b065"}');

The Apple version does not make this mistake.
It is not possible to simply copy the rows Ctrl + C and Ctrl + P in windows version.

Noted: If the bug is related to data, please attach an example SQL data.

Thx for fix.

**Comment by son11592** [comment]
Hi @rados71, I tried to reproduce this issue but nothing happened.

### Here is the testing data

![image](https://user-images.githubusercontent.com/4739616/103634827-35136500-4f7a-11eb-92c4-7849ac116cd5.png)

### And here is the result when:

- Copy with a shortcut: `Control + C`

```
Point	POINT(18.302576244 48.249586051)
Point	SRID=4326;POINT(18.302576244 48.249586051)
```

- And the copy as SQL statement: 

```
INSERT INTO "public"."geometries" ("name", "geom") VALUES
('Point', ST_GeomFromText('POINT(18.302576244 48.249586051)')),
('Point', ST_GeomFromText('SRID=4326;POINT(18.302576244 48.249586051)'));
```

There is no `comma` issue in those results. Could you give me more detail about this issue, ex: some of your testing data, more reproducing steps... It may help us fix it quickly. Thanks.

**Comment by rados71** [comment]
Hi,
On your screen are used dots not commas. But in my app I see commas. See my screen. But in apps I not able setting form of visualisation.
![image](https://user-images.githubusercontent.com/76955062/103665102-51f86a00-4f73-11eb-827b-0b30e4a25ef2.png)

thx. 
rados71

**Comment by huyphams** [comment]
Hi @rados71 please download and install this patch, it should resolve your issue: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

**Comment by rados71** [comment]
Hi,
I installed this update, but it the same build as I have already using (152). Issue is w/o change (not fixed).
![image](https://user-images.githubusercontent.com/76955062/103670733-3fcdfa00-4f7a-11eb-9cae-6d349ab2cdaa.png)

On your screen was dots as geo separator 18**.**XXX and on my screen is comma 18**,**XXX. This is main issue.  

Thx.

**Comment by huyphams** [comment]
Sorry, it was a mistake, please download this patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

**Comment by rados71** [comment]
Thank you very much. It looks good now. It's very useful for me.
rados71
