### ISSUE TITLE
CSV export (comma separated) doesn't quote text with comma inside

### ISSUE THREAD

**Issue by crestQ** [TablePlus/TablePlus-Windows#356]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB connector 3.11

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
152

3. The steps to reproduce this issue:
- run the simple query `select 222 as id,'prefix text,,some dummy text' as textfield;`
- export result to CSV (convert NULL: on; convert line break: off; put field name: on; delimiter: comma; swap: Quote if needed; line break: \r\n; decimal: dot)
- open saved CSV in notepad - there is no quotes in second line for field `prefix text ...`

**Comment by son11592** [comment]
Hi @crestQ, this issue has been fixed. The update will be sent to you soon. Thank you for your feedback.

**Comment by huyphams** [comment]
Please check out our latest release 154, it should fix the issue.
Thanks
