### ISSUE TITLE
Detail Sidebar shows wrong table after "Refresh"

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#357]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
2. MySQL 5.7.17

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3. 152

3. The steps to reproduce this issue:
4. 
![image](https://user-images.githubusercontent.com/25158630/103836870-e6d09580-504f-11eb-9500-af0644de270b.png)
I have 4 tables open
I am working on one record in Tab 2. I am not switching tabs at all. I make a change to the one record in Tab 2 via the detail sidebar. Then I hit the "Refresh" icon. The screen refreshes then the detail sidebar refreshes and then the detail sidebar switch to the record that is currently selected in Tab 3, which has nothing to do with the record in Tab 2.

P.S. If I click on Tab 3 wait for it to refresh, then click back on Tab 2, I get the proper record in the detail sidebar. But If I run through the steps above again, it shows the wrong record again

**Comment by son11592** [comment]
Hi @rwhirn, thank you for your feedback. This issue has been fixed. The new update will be sent to you soon.

**Comment by huyphams** [comment]
Please check out our latest release 154, it should fix the issue.
Thanks
