### ISSUE TITLE
Drag and move window broken on Windows

### ISSUE THREAD

**Issue by niklasnikanti** [TablePlus/TablePlus-Windows#359]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
152

3. The steps to reproduce this issue:
Try to drag and move the TablePlus window and it doesn't move. It sometimes (seemingly) randomly works and then it doesn't no matter how many times I try to drag and move the window.

The latest update seem to have broken the drag and move the window on Windows. It worked just fine before the update.

**Comment by son11592** [comment]
Hi @niklasnikanti, can you describe more detail about it (which window happened)? Or give me some pictures, gif, etc.. to help us find out the problem.

**Comment by niklasnikanti** [comment]
It happens in the database view window. I just tested the last few versions and it seems that the 3.12.4 (152) seems to have broken it since 3.12.13 (152) works just fine.

![tablepluswindow](https://user-images.githubusercontent.com/33550269/104280804-2286b780-54b5-11eb-9ea0-9339b293c127.png)

**Comment by huyphams** [comment]
Hi @niklasnikanti please try this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

**Comment by niklasnikanti** [comment]
It works now. Thank you!
