### ISSUE TITLE
Hiding column does not appear to do anything

### ISSUE THREAD

**Issue by windowsdeveloperwannabe** [TablePlus/TablePlus-Windows#360]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.0
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 152
3. The steps to reproduce this issue:
Right click column, select Hide this column

I created a new text column with a lot of data. This made basic browsing of the rows very slow in TablePlus. I tried hiding the column to solve the problem, but it does not appear to do anything? 😃
![hide](https://user-images.githubusercontent.com/47078223/104604894-84e2e200-5686-11eb-9299-e5418c2f0499.gif)

**Comment by huyphams** [comment]
Hi @windowsdeveloperwannabe thank you for the feedback. Please install this patch, it should fix your issue: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

**Comment by windowsdeveloperwannabe** [comment]
> Hi @windowsdeveloperwannabe thank you for the feedback. Please install this patch, it should fix your issue: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

Hey, thanks hiding the column works now! 😻 Unfortunately it does not help with the slowness, Is there any way to skip loading the column? 🤔 It is about 50kb of text.
