### ISSUE TITLE
Cannot export results as SQL. 

### ISSUE THREAD

**Issue by kennysdavisinstruments** [TablePlus/TablePlus-Windows#361]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Not sure what this means.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
version 3.12.3 (152) - xx64

3. The steps to reproduce this issue:
This is a Cassandra Database
a. write a query that returns some records.
b. select a record by left clicking on the record in the results.
c. click the "Export" button on the lower left below the results.
d. Sect the "SQL" tab
e. Click the "Export" button

Result: Errir shown "Can't detect table"

**Comment by huyphams** [comment]
Please check out our latest release 154, it should fix the issue.
Thanks
