### ISSUE TITLE
Reload after ALTER VIEW change in structure does not update filter fields

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#365]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.17

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
154

3. The steps to reproduce this issue:
Open a view
Open "Filters" if not already opened
Alter view in another tab
Add a new field
Go Back to table tab
Click on "Reload" to reload table where you can see your new field has been added
Click on the filter "field name" dropdown
New field does not appear in the dropdown even if you create a new filter

**Comment by son11592** [comment]
Hi @rwhirn, I tried to follow your reproduce step but the error did not happen. See the below gif, did I miss any steps? Please give me more detail about this issue, eg: photo, gif, video..., thank you for your feedback.

![bobo](https://user-images.githubusercontent.com/4739616/105633817-6b634680-5e8d-11eb-9373-79e02bdd0406.gif)

**Comment by rwhirn** [comment]
@son11592 Your are correct. I was working with a MySQL 'VIEW" not a table. Also, I was doing an "ALTER VIEW" in another tab as a "SQL command". After running the alter I would return to the VIEW tab and hit "Reload" and while the columns would update correctly, the filter dropdowns would not. 

I have update the title and description to reflect this.

Since this does not effect tables and only happens on views, I would consider it a much, much lower priority.

**Comment by son11592** [comment]
Hi @rwhirn, thank you so much for your feedback. I found the root cause of this issue. The update will be sent to you soon.
