### ISSUE TITLE
Invalid JSON in duplicated row

### ISSUE THREAD

**Issue by Toadie1** [TablePlus/TablePlus-Windows#368]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 11.1
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.112.10 (154)
3. The steps to reproduce this issue:
I have a row with column containing JSON data.
When I select the row, right click on them and click Duplicate the new duplicated row has "doubled" double-quotes.
When I select the new duplicated row and create duplicate I got JSON with 4 double-quotes, next duplicate has 8 etc.
You can see this in screenshot - the dark row is original, the green rows are duplicates of previous row.

![image](https://user-images.githubusercontent.com/22539609/105827805-b9c63180-5fc2-11eb-89b4-209a80cece06.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by son11592** [comment]
Hi @Toadie1, this issue has been fixed. The update will be sent to you soon. Thank you for your feedback.
