### ISSUE TITLE
datetime2 fields in SQL Server are displayed as null

### ISSUE THREAD

**Issue by phillip-mofadeng** [TablePlus/TablePlus-Windows#370]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
"Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64) 
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 154
3. The steps to reproduce this issue:
datetime2 fields display as NULL even though they have value and can be viewed with SQL Server Management Studio
Noted: If the bug is related to data, please attach an example SQL data.
![image](https://user-images.githubusercontent.com/53420490/105910315-a2a04600-608d-11eb-97c3-c1a79e804c2c.png)
![image](https://user-images.githubusercontent.com/53420490/105910368-b5b31600-608d-11eb-85b9-f67c342fe906.png)
![image](https://user-images.githubusercontent.com/53420490/105910446-d4b1a800-608d-11eb-8a53-7414f1fae14f.png)

**Comment by huyphams** [comment]
Hi @phillip-mofadeng if you have a chance, please install this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thank you!

**Comment by phillip-mofadeng** [comment]
> Hi @phillip-mofadeng if you have a chance, please install this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
> Thank you!

Just installed the patch, problem seems to be fixed. Cheers
