### ISSUE TITLE
Issue with Login

### ISSUE THREAD

**Issue by irshadelevision** [TablePlus/TablePlus-Windows#373]
1. MariaDB

2. Build 154

3. Today when I try to access already saved db. it is show access denied to some url which is not the one I entered.
    Attached an image of that issue.

![tableplus](https://user-images.githubusercontent.com/60963739/106647868-55681c80-6544-11eb-940a-c01831ca93c7.PNG)

**Comment by huyphams** [comment]
Hi that ip address is your router ip/internet provider ip.

Your host does not allow access from the out side, please use Over SSH
