### ISSUE TITLE
[Feature Request] Make table columns re-orderable using the interface

### ISSUE THREAD

**Issue by jakobwildrain-si** [TablePlus/TablePlus-Windows#376]
1. Which driver are you using and version of it: **MySQL, MariaDB, SQLite, PostgreSQL, Microsoft SQL Server**, not sure how to tell versions, but I assume they are latest for my build of TablePlus
2. Which TablePlus build number are you using: **Build 156**
3. Feature request:

Currently the only way to reorder columns in an SQL (and derivatives) table is to issue an ALTER statement. After that, to see the new table structure you have to close the table tab and reopen.
It would be immensely more convenient if the columns could be re-ordered using drag and drop (perhaps a little "handle" area on the left to grab it by) or, as an option, right clicking a column could have a reorder option, which would ask for a column name AFTER which to place the column in question.

You can still force people to commit changes to the table just like after adding or editing column definitions, just to avoid accidental reordering, although if it's done using right-click, I wouldn't consider it accidental.

And obviously refresh the Structure view to reflect the new columns order.

Thank you for all of the hard work and for a great product! Finally a worthy alternative for SequelPro (Mac) on a PC

**Comment by huyphams** [comment]
HI @jakobwildrain-si you can change the column order by editing the first field in table structure:

<img width="1274" alt="Screen Shot 2021-02-12 at 06 51 19" src="https://user-images.githubusercontent.com/3654622/107713866-b939d480-6cfe-11eb-8ddb-975dadb9acec.png">

After that you can hit control + S to save (control shift P to see the generated queries).

If you change the structure with ALTER query, you don't have to close the tab, just  press control + R to reload the current table.

**Comment by jakobwildrain-si** [comment]
So I would change the # field of the column I want to move and set it to... what exactly? The number of the column after which the column in question should be inserted? Is that how that works? Can I set it to 0 so it goes to the top and becomes the first field?

**Comment by huyphams** [comment]
Yes, you can give it a try, 0 or 1 and see how it goes.

**Comment by gwc4github** [comment]
We could use a better implementation of this feature. It doesn't work at all for PostgresSQL
"Warning 
Currenly, PostgreSQL doesn't support changing ordinal position"


<img width="262" height="218" alt="Image" src="https://github.com/user-attachments/assets/35f539e8-db77-46d3-a45c-66b8606e726b" />
