### ISSUE TITLE
Export to json does not escape newline correctly

### ISSUE THREAD

**Issue by jiangjy1982** [TablePlus/TablePlus-Windows#379]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
156

3. The steps to reproduce this issue:
Select a text column having newlines in it and export to a json file. Open the file and the newlines are not escaped.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
HI @jiangjy1982 please install this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

**Comment by jiangjy1982** [comment]
Hi Henry,

Thanks for the quick response and fix. Yes, I confirmed it's now working
like a charm!


Best,
Jet
