### ISSUE TITLE
No visual dark mode for TablePlus on windows

### ISSUE THREAD

**Issue by ZahidMKhan** [TablePlus/TablePlus-Windows#38]
1. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 52

**Comment by nblackburn** [comment]
The Windows version is quite far behind due to it being newer.

**Comment by johnianb** [comment]
When is the possible deployment of dark theme for windows?

**Comment by huyphams** [comment]
Hey, I'm implementing it, it will be available soon. Hopefully, I can delivery it in the build 74.

**Comment by huyphams** [comment]
Next build 75 👍 
<img width="1174" alt="Screen Shot 2019-08-24 at 1 59 26 AM" src="https://user-images.githubusercontent.com/3654622/63632756-d6627b00-c612-11e9-959a-a8b88008a7c9.png">

**Comment by huyphams** [comment]
Coming soon!
![image](https://user-images.githubusercontent.com/3654622/63645122-db383500-c6cd-11e9-80ff-74db3b4a1f47.png)

**Comment by huyphams** [comment]
It's released now.

**Comment by johnianb** [comment]
great. thanks!
