### ISSUE TITLE
Export to clipboard

### ISSUE THREAD

**Issue by jonorozcoc** [TablePlus/TablePlus-Windows#382]
A helpful feature to improve development time is export to clipboard.

Some use cases:

- Writing mock apis from query results (Using export to JSON function)
- Testing transformations (csv, json) to other formats so we can paste real data for those tests

This function should be row limited to avoid freezing with large results

**Comment by huyphams** [comment]
I think the Copy as > ... is the feature that you're looking for?
<img width="603" alt="Screen Shot 2021-03-01 at 8 01 26 AM" src="https://user-images.githubusercontent.com/3654622/109440283-56696c80-7a64-11eb-9e1d-b5c1818ee81c.png">

**Comment by jonorozcoc** [comment]
Yes, you're right!

Thanks for your quick response
