### ISSUE TITLE
[suggestion] synchronise free trial features across platforms

### ISSUE THREAD

**Issue by alloystory** [TablePlus/TablePlus-Windows#386]
I use switch between Windows and Mac frequently. 
Mac's free trial allows me to open 2 tabs, but perform filters on each table view. 
Windows' free trial allows me to open 3 tabs, but does not allow me to perform filters.

I personally prefer the Mac's free trial features, but more importantly, I hope that these features can be synchronised so I don't have to switch my usage behaviour when I switch between OSes.

**Comment by huyphams** [comment]
Hi @alloystory unfortunately, it was our decision in the first place. If you want to remove those limitations, the best way is to purchase a combo license and support our team to improve the app. Have a great day.
