### ISSUE TITLE
Couldn't make backup of a table

### ISSUE THREAD

**Issue by rmontanana** [TablePlus/TablePlus-Windows#387]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 5.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 158    3.12.19 (158)
3. The steps to reproduce this issue:
Menu - File - Backup - Select database - select table - start backup
Noted: If the bug is related to data, please attach an example SQL data.

mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'inventario2' AND TABLE_NAME = 'Articulos';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109)
Done

![Captura](https://user-images.githubusercontent.com/1431097/110931999-302cb200-832b-11eb-88ac-62a323931676.png)

**Comment by huyphams** [comment]
Hi @rmontanana please try to add this flag and see how it goes.

<img width="311" alt="Screen Shot 2021-03-15 at 6 56 02 AM" src="https://user-images.githubusercontent.com/3654622/111088797-8849fb00-855b-11eb-8b6a-d0e99ee820f3.png">

**Comment by rmontanana** [comment]
Thanks, adding this option it works fine.
