### ISSUE TITLE
no dropdown 

### ISSUE THREAD

**Issue by qsaifudin** [TablePlus/TablePlus-Windows#388]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @qsaifudin please answer the template issue questions, thank you in advance.
