### ISSUE TITLE
Error copying text within query window

### ISSUE THREAD

**Issue by athen66** [TablePlus/TablePlus-Windows#389]
Happens randomly, locks the whole window for 10 seconds. Very annoying.
![tableplus-copy-error](https://user-images.githubusercontent.com/5891861/112403144-1b590280-8ccb-11eb-8d86-7ad439927cef.png)

1. PostgreSQL

2. 158

3. copy/cut any text

4. Windows 10

**Comment by huyphams** [comment]
Hi @athen66 please try our latest release and see how it goes
Thanks
