### ISSUE TITLE
Crashes when saving Favorites with ">" in fave name

### ISSUE THREAD

**Issue by CharlieF107** [TablePlus/TablePlus-Windows#39]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
probably PostgreSQL 9.5.14 (or, unknown)
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Ver 1.9(52) on Windows 10
3. The steps to reproduce this issue:
Right-click on an Favorite "Group" name.
Select Add Favorite.
Enter a Favorite Name
My example: Learner Progress > run in Production db
Enter/paste the query in main window
Click Save.
Hourglass appears briefly then application crashes out totally.
Other tests indicate the > sign in the Favorite name field is the fault
Substitution with a hyphen succeeds

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @CharlieF107 let me fix it!
