### ISSUE TITLE
Cassandra - decimal value shows weird chars

### ISSUE THREAD

**Issue by nizrix** [TablePlus/TablePlus-Windows#390]
Cassandra, build 158

querying Cassandra return "junk" value instead of decimal value.

![image](https://user-images.githubusercontent.com/81955922/113554283-c473f700-9601-11eb-88dd-f13bdf8ef9b2.png)

**Comment by son11592** [comment]
Hi @nizrix  please answer the template issue questions, thank you in advance.

**Comment by nizrix** [comment]
Hi @son11592
I am using Cassandra (3.11.4) on TablePlus for windows build 158.
this bug is critical for us to continue using your product.

**Comment by huyphams** [comment]
We're working on it, thanks @nizrix

**Comment by huyphams** [comment]
Hi @nizrix if you have a chance, please install this hotpatch, TablePlus now can decode varint and decimal: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please let us know if you are seeing any issues.
