### ISSUE TITLE
Feature Request: Foreign key Quick View

### ISSUE THREAD

**Issue by daugaard47** [TablePlus/TablePlus-Windows#393]
Would be nice to hover over a foreign key and see the relationship data. 

Example:
 - I have a posts table with a user_id foreign key
 - When I hover over the user_id foreign key on the posts table, I can see that users data in a pop window on the posts table

Do you have any plans for this feature in the pipeline?

**Comment by huyphams** [comment]
Hi, I just wanna make sure that you are aware of the `control + enter` could do the same thing

**Comment by daugaard47** [comment]
Woah. No I was not aware. Thank you for creating this and pointing out this feature.
Really appreciate the immediate reply too. Great customer service!
