### ISSUE TITLE
Results of multiple queries visible

### ISSUE THREAD

**Issue by djmcelle** [TablePlus/TablePlus-Windows#395]
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
160

3. The steps to reproduce this issue:
When I use multiple queries I would really like to see the results of any query at a glance, just like in SSMS. In TablePlus I only get the result of either the first query or the one activated even if I use "Run All" and "Append all results in one Tab". 

SSMS:
![image](https://user-images.githubusercontent.com/34491252/115117295-14f23980-9f9e-11eb-86da-521caac2b911.png)

TablePlus:
![image](https://user-images.githubusercontent.com/34491252/115117395-a19cf780-9f9e-11eb-98c3-ece48ec97dfe.png)

**Comment by huyphams** [comment]
Hi @djmcelle please add the `;` the end of the query, we also support two result view mode.

<img width="829" alt="Screen Shot 2021-04-17 at 22 18 23" src="https://user-images.githubusercontent.com/3654622/115117877-d58e1200-9fca-11eb-9770-3fc1721bf621.png">

**Comment by djmcelle** [comment]
Hi @huyphams, Thank you very much for your quick reply!
As I had already set everything right, nothing has changed (still "Run all" is used):
![image](https://user-images.githubusercontent.com/34491252/115123957-e6855600-9fbf-11eb-944e-ae8412ef6ae2.png)

**Comment by huyphams** [comment]
I'm using Append all result in one tab and choose Run All, the result is appending correctly, could you double check it? The shortcut to `Run All Queries` is `Control + Shit + Enter` and the shortcut to run the `Current Query` is `Control + Enter`.
<img width="1081" alt="Screen Shot 2021-04-18 at 06 13 07" src="https://user-images.githubusercontent.com/3654622/115129115-2aeb1300-a00d-11eb-8b50-e306ce82b474.png">
