### ISSUE TITLE
Stored passwords and passphrases disappear for no apparent reason

### ISSUE THREAD

**Issue by buergimi** [TablePlus/TablePlus-Windows#396]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **MariaDB 10.1 and 10.3 and Microsoft SQL Server**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **160**

3. The steps to reproduce this issue: **cannot reproduce. Happened to me while adding, editing or removing connections. It happened a lot! Since I installed TablePlus today, it happened 5 or 6 times.**

Noted: If the bug is related to data, please attach an example SQL data.

Please have a look at this -- it's really crippling the effective use of this application. 
Kind regards.

**Comment by jgillyon** [comment]
Just had this happen to me today too using the latest version. I wasn't editing/adding any connections, just opened the program as usual.

**Comment by son11592** [comment]
Hi @jgillyon, does it happen before? Or just happened after the last update?

**Comment by jgillyon** [comment]
First time today. I've been using TablePlus for 1 year or more

**Comment by huyphams** [comment]
Can you reproduce it @jgillyon? if yes, please give us the steps to reproduce the issue. It could be an exception with special characters.

**Comment by jgillyon** [comment]
> 
> 
> Can you reproduce it @jgillyon? if yes, please give us the steps to reproduce the issue. It could be an exception with special characters.

Not sure how it happened, but will let you know if I manage to reproduce it.

**Comment by jgillyon** [comment]
Just a note that this just happened right now again. I had been working with multiple windows in the morning and then closed everything. When opened again, the issue happened. I'm running build 4.2.1 (174) x64. I can't reproduce it, but are there some sort of logs I can send you?

**Comment by MohammadAbusaleh** [comment]
This happened to me 4 times also randomly without nothing special happening.

**Comment by MohammadAbusaleh** [comment]
Just happened now, build 176, been using it since the morning.

**Comment by huyphams** [comment]
Hi guys I've made an attempt to fix this issue, if you have a chance, please download this hotpatch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please let me know if you're still seeing the issue!
