### ISSUE TITLE
SQL queries not saving in history panel

### ISSUE THREAD

**Issue by annarobb90** [TablePlus/TablePlus-Windows#398]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 11.11

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 162

3. The steps to reproduce this issue: Run a custom SQL query, try to find it in history panel, doesn't show up. Only shows "UPDATE" queries, rather than "SELECT" queries

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi, please update to the build 164. It should fix the issue.

**Comment by annarobb90** [comment]
Fabulous! And very efficient.
Thank you.
