### ISSUE TITLE
Build 162 doesn't contain saved query title in tab

### ISSUE THREAD

**Issue by annarobb90** [TablePlus/TablePlus-Windows#399]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 11.11

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 162

3. The steps to reproduce this issue: When loading a favourite query, it titles the query as "SQL" instead of the query name. This is frustrating as when i have 20 queries open, i have to flick through all of them to find the one i'm lokoign for. In my previous build (160) it would show the title of the query in the tab. Why has this feature been removed? 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @annarobb90 we are fixing this issue. Thank you!

**Comment by huyphams** [comment]
Hi, please update to the build 164. It should fix the issue.
