### ISSUE TITLE
Crash on Connect

### ISSUE THREAD

**Issue by Dragony** [TablePlus/TablePlus-Windows#4]
1. Which driver are you using and version of it; **MySql**

2. Which TablePlus build number are you using: **Build 4**

3. The steps to reproduce this issue:

- Open TablePlus
![image](https://user-images.githubusercontent.com/465941/45450414-79f39d80-b6d8-11e8-9cdf-3a4984c5a27e.png)

- Add a new Connection, fill out some details and click "test"
![image](https://user-images.githubusercontent.com/465941/45450454-98599900-b6d8-11e8-93d9-f649d4e69643.png)

- Client will crash
![image](https://user-images.githubusercontent.com/465941/45450481-ac9d9600-b6d8-11e8-9cac-0bb00d3a24b6.png)

- The same issue occurs if I save the connection and try to connect.

Some basic information about my computer:
![image](https://user-images.githubusercontent.com/465941/45450599-056d2e80-b6d9-11e8-9957-2f8e28c07a58.png)

Please let me know if I need to provide more information.

**Comment by Dragony** [comment]
OK after some testing I found out this errors happens if I leave the Port blank (I assumed it will use a default port)

**Comment by huyphams** [comment]
Fixed on build 5.

**Comment by shaunakv1** [comment]
I am running into this crash issue when trying to connect to postgres. my port is not blank

**Comment by huyphams** [comment]
Could you show me the screenshot of the connection @shaunakv1 I've tried everything but it did not crash, I'm not sure how to reproduce it. Thanks!
