### ISSUE TITLE
Feature Request: Search + Sorting in 'Open Database' window

### ISSUE THREAD

**Issue by bwat47** [TablePlus/TablePlus-Windows#40]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQL Server 2014

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
52

A few things that I think would enhance the 'Open Database' window (presently selecting a database can be a little cumbersome if you have a large number of databases):

1. A search filter to filter the list of databases (similar to the search filter above the list of tables once you've opened a database). 

2. Sort the databases in alphabetical order. presently the list of databases seems to be sorted kind of randomly (or at least, I haven't been able to discern how it's sorting them), see the attached screenshot for an example:

![image](https://user-images.githubusercontent.com/1442520/53200837-903f4700-35f0-11e9-949c-3f6b5f09872a.png)

**Comment by huyphams** [comment]
Sure, we will add it on the build 54 (next release). and also the https://github.com/TablePlus/TablePlus-Windows/issues/41
Thanks for the feedback!
