### ISSUE TITLE
Quick Look Editor Viewer bug

### ISSUE THREAD

**Issue by wilson-seixo** [TablePlus/TablePlus-Windows#400]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.5.8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
164 (happens since 162)

3. The steps to reproduce this issue:
- Have a column be of longtext data type (JSON)
- Have a row with a JSON object in that column
- Right click the cell in question and then open the "Quick Look Editor"
- Change any value in the "Viewer" mode and click anywhere in the list side of the Quick Look Editor
- The program crashes

JSON example:
```json
{
  "age": {
    "code": "age",
    "title": {
      "en": "Age",
      "pt": "Idade"
    },
    "placeholder": {
      "en": "Age",
      "pt": "Idade"
    },
    "description": {
      "en": "Age",
      "pt": "Idade"
    },
    "type": "number",
    "rules": "required|integer|between:1,150",
    "mandatory": true,
    "options": null,
    "ppi": true,
    "in_register": true
  }
}
```

**Comment by huyphams** [comment]
Hi @wilson-seixo please install this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thanks

**Comment by wilson-seixo** [comment]
> Hi @wilson-seixo please install this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
> Thanks

That solved it!
