### ISSUE TITLE
Move Tab to a New Window failure

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#402]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Any

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
164

3. The steps to reproduce this issue:
Have 2+ databases open in tabs
I had multiple tables and multiple SQL query windows open in data pane tabs in one of the database tabs
I wanted to move this tab to a separate window so I could move to a second screen
Right click the db tab and select "Move Tab to a New Window"
New window opens but the title of the window says: "my-database" is disconnected, press "Control Shift R" to reconnect...
All of the opened table and SQL query tabs are gone
Pressing "Control Shift R" does nothing
Only pressing "Control R" works and refreshes the connection but does not restore the table/SQL query tabs

**Comment by huyphams** [comment]
Hi @rwhirn please download this patch, it should fix your issue: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please let me know if you are still seeing the issue.

**Comment by rwhirn** [comment]
all fixed!
