### ISSUE TITLE
Alter Table from VARCHAR to INT failure

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#403]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.28

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
164

3. The steps to reproduce this issue:
go to STRUCTURE
change a VARCHAR field to any kind of INT
SAVE change
the command to ALTER TABLE still has CHARACTER SET and COLLATE in it which are invalid in an INTeger context:
`ALTER TABLE db.table CHANGE id id SMALLINT CHARACTER SET utf8 COLLATE utf8_general_ci NULL  COMMENT;`

**Comment by huyphams** [comment]
Thanks, we've fixed this issue! it will be included in the next update!
