### ISSUE TITLE
Error creating PRIMARY index?

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#404]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.28

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
164

3. The steps to reproduce this issue:
The whole "create index" routine is serious lacking. phpMyAdmin just has icons for "PRIMARY", "UNIQUE" and "INDEX" and you just click on one and it does the whole "create index" command for you. 
Anyway, trying to create a PRIMARY index on new table by entering in fields Name: PRIMARY Algorithm: BTREE Is_unique: TRUE Column: id creates the command:
`CREATE UNIQUE INDEX PRIMARY ON mydb.mytable (id) USING BTREE;`
which generates an error invalid index name PRIMARY. Entering the field name in the input field "Primary" does nothing, there is no way to save it. Not sure how to create a primary index.
phpMyAdmin generates the command:
`ALTER TABLE mytable ADD PRIMARY KEY(id);`

**Comment by huyphams** [comment]
Hi @rwhirn there is a primary field next to the table name field in the table structure, you can enter the column name in that field and hit Control + S, it will generate the correct query for primary index.

**Comment by rwhirn** [comment]
Sorry, I tried it a couple times yesterday and it never did anything. The field name didn't get the changed background that it had been recognized even. I think maybe it was because I wasn't "moving out" of the field. You have to move out first before it will recognize and then it will save.
