### ISSUE TITLE
connected with ssh but no data

### ISSUE THREAD

**Issue by Dontorpedo** [TablePlus/TablePlus-Windows#406]
1. Mysql

2. 4.0.2 (168)

3. i have created a new connection trough ssh, connection test ist ok

i can connect to mysql and chose one of my databases, but no data is viewed, it's stays black.. tried to choose another database and it opened in a new tab but also no data is viewed..

i have tried it on my premium version at home and also on my free version at the office

pls halp

**Comment by huyphams** [comment]
Could you show us  a screen shoot please?

**Comment by Dontorpedo** [comment]
![tbpl](https://user-images.githubusercontent.com/6850998/118941198-c4318000-b951-11eb-9e3a-2876da7d23a7.png)

**Comment by huyphams** [comment]
Please toggle the pane by clicking the button at the top right coner! Thanks!

**Comment by Dontorpedo** [comment]
![tbpl](https://user-images.githubusercontent.com/6850998/118941607-30ac7f00-b952-11eb-8061-bf486f203991.png)

**Comment by huyphams** [comment]
The button on the top right (not the top left 🤓)
