### ISSUE TITLE
Setting to disable count of rows

### ISSUE THREAD

**Issue by bladefist** [TablePlus/TablePlus-Windows#408]
Cockroach Driver:

When you open a table to view the data, you perform a count(*) in the background to show the row count at the bottom of the tab.  On massive tables, this count takes forever and causes high CPU on the database.

Can we have a setting to disable this?

**Comment by huyphams** [comment]
TablePlus will estimate rows before counting:

```
select reltuples::int8 as count from pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace where nspname= '<you_schema_name>' AND relname= '<you_table_name>' ;"
```

So if the estimated row < 500k, it will perform count (*). I guess it returned zero in your case?

**Comment by bladefist** [comment]
Returns null for cockroach.  I don't know for sure but I am guessing cockroach doesn't support those tables fully.

**Comment by huyphams** [comment]
Thanks, let me take a look at it.

**Comment by bladefist** [comment]
@huyphams any update? This is making the tool unusable for me and DDOSing my database lol

**Comment by huyphams** [comment]
Hi @bladefist please install this patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0 
Please let me know if you are still seeing the issue.

**Comment by bladefist** [comment]
Opened up a table with a few billion rows... It pulled 300 and stopped loading. Perfect!! Thanks.   Please make this a setting or merge into the main build.   CockroachDB is not good at count(*) on big tables.

**Comment by huyphams** [comment]
It's the officially released @bladefist we only disable count(*) if the estimated value is null or zero. Thanks for confimring
