### ISSUE TITLE
Feature Request: Scrollbar on table and database lists

### ISSUE THREAD

**Issue by bwat47** [TablePlus/TablePlus-Windows#41]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQL Server 2014

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
52

Presently the list of tables on the left side, and the list of databases (when you click Open Database) don't have visible scrollbars (so there's not any way to tell exactly where your scroll position is at in the list, or how much scrollable space is remaining)

Could there be scrollbars added in these two places?

**Comment by huyphams** [comment]
It's released in build 54. Thanks!
