### ISSUE TITLE
Newly added connection does not show (fresh install)

### ISSUE THREAD

**Issue by JBtje** [TablePlus/TablePlus-Windows#410]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0 (not relevant)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
168 (latest as of today)

3. The steps to reproduce this issue:
- I Installed TablePlus for the first time on a windows 10 computer
- Add a new configuration (MySQL, Use SSH Key)
- Test the connection (it succeeds)
- Press "Save"
- In the GUI, the connection does not show. I tried to add it 2 more times, both not showing.
- Close the application and **all 3** connections are now visible.

**Comment by huyphams** [comment]
Hi @JBtje thank you, we addressed the issue in this patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thank you for letting us know.
