### ISSUE TITLE
Feature - comment out syntax short cut and column names function

### ISSUE THREAD

**Issue by BenGaoSydney** [TablePlus/TablePlus-Windows#414]
Would you please add the feature that we could quickly comment out the syntax by "--"? This would greatly improve the efficiency of the coding and testing.

Also, would you please add a way to list our all the column names in of a table some that we don't have to type up every time, I understand there is a way to list all the column names in the table with - columns - select columns, but this is firstly not designed for getting all the column names, and secondly, it does not deal with the column names that has a lot of spaces in them.

Editing the syntax is also painful, as I cannot edit multiple lines together with ALT+ select.

**Comment by huyphams** [comment]
Hi @BenGaoSydney please do not remove the issue template questions. If you're using the latest release all those feature are supported.

1. Commend out: Control /
2. In SQL Editor, type the table name and then a dot, you will see the `*` in the auto-completion list. Select that character it will enter all the table column names for you.
3. You can hold the control + click toduplicate the caret. Or you can use the conotrl + D to duplicate caret by word and control + shift + G to duplicate caret by search all words.

All those shortcuts are similar to sublime text and vscode.
