### ISSUE TITLE
Windows version doesn't auto save files

### ISSUE THREAD

**Issue by DevZ1** [TablePlus/TablePlus-Windows#415]
Hi,

i'm using the windows version of tableplus but it doesn't remember my open files.
I updated to the latest version, but after that each time I add SQL to the open tabs and I close Tableplus, it doesn't remember my new SQL / changes. When I open again Tableplus it just remembers how it was before, thus never updating with new info.

Can someone fix this please ASAP. In previous version this was working perfectly. I'm using version 4.05

Thank you!

**Comment by son11592** [comment]
Hi @DevZ1, thank you for your feedback. But I could not reproduce this issue. When I instantly closed the application, the app still saved the current queries in the SQL Editor. Could you please give me an example (video or GIF)? It will help me much.

**Comment by DevZ1** [comment]
Sure check out this video :

https://www.screencast.com/t/0su1A8Uhh

I hope you can solve this cause it's really annoying.
Maybe I should clear my app cache or something or maybe delete all settings and start new? How can I do that?

**Comment by son11592** [comment]
Thank you so much for your support. I found the problem and am fixing it. The update patch will be sent to you soon.

**Comment by huyphams** [comment]
Hi @DevZ1 if you have a chance, please give this patch a try: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please let me know if you're still seeing the issue.

**Comment by DevZ1** [comment]
Thank you, it works now! :-)
