### ISSUE TITLE
Table Clone not working in MSSQL

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#416]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MS SQL Server 2014 (express)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
168

3. The steps to reproduce this issue:
right click any table and select clone. Click OK. Table name in left pane changes color to show it has changes. Press CTRL-s or click the "Commit your changes" icon and nothing happens. Click the "Preview SQL" icon and the Preview window pops up showing an empty box.

**Comment by huyphams** [comment]
Hi @rwhirn please try this hotpatch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please let me know if you still having the issue.

**Comment by rwhirn** [comment]
@huyphams Works perfect. Thanks.
