### ISSUE TITLE
Unable to access db via ssh

### ISSUE THREAD

**Issue by irshadelevision** [TablePlus/TablePlus-Windows#418]
1. postgresql, mysql
2. build no 170
3. connect to a db via ssh

Everything's where working properly until last update. after update its not working

output when I try connect

Exception
System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at TablePlus.Source.Service.SSH.StartSocket() in C:\Users\huy\Documents\tableplus-windows\TablePlus\TablePlus\Source\Service\SSH.cs:line 393

**Comment by huyphams** [comment]
Hi, it was Windows issue. Please restart the Windows it should resolve the issue

**Comment by irshadelevision** [comment]
> Hi, it was Windows issue. Please restart the Windows it should resolve the issue

Restarted the pc. 
Still it is not working

**Comment by huyphams** [comment]
It is not an issue of the 170 because we did not modify any code related to this. It seems it was there from the beginning.

TablePlus tried to find an available port to create an SSH tunneling, however, for some reason, Windows prohibits TablePlus from using that port. Please try to restart the PC or the app a few times and see how it goes.

I'm trying to improve the SSH code to make sure TablePlus can ignore those ports.

**Comment by irshadelevision** [comment]
When I checked for update. it was saying I haven't updated last 2

**Comment by huyphams** [comment]
It is the same with https://github.com/TablePlus/TablePlus-Windows/issues/183 and 
https://github.com/TablePlus/TablePlus-Windows/issues/267

**Comment by irshadelevision** [comment]
I tried restart. uninstalled the program and reinstalled. nothing seems working. I tried to access different db via ssh nothing seems working

same error.

**Comment by huyphams** [comment]
As I said, it was the Windows issue, please follow: https://stackoverflow.com/questions/10461257/an-attempt-was-made-to-access-a-socket-in-a-way-forbbiden-by-its-access-permissi

**Comment by irshadelevision** [comment]
I tried on Mac. it showing like the below
FATAL:  remaining connection slots are reserved for non-replication superuser connections

**Comment by huyphams** [comment]
Hi, please try this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thanks

**Comment by GenaroHV** [comment]
La solución fue ejecutar estos comandos en el PowerShell
net stop hns
net start hns
