### ISSUE TITLE
DELIMITER statement causes syntax error when importing an SQL Dump or using SQL Editor

### ISSUE THREAD

**Issue by Dragory** [TablePlus/TablePlus-Windows#419]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.5.8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
170

3. The steps to reproduce this issue:
    1. Open a database
    2. Menu -> File -> Import -> From SQL Dump...
    3. Select an .sql dump that contains DELIMITER statements, e.g. dumps that include triggers or functions (see example at the bottom of the issue)
    4. Click "Import"
    5. TablePlus shows a syntax error:
        ![Image of syntax error](https://user-images.githubusercontent.com/2606411/121673077-37459680-cab9-11eb-93a9-4f1504d16073.png)

4. Alternative steps to reproduce this issue:
    1. Open a database
    2. Open SQL Editor
    3. Paste in SQL with `DELIMITER` statements (see example at the bottom of the issue)
    4. Run the SQL
    5. TablePlus shows a syntax error:
        ![Image of syntax error](https://user-images.githubusercontent.com/2606411/121673572-b044ee00-cab9-11eb-8ad8-6417784b5656.png)

**Example SQL to reproduce the issue:**
```
DELIMITER //

CREATE TRIGGER `example_trigger`
BEFORE UPDATE ON `example_table`
FOR EACH ROW BEGIN
	IF (NEW.col = 1) THEN
		SET NEW.other_col = NULL;
	END IF;
END

//
```

For comparison, this same SQL file can be imported without errors using the `mysql` CLI tool or e.g. HeidiSQL.

**Comment by huyphams** [comment]
Hi @Dragory thanks for letting us know. In the meantime, please try to import use our backup/restore feature. We will fix this issue in the next release,

**Comment by Dragory** [comment]
Backup/Restore worked perfectly. Thank you for the incredibly fast reply!

**Comment by huyphams** [comment]
Hi @Dragory please try this hotpatch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

**Comment by Dragory** [comment]
Hey @huyphams, sorry for the delayed response. I tested the hotpatch and delimiters in the SQL Editor work now. I'm still getting the error with Import -> SQL Dump however.
