### ISSUE TITLE
Cant save password with special character

### ISSUE THREAD

**Issue by jagDanJu** [TablePlus/TablePlus-Windows#42]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 11.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
54

3. The steps to reproduce this issue:
I Can´t save an password on connections if there is an ">" or "<" in it.

**Comment by huyphams** [comment]
Thanks, @jagDanJu let check and fix it.

**Comment by huyphams** [comment]
Hi @jagDanJu I fixed it on the release 56. Thanks for the feedback.

**Comment by jagDanJu** [comment]
@huyphams Thank You!
