### ISSUE TITLE
Password Field Deleted or Invalid Key

### ISSUE THREAD

**Issue by nikkuang** [TablePlus/TablePlus-Windows#424]
All the set passwords are always getting deleted from time to time, including an invalid key error. 
I have to set all the configurations again, It seems that the configuration are being reset.

For password, the field is emptied,
For the ssh configuration, it displays the correct configuration and file path, but you need to reenter and select the ssh key again to make it work.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Mysql 8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 170

3. The steps to reproduce this issue: Random, after several days of opening and closing the app. Password field is emptied or the ssh key configuration becomes invalid, even if its correct.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by nikkuang** [comment]
It seems related to issue #396

**Comment by huyphams** [comment]
Hi @nikkuang I've made an attempt to fix this issue, if you have a chance, please download this hotpatch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please let me know if you're still seeing the issue!
