### ISSUE TITLE
White bar on second monitor

### ISSUE THREAD

**Issue by leag** [TablePlus/TablePlus-Windows#425]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
any
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
4.0.5 (168) - x64 windows
3. The steps to reproduce this issue:
Maximize window on left monitor, on windows 11, the monitor to the right will get a white line on is left border

**Comment by son11592** [comment]
Hi @leag, thank you for your feedback. Could you please give me some sample photos or videos? I might help me easy to find out the problem.

**Comment by huyphams** [comment]
Please install this patch if you have a chance, it should resolve the issue: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
