### ISSUE TITLE
Cassandra - When query ends with "ALLOW FILTERING", Limiting rows fails with an error

### ISSUE THREAD

**Issue by theadin** [TablePlus/TablePlus-Windows#429]
- Cassandra (3.11.4)
- TablePlus for windows version 4.2.1 (174).

If the query ends with "allow filtering" and the option to limit the number of rows is set, then you get an error "mismatched input 'LIMIT' expecting EOF" 

I recommend the app check if the query ends with "allow filtering" and if it does then to add the "LIMIT 100" to just prior that instead of to the end

![image](https://user-images.githubusercontent.com/46445608/126171091-7fa21d21-3c05-47d6-8f45-9fd18a29ff32.png)

Cheers

**Comment by son11592** [comment]
Hi @theadin, we've fixed it. The update will be sent to you soon. Thank you for your feedback.

**Comment by theadin** [comment]
Excellent. This is a great improvement
Cheers!

**Comment by huyphams** [comment]
@theadin You can download the hotpatch here: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please let us know if you still seeing the issue.

**Comment by theadin** [comment]
@huyphams I just tested it and it seems to work perfectly.
