### ISSUE TITLE
Feature Request: Backup / Restore / Sync

### ISSUE THREAD

**Issue by bladefist** [TablePlus/TablePlus-Windows#43]
Loving the tool! The backup / restore options have said coming soon for quite some time.  So wanted to ask about that, but expand that possibly.

I put TablePlus on my google drive, so that I can share my connections between my laptop and my desktop since it's a pain to keep those equal on two devices.  Unfortunately, app settings (connections, tab histories, etc) are stored in AppLocal, and while I've tried to back this up and restore it, it's not working well.

So could we have a way to specify the settings/store location? Your licensing is setup to support multiple seats, which I have, so being able to share the config between my seats would be awesome.

Thank you!

**Comment by bladefist** [comment]
@huyphams now that you guys moved to an installer and I can't run the project as a portable anymore, anyway we can sync our config/tabs?

**Comment by huyphams** [comment]
The TablePlus with an installer and the portable are the same, it shared the same configuration file which is located in the %AppData% folder. Just install it and you will see all the connection from the portable version.

**Comment by huyphams** [comment]
TablePlus backup/restore is not released on build 3.1.2, or you can download the patch here: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
