### ISSUE TITLE
Can connect but can't do backup

### ISSUE THREAD

**Issue by MohammadAbusaleh** [TablePlus/TablePlus-Windows#431]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 172

3. The steps to reproduce this issue: Not sure how

Noted: If the bug is related to data, please attach an example SQL data.

I am able to connect to my database, and when I click to backup it shows all the databases on the server but when I proceed with the backup I get this error.
```
System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at TablePlus.Source.Service.SSH.StartSocket() in C:\Users\huy\Documents\tableplus-windows\TablePlus\TablePlus\Source\Service\SSH.cs:line 393
```

**Comment by huyphams** [comment]
Hi, please try this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thanks
