### ISSUE TITLE
Filter by column name and selecting the column bug

### ISSUE THREAD

**Issue by mdurao** [TablePlus/TablePlus-Windows#433]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**

MySql

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**

Version 4.2.1 (174)

**3. The steps to reproduce this issue:**

Select a table;
View Structure;
Search a column in "Search column name..."
Double click the "column_name" to copy the column name.

Instead of showing the "filtered" column_name to by copied, it shows the original column_name that should be in that row and copies that value.

Example:

1. id
2. name
3. email

If you filter by email, it should show;

1. email

And if you double click on the column_name, it's supposed to copy "email" to the clipboard.
Instead, it shows "id" anc copies "id" to the clipboard.

**Comment by huyphams** [comment]
Hi @mdurao if you have a chance, please install this hotpatch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thanks

**Comment by mdurao** [comment]
Hi,

Just to report that the hotpatch fixes the issue!

Thank you,
