### ISSUE TITLE
Mongo connection crashing on windows

### ISSUE THREAD

**Issue by JonatasMA** [TablePlus/TablePlus-Windows#436]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MongoDB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 176

3. The steps to reproduce this issue:
Create a new connection with mongo, set the URL and try it

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @JonatasMA I believe that you forgot to enter the url protocol mongodb://  so the URL is invalid and the app crash. 
We've fixed it and auto add the mongodb:// if the user forgot to add it. You can download the hotpatch here: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Or you can enter the valid URL for example: mongodb://localhost:27017/test

**Comment by huyphams** [comment]
the first version have a trick requirements, it needs full url with protocol and database. The hotpatch improve it as it will set to default mongodb:// and test database if the user forget to enter it.
