### ISSUE TITLE
Driver Error with SQLite files, but the real problem is space caracters...

### ISSUE THREAD

**Issue by vbonnal** [TablePlus/TablePlus-Windows#438]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQLite (générated by Django 3.1.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
176

3. The steps to reproduce this issue:
- Create a new connection
- SQLite
- choose a SQLite file with a space caracters in the path...

Connection test for a file with a long path and with space caracters in the path
![image](https://user-images.githubusercontent.com/7264734/132065673-89de1da6-90d8-4a3f-a5a6-b0ee9cfb8f13.png)

Connection test for the same file without space caracters in the path
![image](https://user-images.githubusercontent.com/7264734/132065694-35b78a7b-1c7b-4cb1-a86d-80991cffce40.png)

**Comment by huyphams** [comment]
the spaces are not the problem, the problem is the special character `è` in your path.  I've fixed it, please install this hot patch if you have a chance: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thank you!
