### ISSUE TITLE
CSV Import not showing Auto Detect

### ISSUE THREAD

**Issue by dianadelloplane** [TablePlus/TablePlus-Windows#441]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 13.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
176

3. The steps to reproduce this issue:
I select Import > From CSV > select the file > then select Create new table > On the right hand side, under the files name, it is not showing the option to auto detect the columns data types. 
Wondering if I am missing something? Or is it already auto-detecting by default? 
![image](https://user-images.githubusercontent.com/90355895/132588742-75b1734f-cdbe-40bb-a14f-316bcf7ee8d8.png)

**Comment by son11592** [comment]
Hi @dianadelloplane, this feature has not been implemented in Windows version. But we will add it soon. Thank for you feedback.
