### ISSUE TITLE
Number of rows in the Table Data View does not match the total rows

### ISSUE THREAD

**Issue by mikeddig** [TablePlus/TablePlus-Windows#442]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 13.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 176

3. The steps to reproduce this issue:
Open a table and # of rows are displayed (e.g. 1-300 of ~9479 rows).
If you run a SELECT * for that table, the total number for rows are 7462. 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @mikeddig that value is the estimated value ~9479. You can enable exactly count in TablePlus settings (however, it will cost performance if the table has million rows).
![IMAGE 2021-09-09 07:58:21](https://user-images.githubusercontent.com/3654622/132604904-20953079-7549-482d-9a72-926af5e3dd45.jpg)

**Comment by mikeddig** [comment]
Thanks! @huyphams

**Comment by huyphams** [comment]
But the weird thing is: if the estimated row count is ~9479, it is less than 500k, that means TablePlus will perform count (*) (but it didn't). So I think it's a bug, let us take a look at it.

**Comment by mikeddig** [comment]
Mine was 0. But after changing to 500k it returned the exact row count.
![image](https://user-images.githubusercontent.com/90362165/132605973-e0231641-4e71-4105-9b9b-224e79ff33c3.png)

**Comment by huyphams** [comment]
Ah ok, so did you change it? or it's zero by default?

**Comment by mikeddig** [comment]
It was 0 by default. The weird thing is that before changing the Estimate count, table view returns the correct row count.

**Comment by huyphams** [comment]
Because that is the threshold. So basically, TablePlus will estimate the total rows. If the value < threshold, TablePlus knows that it can safely count all the rows without hitting the performance.

**Comment by mikeddig** [comment]
Thanks again! 👍
