### ISSUE TITLE
Small UX bug for Beautify button overlay

### ISSUE THREAD

**Issue by ericrabiner** [TablePlus/TablePlus-Windows#444]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Not relevant 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 176

3. The steps to reproduce this issue:

The Beautify hot command overlay should be Control + I.

Beautify:
![image](https://user-images.githubusercontent.com/44846748/132860225-2bf02470-6369-42d1-a35e-0970256a0550.png)

Uglify:
![image](https://user-images.githubusercontent.com/44846748/132860159-0d42074c-c44a-4b2e-a06e-871dea49c434.png)

**Comment by son11592** [comment]
Hi @ericrabiner, thank you for your support. I will fix it now.

**Comment by huyphams** [comment]
We just addressed it. Thanks
