### ISSUE TITLE
Import .txt

### ISSUE THREAD

**Issue by dianadelloplane** [TablePlus/TablePlus-Windows#445]
Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 13.4

Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
176

The steps to reproduce this issue:
I select Import > From CSV > Can I select to import .txt files? Or is that only for macOS at the moment?
Would it work on Linux?

Thank you!

**Comment by huyphams** [comment]
What is the format of the txt file @dianadelloplane ?

**Comment by dianadelloplane** [comment]
Unix LF 
UTF-8

**Comment by huyphams** [comment]
is it a CSV file or a SQL file?

**Comment by dianadelloplane** [comment]
Csv

**Comment by huyphams** [comment]
I think you should rename the file to .csv, accepting .txt for CSV would case more troubles because not all txt files are CSV
