### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by wuqiyin** [TablePlus/TablePlus-Windows#448]
![image](https://user-images.githubusercontent.com/26370779/134444433-7e18084c-f4be-42f9-9167-fd6d7597e7e8.png)
.

**Comment by huyphams** [comment]
HI @wuqiyin  if you have a chance, please download this patch, it should resolve the issue: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
