### ISSUE TITLE
Same issue as on https://github.com/TablePlus/TablePlus-Windows/issues/116

### ISSUE THREAD

**Issue by denache19** [TablePlus/TablePlus-Windows#449]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Cassandra

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
4.5.2 (178)

3. The steps to reproduce this issue:
Connect to a Cassandra 2.X.X (ex 2.2.12)keyspace and you'll notice that only 1 table is shown.

Noted: If the bug is related to data, please attach an example SQL data.
You can review/use the original bug data.

**Comment by huyphams** [comment]
Hi @denache19 there are many Cassandra version, your information is not enough for us to reproduce the issue

**Comment by denache19** [comment]
Cassandra 2.2.12

**Comment by denache19** [comment]
Also the previous patch you're provided is not available anymore.

**Comment by denache19** [comment]
For Cassandra 3 it works fine, therefore I consider is the same issue as on https://github.com/TablePlus/TablePlus-Windows/issues/116 and I would like the fix(patch).
Many thanks.

**Comment by huyphams** [comment]
HI @denache19 if you have a chance, please download this patch, it should resolve the issue: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

**Comment by denache19** [comment]
I confirm it's fixed.
Thanks.
