### ISSUE TITLE
Missing 'dialog' plugin on Windows

### ISSUE THREAD

**Issue by huyphams** [TablePlus/TablePlus-Windows#450]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Windows:  Version 4.5.0 (178) - x64

3. The steps to reproduce this issue:
Trying to connect gives a popup:
"Authentication plugin 'dialog' cannot be loaded: The specified module cannot be found."

Moved from https://github.com/TablePlus/TablePlus/issues/2512

**Comment by quinyx-tjeerd** [comment]
@huyphams commented on the original issue (in the wrong repo):
> If you have a chance, please install this patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0 it should fix the issue.
Thanks

I've tested the patch and it works like a charm , thanks a lot!

**Comment by huyphams** [comment]
I commented on that issue because i think you could miss it as you didn't follow this issue (but you did)
