### ISSUE TITLE
Unnecessary border around window when maximized

### ISSUE THREAD

**Issue by KBulmer** [TablePlus/TablePlus-Windows#451]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0.26

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
180. I think it started in 178.

3. The steps to reproduce this issue:
Maximize the window. You now have to aim at the "X" symbol to close the window rather than just flicking the cursor up there and clicking. There's a similar issue with the scroll bar not being available from the right-most column of pixels.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
HI @KBulmer  if you have a chance, please download this patch, it should resolve the issue: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
