### ISSUE TITLE
Application stays dim after closing the Quick Look Editor

### ISSUE THREAD

**Issue by jazerix** [TablePlus/TablePlus-Windows#452]
Opening the `Quick Look Editor` dims the background, however, when the window closes the application stays dim.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Windows - build 180

3. The steps to reproduce this issue:

    1. Open a connection to a MySQL database
    2. Select a row and a column and open the `Quick Look Editor`
    3. Close the quick look editor, the application is now darker than before

**Comment by huyphams** [comment]
Hi @jazerix thanks for letting me know, please install this patch, it should fix the issue: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
