### ISSUE TITLE
Column Label Displays Incorrectly When Sorted 

### ISSUE THREAD

**Issue by bussardrobbie** [TablePlus/TablePlus-Windows#456]
Good afternoon,
In TablePlus for Windows, column labels may display incorrectly when sorted. Operating system is Windows 11 Enterprise, build 22000.194. It is unknown if this is based upon specific characters being in the label for the column; however, I noted in testing multiple fields in my DB that in the label, the only character affected was _**the first underscore in each column name that was eliminated**_.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL, v8.0.23
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 4.6.4, build 180.
3. The steps to reproduce this issue:
- Open a MySQL connection.
- Click on the label of a column (or the body of the column head) to sort the column.
- The first underscore in the column name will be removed in the label for the column.

Priority: Low, as workarounds exist to otherwise check field names via CLI or other methods. An argument could be made for a "medium" priority as, if a secondary field name source is not checked, the field name could be incorrectly copied into code or queries that are written to modify the data in the fields, causing errors.

Please see attached video for visual demonstration of issue. Note that, only when sorted ascending or descending, the column label for "created_by_app_name" is transmuted into "createdby_app_name" by TablePlus, even though it is seen correctly in other menus.

https://user-images.githubusercontent.com/65207496/136853498-b30553fe-7c0a-4ae5-85e9-9d478ce0cc7b.mp4

Thank you!
-Robbie

**Comment by son11592** [comment]
Hi @bussardrobbie, sorry for late response. We had reproduce this issue and found the problem. The update will be sent to you soon. Thank you for your feedback.

**Comment by huyphams** [comment]
If you have a chance, you can download the hotpatch here: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
