### ISSUE TITLE
Locks up on open before connections are loaded

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#457]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
n/a

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
180

3. The steps to reproduce this issue:
Every time I open Tableplus (which could be as many as 5 or 6 times a day), the program locks up while loading connections. I then have to kill the task in Task Manager and start it again. Then it always works on that second try. Any ideas?

I have 11 connections saved in 3 groups.

**Comment by huyphams** [comment]
Hi @rwhirn I'm sorry because of the issue. It's the Microsoft framework bug and we've fixed it in this patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please let me know if you are still seeing it!
