### ISSUE TITLE
The title bar is white on light grey. I can't see the menu options.

### ISSUE THREAD

**Issue by davepreston** [TablePlus/TablePlus-Windows#459]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL (not sure how to see version)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 4.6.15 (180) - x64

3. The steps to reproduce this issue:
  The initial loading screen looks fine (all dark), but after choosing a connection the title bar changes to light (white text on light grey bar). Everything below the title bar seems fine (and changes with themes), but the title bar is unreadable).

![image](https://user-images.githubusercontent.com/334989/137393477-a73825b2-3bf8-4af9-8093-9633e01de91a.png)

**Comment by huyphams** [comment]
Hi @davepreston please click on the title bar and change the color. I'm sorry for the issue.

**Comment by davepreston** [comment]
@huyphams thanks for the help figuring it out.
I imported my connections from a co-worker (he uses a mac if it makes a difference). 
All the connections I imported from him came across with white/white title bars. After your input I was able to click around randomly on the title bar until I happened to hit the section that changes the color.
Thanks for your help.
