### ISSUE TITLE
Open anything does not work for goto database anymore

### ISSUE THREAD

**Issue by YoranBosman** [TablePlus/TablePlus-Windows#460]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**mysql**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**4.6.4**

3. The steps to reproduce this issue:
**press ctrl+p which opens the goto anything dialog
since 4.6.4 this only works when a database is selected and shows the tables,
but in previous versions i could also select the database first with it.**

**Comment by huyphams** [comment]
Duplicate of https://github.com/TablePlus/TablePlus-Windows/issues/458
We've fixed it here: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thank you for letting me know!
