### ISSUE TITLE
I can't see my top menu bar - it appears the font is white on white background.

### ISSUE THREAD

**Issue by moot33** [TablePlus/TablePlus-Windows#467]
### Please answer the questions below, it helps us to track the issue.
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
![image](https://user-images.githubusercontent.com/93921127/140881542-0287ba9e-4f0b-4bc6-81a2-66a498b3f645.png)
v4.8.0 (182)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
v4.8.0 (182)

3. The steps to reproduce this issue:
I can't see my top menu bar - it appears the font is white on white background.

![image](https://user-images.githubusercontent.com/93921127/140881436-9bb0b99f-37d7-4bad-9fa1-40631892e6eb.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @moot33 i think you imported the connections somewhere and it has a white status color. You can click the header and change the status color.
Thanks
