### ISSUE TITLE
Closed window holds database connection

### ISSUE THREAD

**Issue by dsincl12** [TablePlus/TablePlus-Windows#471]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 182

3. The steps to reproduce this issue:
  1. Open a database
  2. Browse some tables
  3. Close window
  4. Try to drop database from command line, error about database still in use
  5. Close TablePlus completely and retry, database dropped without error

**Comment by huyphams** [comment]
Hi @dsincl12 if you have a chance, please install this patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

Thanks

**Comment by dsincl12** [comment]
Worked perfectly. Good job! :)
