### ISSUE TITLE
The actions Commit,Preview,Discard should be somewhere that is easy to click

### ISSUE THREAD

**Issue by ajcastro** [TablePlus/TablePlus-Windows#476]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 182

3. The steps to reproduce this issue: N/A

Currently, for me to commit or discard changes, 
(1) I need to click Menu, 
(2) then click Edit
(3) then now I can click Commit,Preview or Discard.
So there are three steps or clicks.

I suggest it should be somewhere that is less clicks, I think 2 clicks is fine.
For example what if we put those beside the `+ Row` button,  
a button group for those 3 actions like the screenshot below... 

![image](https://user-images.githubusercontent.com/4918318/143802250-4bd903aa-39fa-46bd-96d3-1daa6ebef5c5.png)

Not sure if this is the best design but the point is to make it easier to access those buttons. 
Also it might be good if there is a shortcut for those. 
It seems the shortcut for Commit is Ctrl+S, but I didn't discover yet for the Preview and Discard.
Thanks a lot!

**Comment by son11592** [comment]
Hi @ajcastro, thank you for your feedback. We have already added the shortcut for those actions.
- Commit: `Ctrl S`
- Discard: `Ctrl Shift Delete` 
- Preview: `Ctrl P` 
Further information, if you forget it, you can hover on those buttons to see their tooltips, which contain the shortcut description.

![image](https://user-images.githubusercontent.com/4739616/143804606-56ad42e4-14b9-47c2-8762-2aeb57befc19.png)

**Comment by ajcastro** [comment]
Oh I see... Thanks for that. 
I didn't notice those buttons before. It was already there, that's what I really wanted.
