### ISSUE TITLE
[FEATURE REQUEST] There is no option to disable automatic saving of queries in the Windows version.

### ISSUE THREAD

**Issue by pastansberry-clgx** [TablePlus/TablePlus-Windows#478]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **MySQL v5.7**
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **Version 4.8.0 (182) - x64**
3. The steps to reproduce this issue: _This is a feature request. There needs to be an option to disable automatic saving of query changes. This feature exists in the MacOS version, but is missing from Windows._

**Comment by son11592** [comment]
Hi @pastansberry-clgx, thank you for your feedback. This feature has already implemented in Windows version. You can use it in the settings menu at the right-bottom of the `Queries` tab
![image](https://user-images.githubusercontent.com/4739616/144529020-505daca1-ea4c-41fd-9d05-85544746765d.png)

In the next version, you will see in the Preferences and we will add some improvements for it.

**Comment by huyphams** [comment]
Hi, If you have a chance, you can install our prerelease build which support disable auto save queries: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

Please let me know if you have any questions.

**Comment by pastansberry-clgx** [comment]
Thank you.

I was able to install the pre-release build mentioned and disable auto-saving of queries.
