### ISSUE TITLE
Cannot Sort Tables By ID

### ISSUE THREAD

**Issue by themrflibble** [TablePlus/TablePlus-Windows#479]
Before this release, I could click `id` column, and it would sort by ASC, then DESC. Now, the ASC arrow appears and then immediately disappears and no sorting occurs.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

I'm using Build 184 for Windows 10, MariaDB 5.5.68

**Comment by son11592** [comment]
Hi @themrflibble, thanks for your feedback. But I could not reproduce this issue. Could you please attach some videos or gif files? I might help us easy to find out the problem.

**Comment by KBulmer** [comment]
Having the same issue since build 184. It happens with most tables but not all. Sorting works, but the arrow always disappears, which means ASC is always the next option.

**Comment by themrflibble** [comment]
Here you can see how the id (and any other column that is not videod does the same) cannot be sorted.
The SQL statement works though.
 
https://user-images.githubusercontent.com/8282596/144908018-d128e942-a2c1-4103-8872-9317f62aebef.mp4

**Comment by jenky** [comment]
Same issue using build 184

**Comment by huyphams** [comment]
Hi guys, if you have a chance, please install this hot patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thanks

**Comment by themrflibble** [comment]
> Hi guys, if you have a chance, please install this hot patch and see how it goes: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0 Thanks

Excellent. This has fixed the issue for me!
