### ISSUE TITLE
Cannot view SQLite db stored on WSL file system

### ISSUE THREAD

**Issue by cparkerx** [TablePlus/TablePlus-Windows#483]
1. Which driver are you using and version of it: SQLite 3.36.0 

2. Which TablePlus build number are you using: Build 182

3. The steps to reproduce this issue: Attempt to open a SQLite db that is stored on the WSL file system from the TablePlus Windows application. The file will "open" in TablePlus, but no tables or data are shown.

Details:

I've noticed in testing that I can use TablePlus-Linux-alpha to open the SQLite file in WSL without any issues. Also, I can copy and paste the SQLite db file from the WSL file system to the Windows file system, using Windows file explorer, and then open the SQLite db in TablePlus-Windows without any issues.

**Comment by ajitid** [comment]
Can be closed in favor of https://github.com/TablePlus/TablePlus-Windows/issues/225
