### ISSUE TITLE
TablePlus doesn't launch on Windows

### ISSUE THREAD

**Issue by daubac402** [TablePlus/TablePlus-Windows#489]
I guess that my network is behind Fortigate firewall (and also currently enabling: fortigate ssl inspection), so maybe the the **check for update** process was failed.
This failed doesn't give any error message or something, just stop the TablePlus.exe process immediately.

### Detail info
1. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Latest on 2022/01/04
2. The steps to reproduce this issue:
Just start TablePlus, It suddenly terminates or remains and only using 32KB RAM Memory

**Comment by daubac402** [comment]
Seems it crashed then my Windows automatically calls WerFault.exe to send an error report to Microsoft (at: onedsblobprdwus15.westus.cloudapp.azure.com)

**Comment by Rubrasum** [comment]
I got the same problem. Did you ever get it figured out?

**Comment by daubac402** [comment]
@Rubrasum, No. The root cause was still unclear.

**Comment by huyphams** [comment]
Hi, we're sorry for the issue, please re-download the build here and try again: https://tableplus.com/release/windows/tableplus_latest
