### ISSUE TITLE
Charset errors with UTF-8

### ISSUE THREAD

**Issue by Dragony** [TablePlus/TablePlus-Windows#5]
1. Which driver are you using and version of it: **MySQL**

2. Which TablePlus build number are you using: **Build 4**

3. The steps to reproduce this issue:
- Open a Table containing rows with UTF-8 Data and specials characters. The table is defined as a "utf8_unicode_ci" table
![image](https://user-images.githubusercontent.com/465941/45450990-094d8080-b6da-11e8-8f95-6281283889c4.png)

Noted: If the bug is related to data, please attach an example SQL data.

Example data: Special (non-Ascii) characters like äöüÄÖÜ

**Comment by huyphams** [comment]
Thanks, I just fixed it.
