### ISSUE TITLE
Query time-out

### ISSUE THREAD

**Issue by kristiejfocht** [TablePlus/TablePlus-Windows#50]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL version 8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 1.0 (58)

3. The steps to reproduce this issue: Execute one of our basic queries

Noted: If the bug is related to data, please attach an example SQL data.

Is there any way to extend how long TablePlus gives a query to execute? After 120 seconds my queries are stopping with the message "Query execution was interrupted, maximum statement execution time exceeded".

**Comment by huyphams** [comment]
I just released the build 60, which increased the query timeout!
