### ISSUE TITLE
Window title bar colours are set to invisible text - Windows 11

### ISSUE THREAD

**Issue by jtromp** [TablePlus/TablePlus-Windows#500]
### Please answer the questions below, it helps us to track the issue.
The font colour is very light and the background colour is almost the same. Only when hovering the text is (barely) visible.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Windows 11 Pro (latest version)
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 186
3. The steps to reproduce this issue:
Open any database connection in Windows 11
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @jtromp you can click the title bar and change it. I think you have imported those connections from
MacOS?
