### ISSUE TITLE
Windows version of TablePlus does not support tab preview, contrary to Mac version

### ISSUE THREAD

**Issue by trebi** [TablePlus/TablePlus-Windows#502]
I am happy paying customer of TablePlus on Mac. However, now when I tried to use the version for Windows, I noticed that it has, contrary to the Mac version, a no-go usability flaw that makes the Windows version of TablePlus basically unusable in my opinion.  

On Mac version, when you click on the table name, it would open something like "tab preview", where the table name is written in _italics_. If you then click on the another table, this previous "tab preview" will get replaced with the new one. Only when you double-click, the tab would stay "pinned". This behavior allows you to quickly preview bunch of tables and independently decide which ones you want to have open as tabs.  

However, this "tab preview" feature does not exist in Windows version of TablePlus. A single click would always open a new, pinned tab. Moreover, If you are using free version, TablePlus would show you "Free Trial limit error" after just 3 clicks. Super annoying.

I found that this issue was already reported in 2018, but I decided to create a new one as I am genuinely shocked that this was still not addressed, as this is a major usability flaw and deal-braker from my perspective.

Duplicates:
- https://github.com/TablePlus/TablePlus/issues/397
- https://github.com/TablePlus/TablePlus-Windows/issues/165

**Comment by bewareilive** [comment]
yes,I haven't seen it on other,
And without this：
https://docs.tableplus.com/preferences/general/connections#keep-connection-alive
don't know why

**Comment by mtaki14** [comment]
Seems like it's been implemented in the latest version (4.8.8)

**Comment by huyphams** [comment]
The "Only keep the modified tabs" has been implemented 💯

**Comment by trebi** [comment]
Awesome, thanks!
