### ISSUE TITLE
Cancel Query

### ISSUE THREAD

**Issue by bladefist** [TablePlus/TablePlus-Windows#51]
Accidentally did a select * without a limit on a large table and I couldn't find a way to cancel the query. 

Thanks!

**Comment by rizalferdian** [comment]
Same thing happened to me

**Comment by bladefist** [comment]
@huyphams this was closed but it still doesn't exist for cockroach.

**Comment by son11592** [comment]
@bladefist you can use this button to cancel any executing query.

![image](https://user-images.githubusercontent.com/4739616/100626496-794a8e80-3358-11eb-9988-748f5bdf2bbb.png)

**Comment by bladefist** [comment]
@son11592 this button doesn't appear on cockroach queries.

**Comment by son11592** [comment]
Hi @bladefist! Unfortunately, this feature is not available on Cockroach database.

**Comment by bladefist** [comment]
Like to re-open this, this is still a big issue.  This feature CAN be available on Cockroach.
