### ISSUE TITLE
[Feature Request] show geography type on column postgis 

### ISSUE THREAD

**Issue by thaisanly** [TablePlus/TablePlus-Windows#511]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it : PostgreSQL 12

2. Which TablePlus build number are you using: build 190

3. The steps to reproduce this issue:

![image](https://user-images.githubusercontent.com/5434401/161466655-65af7b00-a34b-40b2-82b9-f91eb6f7cb12.png)

4. Request show information

![image](https://user-images.githubusercontent.com/5434401/161466768-b62ecf89-0a06-4caf-bf9d-d83a3c021dbf.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by son11592** [comment]
Hi @thaisanly, thank you for your feedback. The next build will contain this improvement.
