### ISSUE TITLE
Sequence and Triggers not visible

### ISSUE THREAD

**Issue by ankitgoel888** [TablePlus/TablePlus-Windows#513]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by ranggakd** [comment]
please explain or close this unclear issue
I have the same issue with the existing triggers cannot be shown in the Windows version of TablePlus

**Comment by ankitgoel888** [comment]
Tableplus doesnt show triggers
