### ISSUE TITLE
FreeVersion

### ISSUE THREAD

**Issue by davidjeba** [TablePlus/TablePlus-Windows#514]
It would be great if you can provide a Free forever version with max 10 Remote databases

1 postgress
1 mysql
1 amazon redshift
1 sql server
1 sqlite
1 Redis
1 Cassandra
1 Cockroach
1 Mongo
1 Mariadb
Unlimited Local Databases

so every database users can try and experience this awesome tool

**Comment by huyphams** [comment]
Actually it does
