### ISSUE TITLE
Replace All - Only replaces 1 occurence on first click

### ISSUE THREAD

**Issue by JustinAddams** [TablePlus/TablePlus-Windows#52]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 10.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 60

3. The steps to reproduce this issue:

Write any old SQL query
Highlight a portion to replace
Press Ctrl + H to open Find and Replace UI
Entire something new in the Replace field
Press Replace all button
Only 1 occurence will be replaced
Press Replace all button again
Remaining occurences will be replaced.

**Comment by huyphams** [comment]
Please check out the build 85, it should be fixed.
