### ISSUE TITLE
Clickhouse connection failed

### ISSUE THREAD

**Issue by bewareilive** [TablePlus/TablePlus-Windows#521]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Clickhouse  21.8.4.51
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
192
3. The steps to reproduce this issue:
Clickhouse connection timeout,less than 1 second after clicking it shows
Modified the default http port 8123 and tcp port 9000
Cluster environment

**Comment by huyphams** [comment]
Hi @bewareilive it is not possible to reproduce the issue with that info. Could you show me the screenshot of the connection form. Have you tried to connect with any other clients?

**Comment by bewareilive** [comment]
![table1](https://user-images.githubusercontent.com/26020170/168528009-524a7ead-7a50-4aee-a014-4e70ad3c14fa.gif)
![table2](https://user-images.githubusercontent.com/26020170/168528075-e155eff3-f9aa-487d-af57-01128e37808e.gif)



> Hi @bewareilive it is not possible to reproduce the issue with that info. Could you show me the screenshot of the connection form. Have you tried to connect with any other clients?

**Comment by huyphams** [comment]
I think you are using the http port instead of the tcp port (http vs native protocol).
TablePlus only support native protocol.

**Comment by bewareilive** [comment]
> I think you are using the http port instead of the tcp port (http vs native protocol). TablePlus only supports native protocol.

But using 9000 port also failed

**Comment by huyphams** [comment]
I don't think that you can connect it directly from the outside (except the server port is exposed and accept connection from any public IP), maybe you should use the Over SSH. Please ask your system admin for advice (ask for the SSH info).

**Comment by bewareilive** [comment]
> I don't think that you can connect it directly from the outside (except the server port is exposed and accept connection from any public IP), maybe you should use the Over SSH. Please ask your system admin for advice (ask for the SSH info).

Thank you for your answer
Connected successfully,but I'm so sad that I can't use it.
The server in my work environment needs to be connected through a fortress machine and does not connect using ssh.I successfully connected using a virtual machine.
