### ISSUE TITLE
Invalid Private Key 

### ISSUE THREAD

**Issue by JimmyTayAC** [TablePlus/TablePlus-Windows#525]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.36
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build194
3. The steps to reproduce this issue:
    1. Connect to VPN.
    2. Provide the credential for MySQL connection
    3. Click Over SSH
    4. Provide the credential of the server
    5. Use SSH key, private key. The ssh key was able to use to ssh into the server, but keep prompt invalid private key while use to 
    open the MySQL db 

![image](https://user-images.githubusercontent.com/106950017/172108414-a344df42-750f-4e04-a84d-7f9bd89b2b47.png)

**Comment by huyphams** [comment]
Duplicate https://github.com/TablePlus/TablePlus-Windows/issues/302
