### ISSUE TITLE
Keyboard shortcut to search in left "Item List Sidebar"

### ISSUE THREAD

**Issue by Mutahhar** [TablePlus/TablePlus-Windows#527]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

> MySQL 8.0.28

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

> 4.9.0 (190)

4. The steps to reproduce this issue:

- Is there any keyboard shortcut to search in the left "Item List Sidebar"? If not please add this to the feature request.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by Mutahhar** [comment]
I want a shortcut to mover cursor here to search in this area👇

![image](https://user-images.githubusercontent.com/11645672/174545171-a6065c07-16e5-4298-a99b-3351f53bb90c.png)

**Comment by huyphams** [comment]
It should be control shift F

**Comment by Mutahhar** [comment]
@huyphams already tried control shift F. It is not working on my side.

**Comment by huyphams** [comment]
Please upgrade it to the latest release first

**Comment by Mutahhar** [comment]
It is working in the latest version... Thanks @huyphams
