### ISSUE TITLE
MySQL Error Changing VARCHAR Length in Structure

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#529]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.33-log

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 196

3. The steps to reproduce this issue:
Changing field length on two fields of VARCHAR(25) to VARCHAR(30)
Get the following ERROR:
>You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'COMMENT '', CHANGE ColorName2 ColorName2 varchar(30) CHARACTER S' at line 2

This is the statement its trying to send:
```
ALTER TABLE Colors
CHANGE ColorName ColorName varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT  COMMENT '',
CHANGE ColorName2 ColorName2 varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT  COMMENT '';
```
If I take out the "DEFAULT" it works.

**Comment by son11592** [comment]
Hi @rwhirn, thank you for you feedback. I have found the root cause of this issue. The next update will be sent to you soon.

**Comment by huyphams** [comment]
Hi @ZiiMs if you have a chance, please try this hot patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please let me know if you're still seeing the issue.

**Comment by rwhirn** [comment]
@huyphams All good. Thank you.
