### ISSUE TITLE
Removal of pg_temp_99  schemas, please!!

### ISSUE THREAD

**Issue by mdjukic** [TablePlus/TablePlus-Windows#530]
### Please answer the questions below, it helps us to track the issue.

1. Redshift 1.0.39255

2. TLSv1.2

3. Drop down box to select  db Schema. . . . . the pg_temp_1. . . .pg_temp_99 schemas are showing.   Could you possibly remove these, as they are a hindrance, and completely useless when using AWS Redshift.   Thanks.

**Comment by huyphams** [comment]
Hi @mdjukic have you tried this setting?
<img width="812" alt="Screen Shot 2022-06-29 at 10 06 18 PM" src="https://user-images.githubusercontent.com/3654622/176470814-31183d20-d799-4ed5-a933-3cf981298441.png">

**Comment by huyphams** [comment]
It looks like Redshift does not have this feature. In the meantime, please use the PostgreSQL driver for redshift, it should hide those schemas.

**Comment by mdjukic** [comment]
Henry....hi!!   I'm not sure that is possible, as Redshift, although PostgreSQL, does only come in in V8....quite old.   
     
    
      Better solution would be to filter out within TablePlus, as I do not have this issue when using othe SQL clients.  
     
     
      
     
    
    
     
      
      
        Marko Djukic 
       
      
      
       
      
     
    
    
    
     
     
       On Wednesday, Jun 29, 2022 at 4:09 pm, Henry Pham ***@***.***> wrote: 
       
      
      
       
      It looks like Redshift does not have this feature. In the meantime, please use the PostgreSQL driver for redshift, it should hide those schemas. 
      —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> 
      ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/TablePlus/TablePlus-Windows/issues/530#issuecomment-1170101806","url": "https://github.com/TablePlus/TablePlus-Windows/issues/530#issuecomment-1170101806","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]

**Comment by huyphams** [comment]
Hi @ZiiMs if you have a chance, please try this hot patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please let me know if you're still seeing the issue.
