### ISSUE TITLE
SQL error by using the GUI for setting a text-Column default EMPTY

### ISSUE THREAD

**Issue by Passwort1234** [TablePlus/TablePlus-Windows#532]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.6.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 196

3. The steps to reproduce this issue:
- Add via GUI a new Column defined as text and set the column_default as EMPTY
- After saving, the Column-Default is set to NULL instead of EMTPY (confusing but not the actual bug)
- Set the column_default to EMPTY via GUI again and save -> now you'll get an Error in your SQL Syntax
- The SQL-Statement which TablePlus generates looks like this: 

`ALTER TABLE 'test'.'testtable'
CHANGE 'test' 'test' text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT  COMMENT '';`

- To avoid the Error you have to set '' after the DEFAULT

`ALTER TABLE 'test'.'testtable'
CHANGE 'test' 'test' text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '';`

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @ZiiMs if you have a chance, please try this hot patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please let me know if you're still seeing the issue.
