### ISSUE TITLE
Crashing to desktop when attempting to view certain table in cockroachdb.

### ISSUE THREAD

**Issue by ZiiMs** [TablePlus/TablePlus-Windows#534]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):CockroachDB CCL v21.2.12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):Build 196

3. The steps to reproduce this issue: Create cockroachdb following this schema and it will crash when you attempt to view it.

Noted: If the bug is related to data, please attach an example SQL data.:

```sql

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'USER', 'CLIENT');

-- CreateTable
CREATE TABLE "User" (
    "id" STRING NOT NULL,
    "name" STRING,
    "email" STRING,
    "emailVerified" TIMESTAMP(3),
    "image" STRING,
    "role" "Role" NOT NULL DEFAULT 'CLIENT',

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);
```

**Comment by son11592** [comment]
Hi @ZiiMs, thank you for your feedback. I found that problem and fixed it. The update will be sent to you soon.
