### ISSUE TITLE
Feature Request: After EXPORT Option to Open File or Open Containing Folder

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#538]
Every time I export a CSV, what I have to do is click the "Export" button again, click the "Export" button in the popup dialog to get the "Save As..." file explorer dialog at the location where I previously saved the export then I right click on the file and do "Open" and then it opens in Excel, then I go back to TablePlus to click "Cancel" on the "Save As..." screen and then click "Close" on the Export" dialog. 

A lot of steps just to open the file I want. Most programs do like browsers and after generating a file allow you to "Open" the file (via its default program) or "Open the containing folder" where you can then double click the file to open it.

**Comment by huyphams** [comment]
Hi @rwhirn if you have a chance, please download this patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
TablePlus now will show an option to open containing folder.

**Comment by rwhirn** [comment]
Sweet! Thank you!
