### ISSUE TITLE
Connection Lost Error opens multiple times

### ISSUE THREAD

**Issue by Havrin** [TablePlus/TablePlus-Windows#540]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
4.9.12 (200)

3. The steps to reproduce this issue:

- open Connection to DB
- open several tabs of tables
- disconnect from internet/vpn
- mulitple errors pop up (probably one error for one open tab)

Expected:
only one error opens per connection

![table-plus](https://user-images.githubusercontent.com/8169275/182368555-37066427-e042-4956-af19-08d953580a55.png)

**Comment by huyphams** [comment]
Hi, please update TablePlus to the latest release. Please let me know if you are seeing the issue.

**Comment by Havrin** [comment]
hi, yes it still happens but the windows are not overlapping anymore. One window opens as seen in the screenshot and if I click ok, the next one opens.
I currently have:
- 1 connection with 6 tabs open
- disconnect from vpn to be able to access the database
- press either
  - CTRL + SHIFT + R -> first error "Driver error cant connect to MySQL Server on XXX", after that one errors pop up everytime I press ok with "Connection is disconnected, press Ctrl shift R to reconnect" and that for a total of 9 times
  - CTRL + R -> first error "Driver error cant connect to MySQL Server on XXX", after that one errors pop up everytime I press ok with "Connection is disconnected, press Ctrl shift R to reconnect" and that for a total of 9 times
  - the refresh button in the top bar -> no error pops up but the title changes to "XXX is disconnected, press "Ctrl Shift R" to reconnect..."
- this only happens when table plus is in focus. If i hit Ctrl Shift R and focus chrome for example, no errors pop up, even when I enter table plus again.

Current version: 4.10.0 (202)
OS: Windows 10 Pro 19044 Build

**Comment by Havrin** [comment]
@huyphams

**Comment by son11592** [comment]
Hi @Havrin, I'm working on this issue but I could not reproduce this, the alert `Connection is disconnected, press Ctrl shift R to reconnect` only showed one time on my side. Could you please attach a video recording this issue on your side? It might help us find out the problem. And thank you for your feedback.

**Comment by Havrin** [comment]
sorry for the watermark and missing cursor. Just needed a quick solution to hide the connection.  
So first few seconds I successfully connect. At around 10 seconds I disconnect from my vpn to not be able to access the DB anymore. After a timeout the errors pop up several times:

https://user-images.githubusercontent.com/8169275/183404153-1d73d97c-5835-404a-b20d-3c904ba5e30e.mp4

**Comment by son11592** [comment]
ok thanks, @Havrin. I check it now.
