### ISSUE TITLE
Find in SQL Query Result Requires Lower Case or Match Case

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#542]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.33-log

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
202

3. The steps to reproduce this issue:
A SQL Query that retrieves a column that is all upper case
![image](https://user-images.githubusercontent.com/25158630/182970488-7ecb9bc5-c68d-473b-bf40-288194cd2f1a.png)

With "Match Case" unchecked, do a "Find" and type in an upper case character that is in some results, in this case I type the letter "B" and all results disappear.
![image](https://user-images.githubusercontent.com/25158630/182970773-4ce61b08-b612-45ef-9c6b-2d82fbfb843f.png)

Type a lower case "b" or check the box "Match Case"and the proper results appear
![image](https://user-images.githubusercontent.com/25158630/182970919-9ce8b6d5-bf62-435f-a3a9-9ce833b037db.png)

**Comment by son11592** [comment]
Hi @rwhirn, thank you for your feedback. We found the problem and fixed it. The next update will contain this fix.

**Comment by huyphams** [comment]
HI @rwhirn if you have a chance please download this patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thanks

**Comment by rwhirn** [comment]
@huyphams Looks good! Thank you.
