### ISSUE TITLE
Incorrect selected row count in query results

### ISSUE THREAD

**Issue by rohanc** [TablePlus/TablePlus-Windows#543]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgresql 13.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
202

4. The steps to reproduce this issue:

If you run a SELECT query using the SQL editor the results are displayed in the bottom half of the pane. Underneath the pane it says the number of rows returned, e.g. "100 rows". That number is correct.

If I then click on one or more of those rows, it says "15 of 100 rows". That first number (e.g. 15) seems to be always incorrect. It's also incorrect if I select multiple rows using CTRL+A or ctrl-click etc.

What I expect it to say is the number of rows selected by the user. For example, if I just click on the first row after the query has finished I expect it to say "1 of 100 rows".

<img width="487" alt="tableplus incorrect row count" src="https://user-images.githubusercontent.com/1295900/182999514-4624d39c-8a2c-4917-a671-9f81f7753499.png">

**Comment by son11592** [comment]
Hi @rohanc, thank you for your feedback. We found the issue and fixed it. The next build will contain this fix.

**Comment by huyphams** [comment]
HI @rohanc if you have a chance please download this patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thanks

**Comment by rohanc** [comment]
I applied the patch and it works great. Thanks for responding so quickly! Unlike some other projects, I feel like reporting bugs here is worth the effort.
