### ISSUE TITLE
SQL error when change the default value of the DateTime type in TablePlus.

### ISSUE THREAD

**Issue by nnahito** [TablePlus/TablePlus-Windows#545]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    - MySQL5.6, MySQL5.7, MySQL8, MariaDB
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
    - 4.10.1(202) x64
    - Build 202
3. The steps to reproduce this issue:
    - I get an SQL error when I try to change the default value of the DateTime type in TablePlus.
    - This is the SQL issued by TablePlus.
        - ```sql
          ALTER TABLE `db`.`article`
          CHANGE `created_at` `created_at` datetime NOT NULL DEFAULT 9999-12-31 23:59:59 COMMENT '';
          ```

I am not very good at English, so I am sorry if my notation is wrong.



Noted: If the bug is related to data, please attach an example SQL data.

**Comment by nnahito** [comment]
As a side note, the same error occurs in the Mac version.

**Comment by huyphams** [comment]
Hi @nnahito thank you for letting me know. We're working on it.

**Comment by huyphams** [comment]
Hi @nnahito if you have a chance, please install this patch https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0 
Please let me know if you are still seeing the issue.

**Comment by nnahito** [comment]
@huyphams 
Thank you!
I used the patch immediately.
It works fine!
TablePlus is very easy to use and we will continue to use it!
