### ISSUE TITLE
Running Queries or viewing large tables crashes application

### ISSUE THREAD

**Issue by jordonbrill** [TablePlus/TablePlus-Windows#55]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7.25 Ubuntu 18.04.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 62

3. The steps to reproduce this issue:
Run simple select where query on table of about 40,000 or just open large table and the application shuts down. I don't seem to be getting an error message or anything - the application just closes. Happy to help diagnose further!

Noted: If the bug is related to data, please attach an example SQL data.

![image](https://user-images.githubusercontent.com/271489/55432092-aa593700-5557-11e9-8b62-be8f27c0a694.png)

**Comment by huyphams** [comment]
Thank you @jordonbrill for the feedback, let me check it.

**Comment by jordonbrill** [comment]
Is there anything you would like me to help with on this?

**Comment by huyphams** [comment]
Thank you for reminding me, I've checked multiple time, but I don't think it related to the number of rows, I think it related to the data parsing.
<img width="1044" alt="demo" src="https://user-images.githubusercontent.com/3654622/56230649-f3a49d00-60a6-11e9-82e7-d04213427c12.PNG">

**Comment by jordonbrill** [comment]
The issue does still exist in the latest version even though I'm not 100% clear on what the issue actually is. I'm not really sure what's going on. I tried viewing one of my tables (which has a pretty simple structure and no real strange data) and it still just randomly closes the application. Here's the structure of one of the tables:

``` sql
CREATE TABLE `tablename` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `app` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `authentication` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `ip` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `params` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `route` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `status_code` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

It closes when I query it and also when I just click next page of results

![image](https://user-images.githubusercontent.com/271489/56835890-1a976780-683b-11e9-8880-da78ae5ffd8f.png)

I did run this query
``` sql
select count(*), app from tablename group by app;
```
and it didn't crash but actually showed me results after a while. The table has about 6.5M rows. Odd. Perhaps it is related to parsing/display of the data somehow - because this just showed summary data and worked.

**Comment by jordonbrill** [comment]
Major kudos to the team. I have been installing the updates that have been coming out (quite frequently, which is AWESOME) and the product continues to be much better. This problem appears to be resolved now. Thank you!

![image](https://user-images.githubusercontent.com/271489/68487009-ee0bd180-0207-11ea-8b0d-cba8cfad3635.png)

**Comment by ipmanlk** [comment]
This issue is still happening in the latest Linux version.

![image](https://github.com/TablePlus/TablePlus-Windows/assets/13213457/068aadf1-c63f-4a4b-87ef-563df88ffd02)

My current setup,
![image](https://github.com/TablePlus/TablePlus-Windows/assets/13213457/c8ac1a5c-688a-47e8-aef5-3878e59d9714)
