### ISSUE TITLE
Feature request: Data type highlighting

### ISSUE THREAD

**Issue by quantumwebco** [TablePlus/TablePlus-Windows#550]
Would be great to have cells highlighted by data type e.g.
![image](https://user-images.githubusercontent.com/12368817/185608776-9ab9cbd1-408d-49aa-b8c0-0c4972086478.png)
If this is implemented I plan to bring a whole team over to TablePlus (currently using a mix of HeidiSQL and native IDE tools). I would be willing to donate to make this happen before we shell out on multi user company licenses. Get in touch if something can be arranged. Thanks

**Comment by quantumwebco** [comment]
This has been implemented https://github.com/TablePlus/TablePlus/issues/2792 eagerly awaiting release

**Comment by huyphams** [comment]
Hi @quantumwebco if you have a chance, you could install this patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
It supports changing data text color.

**Comment by quantumwebco** [comment]
That is brilliant! Thanks so much! I'm off to buy some licenses :)
