### ISSUE TITLE
Copy cell/row functionality/shortcuts

### ISSUE THREAD

**Issue by quantumwebco** [TablePlus/TablePlus-Windows#552]
### Please answer the questions below, it helps us to track the issue.
Not really a bug but slightly unexpected behaviour and possibly missing a keyboard shortcut

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
202

3. The steps to reproduce this issue:
Highlight a cell and CTRL + C, expected to copy cell but copies whole row
You can copy a cell with right click but there is no keyboard shortcut and I found it unexpected for it to copy the whole row
Should CTRL + C be copy cell and something like CTRL + SHIFT + C be copy row? Shift being the default to select many in most OS
I want to copy a single cell value much more often than wanting to copy a whole row
It would be nice to have a keyboard shortcut to copy a single cell

**Comment by huyphams** [comment]
We've added the control + shift + C to copy the cell value.
Thanks for the suggestion.
