### ISSUE TITLE
SSH: 1Password Compatibility

### ISSUE THREAD

**Issue by suabahasa** [TablePlus/TablePlus-Windows#554]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
All driver and version

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
202 (x64)

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

Please support 1Password SSH Agent as described on https://developer.1password.com/docs/ssh/agent/

> The 1Password SSH agent uses the SSH keys you have saved in 1Password to seamlessly integrate with your Git and SSH workflows. It authenticates your Git and SSH clients without those clients ever being able to read your private key.
> 
> In fact, your private key never even leaves the 1Password app. The SSH agent works with the SSH keys stored in your Personal or Private vault, but never without your consent. Only SSH clients you explicitly authorize will be able to use your SSH keys until 1Password locks.

**Comment by suasgn** [comment]
duplicate #569
