### ISSUE TITLE
Copying output into excel/gsheets looses ordering

### ISSUE THREAD

**Issue by tdiggins1** [TablePlus/TablePlus-Windows#555]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Redshift
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
190
3. The steps to reproduce this issue:
4. 
run a query with a desired order by and either CTRL A on the output then CTRL C into excel OR
CTRL A on the output, right click, copy TSV with header, copy into excel

If exporting to CSV the ordering is retained but this is a much longer method of getting data out of tableplus

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks, we just fixed it. Please wait for the next update.
