### ISSUE TITLE
Preferences - Syntax Colors Listing - "Revered keywords" Typo

### ISSUE THREAD

**Issue by RhettApeirogon** [TablePlus/TablePlus-Windows#558]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
- MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 
- 202

3. The steps to reproduce this issue: 
- Menu>Help>**Preferences...**
- Select the Fonts & Colors tab
- Select the SQL Editor sub-tab
- Scroll down the **syntax colors listing** until you reach **"Revered keywords"**. I think that this should be **"Reserved keywords"**.

**Comment by huyphams** [comment]
Thanks, it's fixed.

**Comment by RhettApeirogon** [comment]
Thank you very much!
