### ISSUE TITLE
Executing more than one Query on sametime shows 1 affected rows

### ISSUE THREAD

**Issue by jagDanJu** [TablePlus/TablePlus-Windows#56]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
64

3. The steps to reproduce this issue:
If you mark more than one line with an insert or update statement and execute it, the display shows "1 rows afftected". The output would have to match the number of rows actually affected.

![image](https://user-images.githubusercontent.com/3613218/55687318-d9aee000-596b-11e9-9960-facac09dcf82.png)

**Comment by huyphams** [comment]
Thanks @jagDanJu it reported the wrong message because it only shows the message of the last query. Let me fix it.

**Comment by huyphams** [comment]
I fixed it, it will be included in the next update! thank you for the feedback.
