### ISSUE TITLE
Navigation bar for all databases, schemas & objects

### ISSUE THREAD

**Issue by mdjukicgit** [TablePlus/TablePlus-Windows#560]
Feature request - Navigation bar for all databases, schemas & objects needed

Instead of scratching around for schemas and objects, can you please, please, please introduce an 'Aginity' like navigation pane for all databases, schemas, & objects.   Tableplus is missing this BIG TIME.

Thanks.

**Comment by huyphams** [comment]
I'm not sure that I understand you correctly,  you mean the open anything feature?

<img width="1204" alt="CleanShot 2022-09-08 at 18 59 31@2x" src="https://user-images.githubusercontent.com/3654622/189116505-b0f2211d-c952-4dcb-bfe7-5c2d77e68099.png">

**Comment by huyphams** [comment]
Open anything (Control + P) contains all databases, schemas, objects, and also saved Queries.

**Comment by mdjukicgit** [comment]
Henry. . . . hi!!    You need this:
***@***.***
