### ISSUE TITLE
Run Current Query Not Running Correct Query

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#561]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server 2014 (Express)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
202

I have three queries in my window as you can see from the semi-colons
My cursor is very definitely placed in the third query
Yes when I "Run Current Query" it runs the first.
If I select/highlight the entire third query and then "Run Current Query" it runs the third correctly.
![image](https://user-images.githubusercontent.com/25158630/189393403-ffb668e3-1193-4d2f-a97c-bfd1a3dee1e7.png)

**Comment by huyphams** [comment]
Hi @rwhirn "run current query" will run the query under the cursor. So I think you placed the cursor on the top so it run the 1st query.
Please place the cursor in the last query, it will run the last query correctly. You can see the current query as it has a placeholder background.

**Comment by rwhirn** [comment]
@huyphams Nope I said "very definitely". I tried it **multiple** times with the cursor in different places, beginning, end and middle and it doesn't run that query no matter what, unless I highlight it.

**Comment by huyphams** [comment]
Do you see a placeholder of the selected query under the cursor? I'm testing with some queries and it works just fine. Can you send me all those queries to nick@tableplus.com so I can check them? (you can replace some sensitive data before sending it to us.).
Thank you in advance.

**Comment by rwhirn** [comment]
@huyphams Looks like its a SQL statement issue.
I have a nested "CASE" statement in both the first and second query. When I take those two statements out then the 3rd query runs fine. 
Here's what it looks like:
`CASE WHEN drequest<='2013-08-19' THEN 99 ELSE CASE WHEN drequest<='2013-08-20' THEN 14 ELSE 1 END END AS datesort,
`

**Comment by huyphams** [comment]
Thanks let me check with the nested case.

**Comment by rwhirn** [comment]
@huyphams I confirmed, if I reduce those long queries down to just the nested case statement, remove all JOINs and WHERE clauses then the third query does not run.

**Comment by huyphams** [comment]
Hi @rwhirn if you have a chance, please try this hotpatch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please let me know if you are still seeing the issue.

**Comment by rwhirn** [comment]
@huyphams All fixed! Thank you.
