### ISSUE TITLE
 permission denied for schema

### ISSUE THREAD

**Issue by mdjukicgit** [TablePlus/TablePlus-Windows#563]
I get this error when running simple SQ:L statements on a number of databases when using SQL.
However, when I run exactly the same SQL via a competing tool. . . . . .the SQL works fine.
Any ideas???

**Comment by huyphams** [comment]
Hi, are you sure that you're using the same user in TablePlus and in CLI?

**Comment by mdjukicgit** [comment]
Maybe not.  Thanks.
