### ISSUE TITLE
Crash when right-clicking in table list area

### ISSUE THREAD

**Issue by digiservnet** [TablePlus/TablePlus-Windows#564]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL & MariaDB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
4.10.6 - Build 204

3. The steps to reproduce this issue:
Load a database, right-click in a space in the left column under the list of tables. TablePlus will crash and disappear. Previous build (202) is functioning fine (though doesn't include he new grouping etc options).

**Comment by huyphams** [comment]
Hi @digiservnet thank you for letting me know. We just released a hot patch which fixed this issue. Please update the app!
Menu > Help > Check for update.

**Comment by digiservnet** [comment]
Perfect! Confirmed working as expected 🙂
