### ISSUE TITLE
Titlebar colours are washed out on windows 11.

### ISSUE THREAD

**Issue by mridulmp** [TablePlus/TablePlus-Windows#565]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Any

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
4.10.8 (206) - x64

3. The steps to reproduce this issue:

Titlebar colours are washed out on windows 11. It is very tough to see the icons and menu. I am attaching screenshots for both dark and light themes. Colours look very different from the screenshots from the readme on this repository.

![image](https://user-images.githubusercontent.com/6697601/190993612-28122310-10e9-4500-9ff9-47520d2ba856.png)

![image](https://user-images.githubusercontent.com/6697601/190993993-baab1a3c-431a-46a0-9125-fbedfff9e9bb.png)

**Comment by huyphams** [comment]
Hi @mridulmp I think those connections were imported from macOS and it keeps the macOS status bar colors. You could click the title bar and change the color again.
Thanks
