### ISSUE TITLE
PostgreSQL structure view taking too long to load.

### ISSUE THREAD

**Issue by zzz2496** [TablePlus/TablePlus-Windows#568]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 10.10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 4.10.8 Build 206

3. The steps to reproduce this issue: Open any table or view from the left side pane, then while the "Data" tab is loading, press the "Structure" tab, it will take a while to load if the "Data" tab is still loading.

Noted: If the bug is related to data, please attach an example SQL data.

Is there a way to directly load the "Structure" instead of waiting for the "Data" tab to completely loaded?

**Comment by huyphams** [comment]
Hi @zzz2496, please right-click on the table on the left-sidebar and select "open structure" it will open the structure directly without loading the data.
