### ISSUE TITLE
Unable to edit boolean values

### ISSUE THREAD

**Issue by samiggapps** [TablePlus/TablePlus-Windows#57]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

psql (PostgreSQL) 10.5 (Ubuntu 10.5-0ubuntu0.18.04)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

build 66 

3. The steps to reproduce this issue:

create a table with a field that only takes a boolean value true/false
cannot edit on the GUI

**Comment by huyphams** [comment]
I confirmed the issue and will fix it.
You can workaround by double the field on the left of the bool field and press tab, it will move to the next field, which allows you to edit it.

**Comment by huyphams** [comment]
I fixed it on the release 67. Thank you!
