### ISSUE TITLE
Tables are not shown in groups

### ISSUE THREAD

**Issue by Marcdj-02** [TablePlus/TablePlus-Windows#570]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
InnoDB 10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 210

3. The steps to reproduce this issue:
   - Right click sidebar
   - Click 'New'-> 'New group'
   - Add Name and tables
   - Click 'Save'

Tables added: (correct naming and casing)
![afbeelding](https://user-images.githubusercontent.com/72502650/195914189-c58ad6ad-3124-428b-8517-6ac95aa73bc9.png)

Tables not showing up in group (folder is empty)
![afbeelding](https://user-images.githubusercontent.com/72502650/195914245-40f31872-86a0-4647-9a54-bc8a29205585.png)

**Comment by sonswift** [comment]
Hi @Marcdj-02, I see that you created a group in Functions section. The groups in this section will contain only Functions or Store Procedures of this database.

If you want to create a group for Table or View, you have to right-clicked on the Tables section (or any items in it) and select New > New group.

Hope this help.

**Comment by Marcdj-02** [comment]
Can't believe I was that stupid. Thanks.
