### ISSUE TITLE
[Feature request] Ability to set connection encoding

### ISSUE THREAD

**Issue by mtaki14** [TablePlus/TablePlus-Windows#576]
It would be helpful to have the ability to set the character encoding at a connection level. There are cases when working with (usually legacy) databases whose data will appear as gibberish unless you set a specific encoding. 

Here is how the setting looks like in another software:

![image](https://user-images.githubusercontent.com/7987430/202125426-5835e53f-17b1-4ee2-92fe-bfe72a124b3d.png)

**Comment by huyphams** [comment]
Hi, please find it in the main menu.
 
<img width="484" alt="CleanShot 2022-11-16 at 15 18 22@2x" src="https://user-images.githubusercontent.com/3654622/202125835-9969542b-a849-45e4-b83d-601b054b47a0.png">

**Comment by mtaki14** [comment]
Oh lovely, didn't realise this was an option. Except I can't see "WIN1253 - Greek" in mine, which is the one I need. Is the list not exhaustive on the windows version?

This is all I have

![image](https://user-images.githubusercontent.com/7987430/202127189-c07b33ed-64d4-4164-a038-0ad657a7082f.png)

**Comment by huyphams** [comment]
Have you tried the   "greek": "greek - ISO Greek"?

**Comment by mtaki14** [comment]
Yes, that doesn't work. Unless I use 1253 then the data appear as gibberish. Could you please add the rest of the encodings in the windows version in the future?

**Comment by huyphams** [comment]
Sure, let me take a look at it.

**Comment by mtaki14** [comment]
Any progress on this? I'm forced to use another program just to work on this type of databases (which is quite often)

**Comment by huyphams** [comment]
Hi @mtaki14 we will send you a hot patch asap.

**Comment by huyphams** [comment]
if you have a chance, please try this patch: out date. Please let me know if you're still seeing the issue. Thanks

**Comment by mtaki14** [comment]
I've tried the patch but there seems to be an issue. I select the win1253 entry but as soon as I press ctrl + r to refresh the workspace (as asked) the selection goes back to the previous encoding.

**Comment by huyphams** [comment]
Hi @mtaki14 if you have a chance, please try https://www.dropbox.com/s/z807gbi7ir9nal6/TablePlusUpdate.exe?dl=0

**Comment by mtaki14** [comment]
Says file deleted

**Comment by huyphams** [comment]
You can also try to update the app to our latest release, it include the new encoding @mtaki14

**Comment by mtaki14** [comment]
Just tried the new update. I can see the new encondings but I'm still facing the same issue. As soon as I choose the win 1253 encoding and refresh the selection goes back to the previous one. Any of the other encodings seem to work fine

**Comment by mtaki14** [comment]
Any update on this? Here's a screen recording showing what I mean
![TablePlus_5rfqkSD7Bn](https://user-images.githubusercontent.com/7987430/223064873-05a73ce3-0076-4f8e-8a39-a684dbb1008b.gif)

**Comment by mtaki14** [comment]
Above issue still persists. This never has never worked properly
