### ISSUE TITLE
Can't connect to remore db over ssh

### ISSUE THREAD

**Issue by routrax** [TablePlus/TablePlus-Windows#58]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by routrax** [comment]
I'm unable to connect to a remote db over ssh.
The error message says 'Can't connect', which is not very helpful. 

Where are the logs?

**Comment by routrax** [comment]
MySql
Build 62
Just trying to connect over ssh.

I can connect via workbench and cli.

**Comment by huyphams** [comment]
Hi, @routrax thank you, let me take a look into it. Our newest build is the build 68, please update the app and try again.
A properly SSH setup should look like this one:
<img width="847" alt="Screen Shot 2019-05-21 at 7 14 05 PM" src="https://user-images.githubusercontent.com/3654622/58095208-b16a0080-7bfc-11e9-9d41-5578237c1581.png">

**Comment by routrax** [comment]
Hi,

I managed to get it working.

I updated to 68 and noticed the server had a trailing forward slash, which
must have been the problem.
It would be good if we could resize that form as the input is very small,
if are using remote servers like AWS etc as the host will be quite long.

Thanks for your help and fast response!

Stephen

**Comment by huyphams** [comment]
Thank you, I will improve and make it bigger. I'm closing this issue for now because it's resolved.
