### ISSUE TITLE
Unable to connect to clickhouse

### ISSUE THREAD

**Issue by smach1991710** [TablePlus/TablePlus-Windows#580]
I use TablePlus to connect to the clickhouse and report "Timeout waiting for connection", but I can connect using jdbc

**Comment by huyphams** [comment]
Hi @smach1991710 could you post the step to reproduce or at least the connection form? It's impossible to reproduce or help you to solve the issue without any information.

**Comment by smach1991710** [comment]
> 

![image](https://user-images.githubusercontent.com/6259941/203882486-35c3d1a3-6eb6-4ae3-9f31-921fa3e9c301.png)
This is my connection information, because it is an intranet, there is no way to give it to you

**Comment by smach1991710** [comment]
> Hi @smach1991710 could you post the step to reproduce or at least the connection form? It's impossible to reproduce or help you to solve the issue without any information.

![image](https://user-images.githubusercontent.com/6259941/203883209-a1e8ffcc-b7ed-4043-986f-5ff9f0c598c1.png)

This is my connection information, because it is an intranet, there is no way to give it to you。

**Comment by smach1991710** [comment]
> Hi @smach1991710 could you post the step to reproduce or at least the connection form? It's impossible to reproduce or help you to solve the issue without any information.

But I can connect to clikhouse by using jdbc through a simple java program, the configuration is the same, is it convenient for you to deploy a clickhouse for testing?

**Comment by huyphams** [comment]
Hi, @smach1991710 TablePlus does not use jdbc driver so the config could be a bit different. The 8123 is the HTTP protocol that is used for jdbc. Please use the native protocol (Default port 9000) for TablePlus.

**Comment by Slach** [comment]
@huyphams I tried to connect to public altinity clickhouse endpoint with Native TCP protocol over SSL with port 9440
and get the same error
![image](https://user-images.githubusercontent.com/105560/228861102-680283b9-5776-403c-b572-7761534e4b47.png)


![image](https://user-images.githubusercontent.com/105560/228860419-a5ea5187-1031-44f6-abfe-6c599b3664d5.png)

but `clickhouse-client -h github.demo.altinity.cloud --port 9440 -s --user=XXX --password=XXX`
works as expected
![image](https://user-images.githubusercontent.com/105560/228860977-5b0c03f5-ae79-4f40-b2d8-704bcc58ef9f.png)

where I can get debug logs to provide more detailed information?

**Comment by VictorCano** [comment]
I've got the exact same problem in TablePlus 5.4.0 (234) on Windows 11.

IPs are all whitelisted, also tried via tunneling and I keep getting "Timeout waiting for connection.".

Clickhouse client also works, my issue is exactly the same as @Slach.

I see the issue is closed but couldn't find any info or solution on all repos, and also nothing in the changelogs or docs. Shouldn't this issue be opened? I sure can help debugging.
