### ISSUE TITLE
Windows Cannot see top menu

### ISSUE THREAD

**Issue by squalsoft** [TablePlus/TablePlus-Windows#584]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Any db

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Latest - 214

3. The steps to reproduce this issue: run program, connect to db

Noted: If the bug is related to data, please attach an example SQL data.
https://disk.yandex.ru/i/PRsRw1Uym1MOig

**Comment by huyphams** [comment]
Hi @squalsoft I think you imported this connection from macOS. You need to click on the header and change the status color because it keeps the color from the macOS.
