### ISSUE TITLE
Not to open new tab on every single click in free version

### ISSUE THREAD

**Issue by dvlprJobayer** [TablePlus/TablePlus-Windows#586]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
--MySQL 8.0.30

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
--Build 214

3. The steps to reproduce this issue:
--When I click on any table once it gets automatically pinned without modifying it or double-clicking on it.

 Expected Behaviour:- 
 It should not get pinned without double-clicking or modifying.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
You can change this behavior in the app settings. Thanks!

**Comment by dvlprJobayer** [comment]
> You can change this behavior in the app settings. Thanks!

Thanks
