### ISSUE TITLE
Wrong decimal character in CSV Exports

### ISSUE THREAD

**Issue by belgacea** [TablePlus/TablePlus-Windows#59]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
cqlversion=3.4.4
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
70
3. The steps to reproduce this issue:
Export > CSV  (default decimal character = ".") > Export..
File contains comma "," as decimal seperators for `float` & `double` types.

Noted: If the bug is related to data, please attach an example SQL data.
Schema
```sql
CREATE TABLE IF NOT EXISTS test.message(
  id text,
  ts timestamp,
  code text,
  emi int,
  v text,
  t1 double,
  t2 double,
  t3 double,
  t4 double,
  t5 double,
  x float,
  y float,
  z float,
  PRIMARY KEY ((id), ts)
) WITH CLUSTERING ORDER BY (ts DESC);
```
```
"id","time","code","emi","v","t1","t2","t3","t4","t5","x","y","z"
"46","2019-04-01 00:00:57","1",1444,"1",66,12,34,5,29,31,64,56,38,31,67,32,9,64,31,53
"46","2019-04-01 00:00:52","1",1515,"1",66,34,5,29,31,64,56,38,31,69,08,24,91,36,7
"46","2019-04-01 00:00:46","1",1452,"1",66,12,34,5,29,31,64,5,38,31,66,88,11,12,34,43
"47","2019-04-01 00:00:46","1",1452,"1",100,12,34,5,29,31,64,5,38,31,66,88,11,12,34,43
"77","2019-04-01 00:00:41","1",1319,"1",66,19,34,5,29,31,64,5,38,31,67,82,8,66,34,79
```

**Comment by belgacea** [comment]
Hello @huyphams I don't understand then, because I get commas for all `double` & `float` in my queries. What could be the cause ? Is there a way to turn TablePlus in debug mode ?
Cassandra  : `[cqlsh 5.0.1 | Cassandra 3.11.3 | CQL spec 3.4.4 | Native protocol v4]`
.NET : `SDK v4.7.2`

**Comment by huyphams** [comment]
Thank for getting back, could you show me the screenshot of the export popup?

**Comment by belgacea** [comment]
![image](https://user-images.githubusercontent.com/17744651/58868255-3ef92600-86bc-11e9-990a-f6d005ff07c7.png)

**Comment by huyphams** [comment]
What is the character you're seeing in the data view, a dot or a comma?
<img width="580" alt="a" src="https://user-images.githubusercontent.com/3654622/58870250-0bcd8b80-86ea-11e9-8e28-140190a501ac.png">

**Comment by belgacea** [comment]
Commas
![image](https://user-images.githubusercontent.com/17744651/58871063-9e0d6980-86c1-11e9-9f16-d4af704dd1b0.png)

**Comment by huyphams** [comment]
got it, made sense now. TablePlus only replace the dot to the comma. I'm fixing it now.

**Comment by huyphams** [comment]
It's fixed now thank you @belgacea 
Download: https://www.dropbox.com/s/ealt5w189kecr2q/TablePlus_x64.zip?dl=0

**Comment by belgacea** [comment]
Thank you very much ! Works like a charm :relaxed:
