### ISSUE TITLE
Display Menu Bar

### ISSUE THREAD

**Issue by jimrandell** [TablePlus/TablePlus-Windows#591]
### Please answer the questions below, it helps us to track the issue.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build220

I cant find a way to display the menu bar, horizontally, across the top of the window, y'know, as god intended.

![image](https://user-images.githubusercontent.com/3543506/219077649-46214df4-b36a-4ec3-843c-415fc2db9fd7.png)

**Comment by rwhirn** [comment]
lol! Dinosaur!  (like me!)
