### ISSUE TITLE
Nothing is Shown in the screen

### ISSUE THREAD

**Issue by MohamedWail** [TablePlus/TablePlus-Windows#595]
1. Which driver are you using and version of it : MariaDB 10.4.22

2. Which TablePlus build number are you using: Build 226

3. The steps to reproduce this issue: i just open table plus and choose the database and nothing appears

![Bug](https://user-images.githubusercontent.com/45482372/223424185-b226e9f0-95e2-45e6-8283-f1f764b55906.png)

**Comment by sonswift** [comment]
Hi @MohamedWail, the left and right sidebars are collapsed. The buttons to toggle them are on the right of the menu bar (see image below). Or you can use the shortcuts:
`Ctrl 0` : Toggle left sidebar
`Ctrl Space`: Toggle right sidebar
Hope this help,

![image](https://user-images.githubusercontent.com/4739616/223426551-b30a498c-6b2c-44cb-be91-d312b5428068.png)
