### ISSUE TITLE
Refresh Data on re-click

### ISSUE THREAD

**Issue by jagDanJu** [TablePlus/TablePlus-Windows#6]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
6

3. The steps to reproduce this issue:
If you look in the table overview and left click one Table, then the data appear on the right side.
To update the data you have to press Windows + R. It would be nice if you could re-click on the table to update the data as well.

**Comment by huyphams** [comment]
Hi @jagDanJu this behavior is a good idea. but it has some disadvantages.
- When a table has a lot of data, and users don't want to reload it.
- When the connection was slow.
- When users simply don't want to reload it but want to navigate to it.
....
So I think we should not implement this feature, control + R is easy to use and similar to F5.

**Comment by jagDanJu** [comment]
Understandable Points
Thanks
