### ISSUE TITLE
Not Starting

### ISSUE THREAD

**Issue by basbroens** [TablePlus/TablePlus-Windows#604]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): na

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): na

3. The steps to reproduce this issue: starting tableplus

I run windows 11. I try to start tableplus. It does not open anything and i see no errors. Also nothing is started in taskmanager

**Comment by cragsdell** [comment]
I just installed the current Windows version of TablePlus to a H-P laptop. It doesn't open after the install is complete. Tried removing and re-installing with no luck.

**Comment by huyphams** [comment]
Hi @basbroens @cragsdell we're sorry for the issue, please re-download the build here and try again: https://tableplus.com/release/windows/tableplus_latest

**Comment by basbroens** [comment]
thnx.. that solved it
