### ISSUE TITLE
Error connecting to postgresDB since recent table plus upgrade, issue with password having "@" 

### ISSUE THREAD

**Issue by msbrizuela** [TablePlus/TablePlus-Windows#605]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
not sure , not informed in tableplus when connecting 
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**5.3.9 (232)**
3. The steps to reproduce this issue:
Connect to a postgres server which password contain a "@" character, results in a "could not translate host name "xxx@server" to address: Unknown server error
"
where xxx is the string in the pwd after the "@" 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @msbrizuela we will look at it, in the mean time, please download this hotpatch https://download.tableplus.com/windows/5.3.8/TablePlusSetup.exe
