### ISSUE TITLE
New connection opens in a new window instead of tab on the left tab bar

### ISSUE THREAD

**Issue by damamaty** [TablePlus/TablePlus-Windows#609]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

postgresql 12.14

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

build 234

3. The steps to reproduce this issue:

OS: windows 11
Open connection, ctrl+n, open another one. 
Expected: one window with the left tab bar appeared with 2 tabs for each connection
Actual: 2 windows

As I can see there was tabbed mode on windows like on macos (e.g. in the blog post: https://tableplus.com/blog/2020/10/redesign-tableplus-windows.html), was it removed or should it be activated somehow?

**Comment by sonswift** [comment]
Hi @damamaty, thank you for your feedback. Currently, TablePlus Windows has already supported for open a new connection in `Tabbed Mode` by clicking the top-left connection button or using the shortcut: `Ctrl Shift K` 

![image](https://github.com/TablePlus/TablePlus-Windows/assets/4739616/cdd94c38-07f7-48d1-bbef-e3e4bdd42d54)

**Comment by huyphams** [comment]
Hi @damamaty that is intentional behavior.
