### ISSUE TITLE
Tables in database do not show

### ISSUE THREAD

**Issue by srchulo** [TablePlus/TablePlus-Windows#61]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0.16

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
70

3. The steps to reproduce this issue:
Connect to mysql over ssh and look at the tables shown in the database. Tables is empty, but should show one table that exists:

![image](https://user-images.githubusercontent.com/935847/59734925-02c7d880-9219-11e9-8c14-bbd88c67ee78.png)

When I run:

`show tables in my_db;`

It does show the one table, so I know that the table exists:

![image](https://user-images.githubusercontent.com/935847/59734976-39055800-9219-11e9-8ff4-2d101636271d.png)

**Comment by sgsharma** [comment]
Also experiencing this issue. Seems to only happen when the tables are empty. 
Running PostgreSQL 10.0
Using TablePlus Version 2.8.2 (256)
When running:

```
SELECT 
    *
FROM
    information_schema.tables;
```

I see several tables but don't see any tables in the dropdown.

**Comment by huyphams** [comment]
Hey @sgsharma  have you changed the schema at the bottom left? The macOS doesn't have this issue.

**Comment by sgsharma** [comment]
> Hey @sgsharma have you changed the schema at the bottom left? The macOS doesn't have this issue.

Yep, tried switching schemas. I can attach screenshots if you like!

**Comment by huyphams** [comment]
Sure, you can drop me an email nick@tableplus.com thank you so much!

**Comment by chans08** [comment]
> 1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
>    MySQL 5.6.47
> 2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
>    version 3.6.0 (Build 128)
> 3. The steps to reproduce this issue:
>    Connect to mysql over ssh and look at the tables shown in the database. Tables is empty, but should show 11 tables that exist:
> 
> When I run:
> 
> `show tables in my_db;`
> 
> It does show the 11 tables, so I know that the tables exist:
> 
![tablepluserror캡처](https://user-images.githubusercontent.com/47965020/84449557-b165f400-ac88-11ea-83a0-c8cf454a2c20.PNG)

**Comment by kanlukasz** [comment]
I have same problem with `mariadb`

**Comment by adamJLev** [comment]
Same issue on Tableplus on mac and Postgres v10.

If i do this I see the tables:
```SELECT 
    *
FROM
    information_schema.tables;
```

but in the sidebar no tables show

**Comment by huyphams** [comment]
Hi, please try our latest release 146 and also change the schema at the bottom left @adamJLev

**Comment by adamJLev** [comment]
@huyphams only seeing a public schema there, should I be expecting anything else? no tables are shown either way.
Btw this is on mac latest (348) 

<img width="566" alt="Screen Shot 2020-10-27 at 4 53 52 PM" src="https://user-images.githubusercontent.com/188466/97327226-8ce37080-1853-11eb-9e15-643f2a63571f.png">
