### ISSUE TITLE
W11 tableplus won't start

### ISSUE THREAD

**Issue by Petoches** [TablePlus/TablePlus-Windows#610]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): na

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): na

3. The steps to reproduce this issue: starting tableplus

same as this issues from May https://github.com/TablePlus/TablePlus-Windows/issues/604, tried to start tableplus on W11 but nothing happens, tried to uninstall and reinstall several times, still nothing.

**Comment by sonswift** [comment]
Hi @Petoches, does it happen with the latest version on our website? Did you install the app before or this is the first time install? 

I couldn't reproduce this issue. Could you please attach a recorded video of this issue?

Thanks

**Comment by Petoches** [comment]
Yes it happens with the latest version, i used tableplus for more than 2 years now it just stopped working overnight.
I tried to uninstall and reinstall while restarting windows in vain. I click on the soft and nothing happen, not even in the task manager.

**Comment by Petoches** [comment]
Seems like i fixed it by installing the version : TablePlus 5.3.3 - Build 228
Then updating to the latest version via the software ...
