### ISSUE TITLE
after connecting to sqlite database file , no files or items are shown in the items

### ISSUE THREAD

**Issue by GidonLakra** [TablePlus/TablePlus-Windows#612]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: SQlite 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @GidonLakra could you show us the screenshot please? Maybe you forgot to toggle the item sidebar (click button on top right)
