### ISSUE TITLE
CSV Import Utility no longer works

### ISSUE THREAD

**Issue by VTAGithub2020** [TablePlus/TablePlus-Windows#613]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Postgress

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 236

3. The steps to reproduce this issue: Right Click on Postgres table name in list..Import..From CSV.  There is an option after selecting the CSV file to match column names by name case insensitive.  However, the Do No Import is checked automatically for all columns.  Have to manually go in and change each column to the proper name.  This broke prior versions that worked perfectly. 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by VTAGithub2020** [comment]
DB Version is Postgres 12.14

**Comment by huyphams** [comment]
Hi, on the top right, there is a matching option where you can choose how to match columns

**Comment by VTAGithub2020** [comment]
Yes.  And that what is not working.  It worked before.  To make it work now, you have to select each column because the default is do not import now.  Test it out.

**Comment by VTAGithub2020** [comment]
If you don't change the default from Do Not Import to the proper column name, then you get the following error

[test1.pdf](https://github.com/TablePlus/TablePlus-Windows/files/12178394/test1.pdf)

**Comment by huyphams** [comment]
Thanks fixed, will deploy update soon 🙌

**Comment by VTAGithub2020** [comment]
Great.
