### ISSUE TITLE
Add support to access DuckDB databse files

### ISSUE THREAD

**Issue by f8dca** [TablePlus/TablePlus-Windows#620]
It would be great if TablePlus would add support DuckDB:
https://duckdb.org/why_duckdb.html

**Comment by geertbrit** [comment]
Any plans for this?

**Comment by steverob** [comment]
+1 for this

**Comment by amuedespacher** [comment]
+1 - that'd be great!

**Comment by mfyz** [comment]
+1

**Comment by Mrunal-Saoji** [comment]
+1

**Comment by zrbbv** [comment]
+1

**Comment by huyphams** [comment]
thanks, I forgot to close this issue. DuckDB is already supported on Windows.
