### ISSUE TITLE
Tableplus fails to read column types for new MariaDB server version (11.2) 

### ISSUE THREAD

**Issue by ALameLlama** [TablePlus/TablePlus-Windows#622]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB Server 11.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 240

3. The steps to reproduce this issue:
I noticed this when provisioning homestead using mariaDB and connecting to the database base, I've also recreated this spinning up a docker container.

most of the types will returned unknown but some will return other types like geometry instead of long text and erroring out

![image](https://github.com/TablePlus/TablePlus-Windows/assets/55490546/2fe274bb-e558-46c6-ba13-b3e28c3de6f1)

**Comment by ALameLlama** [comment]
to replicate
```
CREATE TABLE example_table (
    id INT NOT NULL AUTO_INCREMENT,
    varchar_column VARCHAR(255),
    char_column CHAR(10),
    text_column TEXT,
    longtext_column LONGTEXT,
    int_column INT,
    smallint_column SMALLINT,
    bigint_column BIGINT,
    float_column FLOAT,
    double_column DOUBLE,
    decimal_column DECIMAL(10, 2),
    date_column DATE,
    time_column TIME,
    datetime_column DATETIME,
    timestamp_column TIMESTAMP,
    boolean_column BOOLEAN,
    enum_column ENUM('Option1', 'Option2', 'Option3'),
    set_column
    SET('Value1', 'Value2', 'Value3'),
        binary_column BINARY(16),
        varbinary_column VARBINARY(255),
        blob_column BLOB,
        json_column JSON,
        spatial_column GEOMETRY,
        PRIMARY KEY (id)
);
INSERT INTO
    example_table (
        varchar_column,
        char_column,
        text_column,
        longtext_column,
        int_column,
        smallint_column,
        bigint_column,
        float_column,
        double_column,
        decimal_column,
        date_column,
        time_column,
        datetime_column,
        timestamp_column,
        boolean_column,
        enum_column,
        set_column,
        binary_column,
        varbinary_column,
        blob_column,
        json_column,
        spatial_column
    )
VALUES
    (
        'Hello',
        'ABC',
        'This is a text',
        'This is a long text',
        42,
        10,
        1234567890,
        3.14,
        123.456,
        99.99,
        '2023-10-26',
        '13:45:00',
        '2023-10-26 13:45:00',
        NOW(),
        TRUE,
        'Option2',
        'Value1,Value3',
        0x01A5,
        0x010203,
        'This is a BLOB',
        '{"key": "value"}',
        POINT(1, 2)
    );
 ```
 You can see most of them are unknown, longtext is geometry and also breaks in the normal data view and ENUM seems to be the only one that works
![image](https://github.com/TablePlus/TablePlus-Windows/assets/55490546/a0028ae5-7586-438c-98cc-c6d52844f22b)
![image](https://github.com/TablePlus/TablePlus-Windows/assets/55490546/1eb83262-6a93-44c8-b41e-3798749d72c9)

**Comment by sonswift** [comment]
Hi @LlamaDuckGoose, thank you for your feedback. This issue has been fixed. The next update will contain it.

**Comment by ALameLlama** [comment]
@sonswift I just downloaded Build 242 and it seems to still be a problem but instead of it being unknown, it's now decimal
![image](https://github.com/TablePlus/TablePlus-Windows/assets/55490546/53b07100-faa3-4c81-ae5c-d8a7a404cde6)

**Comment by huyphams** [comment]
Hi @LlamaDuckGoose we know the issue. We will fix it in the hotpatch. Thank you for the details

**Comment by huyphams** [comment]
Hi @LlamaDuckGoose if you have a chance, please try this patch: https://www.dropbox.com/scl/fi/dv4n8k2xsb94pmnvh71ij/TablePlusUpdate.exe?rlkey=e5x05sl3mjefva6jzfd15q94y&dl=0
Let me know if you're still seeing the issue.

**Comment by ALameLlama** [comment]
@huyphams downloaded the newest version and it looks good to me know, thanks <3
