### ISSUE TITLE
SQL dump import functionality on windows only uses first 10,000 characters

### ISSUE THREAD

**Issue by maxstoll94** [TablePlus/TablePlus-Windows#627]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
- PostgresSQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
- 242

4. The steps to reproduce this issue:
- When I import an SQL dump the maximum character limit is 10 000 (on Windows 11). Where as for my colleague the maximum is set to 100 000 (on MacOs). 
- As a result he can successfully import this dump file but I cannot. 

<img width="320" alt="image" src="https://github.com/TablePlus/TablePlus-Windows/assets/14106031/57630556-bd60-41d8-9127-6aa4e142ff99">

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @maxstoll94 it show you the example of the file, it does not indicate that it will only import first 10k. Let say, if you import 10GB of text. Showing all of them is not possible.
