### ISSUE TITLE
mySQL 5.1.73 bad handshake

### ISSUE THREAD

**Issue by Cweber-RPS** [TablePlus/TablePlus-Windows#628]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mySQL (whatever is the default)
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
5.5.0 (242)
3. The steps to reproduce this issue:
Updated to version 5.6.0 (244)

Upgrading the TLS broke our mySQL connections 5.1.73; provides a warning/failure of "bad handshake"

**Comment by huyphams** [comment]
Hi @Cweber-RPS you may want to try our 254 release which fixes this issue.
