### ISSUE TITLE
Query 1: Commands out of sync; you can't run this command now

### ISSUE THREAD

**Issue by angus-mcritchie** [TablePlus/TablePlus-Windows#629]
1. DB Driver: `MySQL 8.0.34`
2. TablePlus build number: `244`
3. The steps to reproduce this issue:
    Run any SQL query that would produce an error eg. `select 1 from non_existant_table`

I get `Query 1: Commands out of sync; you can't run this command now` back, however, I expect to get a useful error message such as 
 `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database_1.non_existant_table' doesn't exist`.

I rolled back my TablePlus version to build `242`, and it displayed the correct error message as expected.

**Comment by huyphams** [comment]
Hi @angus-mcritchie thanks you. We fixed the issue, please update the app to the build 246.
