### ISSUE TITLE
Driver errors when connecting to a database from the Open Connection menu specifically

### ISSUE THREAD

**Issue by marty0678** [TablePlus/TablePlus-Windows#630]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
	* MySQL 8.0.29
	* Mongo 3.6.12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
	5.6.2.246

3. The steps to reproduce this issue:
	There appears to be driver errors when opening some connections from the open connection menu, but not from the main menu or the edit connection menu.

### Working Steps Example:
1. Configure a connection to a MySQL database
2. Use SSH, and add your private key
3. Run test, verify it works.
4. Then connect to it

#### Results:
You can connect and it's wonderful.

#### Breaking Steps Example:
1. Still keeping the DB you just made, create a new one (it doesn't matter what it is).
2. Connect to it.
3. Now once you are in the new DB, instead of going to Menu -> Connection -> New and selecting your DB you made above, instead go to the Show Connection List menu at the top left (CTRL + SHIFT + K) and open your database from that menu.

#### Results:
You get a SSH Error - Invalid private key error and you can't connect. If you go through the Menu -> Connection -> New option however, you can.

Similar, if you use a Mongo DB connection (not even with SSH), and you do the same steps, you instead get this error: 

Driver Error
Invalid URI Schema, expecting 'mongodb://' or 'mongodb+srv://'

Even though the schema does have that and it can connect when going through the Connection menu.

This only broke once I updated to build 246. I'm assuming the Connection List is just not getting the full driver details correctly during the connection.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi! Thank you for reaching out. I'm sorry for the issue. The patch 248 has been released to address this issue. Please let me know if you're still seeing any bugs.

**Comment by marty0678** [comment]
Oh wow, thanks for the super fast turn around! Patch works great thank you!

**Comment by huyphams** [comment]
yeah, we found an other issue with backup/restore.

**Comment by charlielangridge** [comment]
@huyphams - Backup doenst work with 248
