### ISSUE TITLE
Backup gives "Invalid Prviate Key" error

### ISSUE THREAD

**Issue by charlielangridge** [TablePlus/TablePlus-Windows#631]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 248

3. The steps to reproduce this issue: I can connect to, (read / update etc) the database as normal, but if I use the backup facility I get the "Invalid Private Key" error - inspite of they key being correct. This error has only occurecd with this release, and was working well yesterday

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by marty0678** [comment]
Sounds related to this - https://github.com/TablePlus/TablePlus-Windows/issues/630

**Comment by charlielangridge** [comment]
@marty0678 - yes, but 248 doesnt fix the issue :(

**Comment by huyphams** [comment]
Sorry for the issue. We fixed it and pushed the update again. Let me know if you're still seeing the bug.
