### ISSUE TITLE
Right Click Menu on SQL Query

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#632]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.42-log

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
252

3. The steps to reproduce this issue:
Open SQL Query window
Right click
![image](https://github.com/TablePlus/TablePlus-Windows/assets/25158630/4732b3c6-abdb-4fe8-bf95-b02fe86c7833)
Two options cut off

**Comment by sonswift** [comment]
Thank @rwhirn, it will be fixed in the next update.

**Comment by huyphams** [comment]
Hi @rwhirn this patch should fix the issue: https://www.dropbox.com/scl/fi/dv4n8k2xsb94pmnvh71ij/TablePlusUpdate.exe?rlkey=e5x05sl3mjefva6jzfd15q94y&dl=0
Thank you for letting us know.

**Comment by rwhirn** [comment]
@huyphams Fixed! Thank you.
