### ISSUE TITLE
Queries on Microsoft SQL Azure (RTM) Drivers Datetimeoffset Datatypes wrong date format and shown as unknowns type

### ISSUE THREAD

**Issue by thmlbdshoichi** [TablePlus/TablePlus-Windows#633]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
- Microsoft SQL Azure (RTM)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
- TablePlus 5.6.9 Build 252 x64

3. The steps to reproduce this issue:
- Query any data from the table that has a column which has data type of datetimeoffset 
- and the date result will be in wrong format 
- Result: 23/10/2023 15:33:37 +07:00 (wrong) expected 2023-10-23 15:33:37.2159443 +07:00
- this behavior is also preventing an update using Tableplus GUI tools since the value is in wrong format

Noted: If the bug is related to data, please attach an example SQL data.

![image](https://github.com/TablePlus/TablePlus-Windows/assets/26995849/fc1581dc-626d-4db6-89c4-9d910dc77d5a)
![image](https://github.com/TablePlus/TablePlus-Windows/assets/26995849/94d65c21-7e6b-4804-bb24-dbe746205d00)
![image](https://github.com/TablePlus/TablePlus-Windows/assets/26995849/5e1dfd8d-0753-4c65-aa20-0025d817f9a0)
![image](https://github.com/TablePlus/TablePlus-Windows/assets/26995849/d6fa867d-9c1d-49ef-b9fa-1bd881ab7b66)

**Comment by sonswift** [comment]
Hi @thmlbdshoichi, I found the problem and fixed it. The next update will contain this fix. Thanks for your feedback.
