### ISSUE TITLE
Drag&Drop a connection looses the password configuration

### ISSUE THREAD

**Issue by nelsou** [TablePlus/TablePlus-Windows#634]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Not Applicable

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 238

3. The steps to reproduce this issue:
When you drag and drop a connection, password is reset and we have to fill it again which is really anoying as we often drag&drop by mistake ...

<img width="250" alt="image" src="https://github.com/TablePlus/TablePlus-Windows/assets/143550/da562b23-2faa-43b7-902c-789e2e3bbd98">

**Comment by sonswift** [comment]
Hi @nelsou, have you try to update app to the latest version. We have already improved the connection credential. Hope this will help you, thanks.

**Comment by nelsou** [comment]
Thank @sonswift , indeed Build 252 fixes my issue, good job.
