### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by amkhrjee** [TablePlus/TablePlus-Windows#635]
The issue is when installing from the `TablePlusSetup.exe`. 

First error: Could not copy LibSkia.dll - the source file may be corrupted. I skipped the file, and the second error occured.

Second error: `af.pak` may be corrupted. After this I just cancelled the installation.

My System: ASUS FX505DY running Windows 10 Home
 
![image](https://github.com/TablePlus/TablePlus-Windows/assets/50242721/7bcf0883-f421-49a5-8069-d535871fa3df)

**Comment by huyphams** [comment]
Thanks let me check it!

**Comment by huyphams** [comment]
I could not reproduce the issue, would you mind to try our build from the changelogs and see how it goes? 
https://tableplus.com/win/changelog
Please install the build 254 and 252

**Comment by amkhrjee** [comment]
Sure I'll give it a go and update you on how it went.

**Comment by amkhrjee** [comment]
It went smoothly and the installer successfully installed it. I think it had something to do with Windows Updates because right after I posted the issue, I restarted my computer and installed a few updates.

**Comment by huyphams** [comment]
So you're on the latest release?

**Comment by amkhrjee** [comment]
Yes, Build 254
