### ISSUE TITLE
SSL Connection no longer provided for MariaDB

### ISSUE THREAD

**Issue by localpath** [TablePlus/TablePlus-Windows#637]
### Please answer the questions below, it helps us to track the issue.
SSL Connection no longer provided

Enforce no longer provides SSL connection between client and RDS instance. (this was working an update or two back)
Verify Server Cert no longer fails SSL check even when no cert is provided. (this would always fail correctly as I wasn't trying to actually verify but now it doesn't fail when I think it should)

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.6.14
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 254
3. The steps to reproduce this issue:
Create a new connection to MariaDB instance over SSH proxy into AWS VPC w/ private DB connection
Select "Preferred" for SSL mode
Connect to DB
Observe no SSL connection provided by client

Example screenshot below that would provide an SSL connection but now it no longer will.

![image](https://github.com/TablePlus/TablePlus-Windows/assets/44937070/2c12833c-232c-446a-9001-c222c93f5f8a)

![image](https://github.com/TablePlus/TablePlus-Windows/assets/44937070/b0502fcb-98e6-4137-b11b-a2650c87e697)

**Comment by huyphams** [comment]
Hi @localpath thank you for letting me know. I'm not sure why LibMariaDB does not support SSL. (previously we use Lib MySQL).
In the meantime, you can use the MySQL driver for MariaDB, they are just the same (different maintainers).

**Comment by huyphams** [comment]
Hi @localpath if you have a chance, please try this patch and see how it goes:
https://www.dropbox.com/scl/fi/hqi17lg3wrg74deuqxpmb/TablePlusUpdate.exe?rlkey=ap8at4ntmuw4wpgas4b46797y&dl=0
Thanks

**Comment by localpath** [comment]
@huyphams Thanks for that. Seems to be working good now.

![image](https://github.com/TablePlus/TablePlus-Windows/assets/44937070/2e306914-967c-4741-b85c-c77df5336559)

**Comment by huyphams** [comment]
Thanks for confirming.
