### ISSUE TITLE
Slow slow slow

### ISSUE THREAD

**Issue by Davidkulpe** [TablePlus/TablePlus-Windows#638]

**Comment by huyphams** [comment]
Hi @Davidkulpe I don't understand the issue, please tell us the step to reproduce the bug.
Thanks!

**Comment by Davidkulpe** [comment]
Hi guys,
Thank you for reaching back....
I'm just stating that I purchased a new license for the best DB tool I know
, after updating to latest version everything started to response much
slower than previous.
I dont think you can reproduce it is just like this

**Comment by huyphams** [comment]
What do you mean by slow? Loading item list or query editor or auto complete, or the data grid or something?

**Comment by huyphams** [comment]
and which version are you using before the update?
