### ISSUE TITLE
Toolbar link colors on Windows 11 in dark mode

### ISSUE THREAD

**Issue by mortenthogersen** [TablePlus/TablePlus-Windows#639]
For me the toolbar doesn't seem to color in right. See attached screenshot.

It's white text on an almost white toolbar. Despite windows being set to a dark toolbar in dark mode

Version is 5.7.1 (254) - x64

![image](https://github.com/TablePlus/TablePlus-Windows/assets/5855443/39414150-b68a-4b86-b7c7-6c091654b4e3)

**Comment by sonswift** [comment]
Hi @mortenthogersen, I will check it now. Could you please tell me which theme you are using? Did you change any colors in theme config?

**Comment by mortenthogersen** [comment]
I am using the light theme but it doesn't matter if the theme is dark or light. Toolbar still stays white for me. I have no custom theme colors set. I even tried restoring defaults

**Comment by sonswift** [comment]
ok, let me take a look on it.

**Comment by mortenthogersen** [comment]
I can add that the welcome screen where i can select server etc. is with dark toolbar

**Comment by sonswift** [comment]
yes, please. It might help me find out your problem

**Comment by huyphams** [comment]
Hi @mortenthogersen did you import this connection from other platform (macos, ios)?
You may want to click on the title and change the status color.

**Comment by mortenthogersen** [comment]
> Hi @mortenthogersen did you import this connection from other platform (macos, ios)? You may want to click on the title and change the status color.

There we go, they are synced with my work Macbook.. changing the status color changes the toolbar color as well
