### ISSUE TITLE
Missing Authentication Plugin

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#642]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
254

3. The steps to reproduce this issue:
Trying to connect over SSH with private key
![image](https://github.com/TablePlus/TablePlus-Windows/assets/25158630/d77d0115-01cc-4ad0-9c13-47438bbfca8b)

**Comment by huyphams** [comment]
Hi @rwhirn please try our latest release 256 it should resolve the issue! Thanks!

**Comment by rwhirn** [comment]
All good @huyphams . Thank you.
