### ISSUE TITLE
Stupid Human Error

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#644]
Stupid Human Error

**Comment by huyphams** [comment]
Hi @rwhirn could you click the console and check which queries were sent to the server? does it include limit 1000?

**Comment by rwhirn** [comment]
Henry:

Oh dang. I knew it was going to be something stupid that I was doing wrong!
 
Sorry. :(

**Comment by huyphams** [comment]
Hi @rwhirn so can you confirm it is not an TablePlus issue? 
Thank you and happy new year!

**Comment by rwhirn** [comment]
Yes, working fine. Happy New Year to you too!
