### ISSUE TITLE
[Feature Request] Sidebar Views\Triggers\Non-Table collapse-expand functionality

### ISSUE THREAD

**Issue by ddiatlov** [TablePlus/TablePlus-Windows#646]
### Feature Request
As of now, there are Functions and Tables sections in the sidebar, but it would be nicer if there also was a Views and Triggers section, because it is a little confusing when the views are listed with all the tables.

Thanks.

![image](https://github.com/TablePlus/TablePlus-Windows/assets/42209321/4d232380-d20d-485b-bcb9-80dd8963952d)

* Driver: Microsoft SQL Server 2019 15.0.2104.1 (X64) 
* TablePlus build number: 5.8.0 (256)

**Comment by huyphams** [comment]
Hi @ddiatlov you can create your custom rule here:
<img width="458" alt="Screenshot 2024-01-16 at 11 20 34 AM" src="https://github.com/TablePlus/TablePlus-Windows/assets/3654622/c82c64b2-9e08-454b-9b5f-07d1e1d69916">

**Comment by huyphams** [comment]
it only works with views, we do not support viewing triggers on sidebar.

**Comment by ddiatlov** [comment]
Thank you for the quick response :)
