### ISSUE TITLE
cannot update anymore

### ISSUE THREAD

**Issue by Link2Trials** [TablePlus/TablePlus-Windows#649]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Mysql

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

256

4. The steps to reproduce this issue:

Update tableplus

I cannot update TablePlus anymore. i get a popup with a message that iam not connected to the internet, but iam.

**Comment by huyphams** [comment]
Hi @Link2Trials please try again, let me know if you're still seeing the issue.

**Comment by Link2Trials** [comment]
Hi

Thanks it works now.

Greet
Edwin
________________________________
Van: Henry Pham ***@***.***>
Verzonden: vrijdag 2 februari 2024 07:40
Aan: TablePlus/TablePlus-Windows ***@***.***>
CC: Edwin Swart ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [TablePlus/TablePlus-Windows] cannot update anymore (Issue #649)

U ontvangt niet vaak e-mail van ***@***.*** Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Hi @Link2Trials<https://github.com/Link2Trials> please try again, let me know if you're still seeing the issue.
