### ISSUE TITLE
Navigate query issue after creating graph panel on Metrics Board

### ISSUE THREAD

**Issue by Carlo-Nigro** [TablePlus/TablePlus-Windows#661]
Hi, i'm using Postgresql 15.6 driver, TablePlus 5.9.6 (270) on Windows 11 System.

If I create a panel on metrics board in which the query is more long than the textbox, it happens that if I want to see query definition by clicking the box, if I scroll content with mouse scroll or use the scrollbar, the pop-up disappears :(

**Comment by sonswift** [comment]
hi @Carlo-Nigro, thank for your report. I will check it now.

**Comment by Carlo-Nigro** [comment]
Hi @sonswift ,
the issue was solved in the last release 5.9.6 (272).
Thank you!
