### ISSUE TITLE
Blank screen while opening connection.

### ISSUE THREAD

**Issue by ragul-pr** [TablePlus/TablePlus-Windows#664]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 14.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):  270

3. The steps to reproduce this issue: I try to open any connection only black screen is showing.

Noted: If the bug is related to data, please attach an example SQL data.

![Screenshot (99)](https://github.com/TablePlus/TablePlus-Windows/assets/157595504/c2ed8f49-2d90-4921-a624-3f034b1767e2)

**Comment by huyphams** [comment]
Hi @ragul-steamA you toggled the sidebar off. You can toggle it again by click the icon of the top right.

**Comment by ragul-pr** [comment]
Thanks for letting me know

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
