### ISSUE TITLE
Field Autocomplete requires full tablename

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#67]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
72

3. The steps to reproduce this issue:
When typing SQL query in order to get field autocomplete to work you must type the complete table name first and every time. Often, typing the complete table name is more characters than typing out the entire field name. Certainly if I am typing a plain vanilla SELECT from a single table it ought to determine the table name from the "FROM" clause. Or at least if I give it an alias name 
like "c" it should be able to autocomplete from "c.".

**Comment by huyphams** [comment]
I think TablePlus Editor now smarts enough and also support alias. It also has column auto-completion if there are tables in the query.
Let me know if you're still seeing the issue.

**Comment by rwhirn** [comment]
Field names are there now yes.

I'm not sure how this new fuzzy search algorithm works, and maybe it just takes some getting used to and searching a different way. For me this is what happens when I type "cus"
![image](https://user-images.githubusercontent.com/25158630/64566926-b1f9e480-d31c-11e9-9b41-f152342b3fba.png)

Its not until I type "custom" that I get all the tables and fields beginning with "cus"
![image](https://user-images.githubusercontent.com/25158630/64568815-4e25ea80-d321-11e9-8b95-d23e04f3360d.png)

**Comment by rwhirn** [comment]
@huyphams Autocomplete doesn't work with an alias if you have two "id" fields, "a.id, b.id" you can't type "a." plus anything and get any autocomplete. You must type the field name alone and then go back and add the alias.

**Comment by huyphams** [comment]
Thanks @rwhirn let me check and improve it.

**Comment by huyphams** [comment]
Could you try this update: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0 and let me know if it works for you?
You can download and install it without any compatible issue, it will update the existed TablePlus app.
When the new build release, you can still upgrade as the official release.

**Comment by rwhirn** [comment]
Not seeing any change. If I type "c" I get options:
![image](https://user-images.githubusercontent.com/25158630/65441463-09558580-ddf0-11e9-8930-343eeb7f573a.png)

If I type "o.c" I get nothing:
![image](https://user-images.githubusercontent.com/25158630/65441584-4752a980-ddf0-11e9-9d87-343db6cbf30a.png)

**Comment by huyphams** [comment]
I can reproduce the bug now, I'm fixing it.

**Comment by huyphams** [comment]
Please try this update @rwhirn https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0 it should fix the issue.

**Comment by rwhirn** [comment]
Perfect!
