### ISSUE TITLE
Not able to modify Query Result Font Size. Only modifies font-size. Editor font-size change doesn't reflect to the query results table font size. 

### ISSUE THREAD

**Issue by Veznan7410** [TablePlus/TablePlus-Windows#679]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 14

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 276

3. The steps to reproduce this issue: The font for the query results table font is much bigger than it was at the start of installing the application. 
- I am on windows machine. 
- This issue occurred when I was trying to increase the font size of Query Results Table font-size. The size is increased in some-way. 
- But won't go back or reset to it's original size. 
- There is not distinct instructions in the documents to modify the query results in table font size. 
- Both font size of editor and query result pane should be separately handled. Cannot find the UI option for the same as well. 

I want to bring attention to the font size modification (requirement), should be freely able to modify the font size for Query Result Pane. 

Image Attached.

Noted: If the bug is related to data, please attach an example SQL data.
![image](https://github.com/user-attachments/assets/39f18098-0046-4fa7-9b05-04907bb00048)

**Comment by sonswift** [comment]
Hello @YashPatil-21, have you tried this in Preferences window? You can open it by using shortcut `Ctrl + ,` or open Menu > Help > Preferences...

![CleanShot 2024-08-13 at 16 04 13@2x](https://github.com/user-attachments/assets/e50a6d7a-8d57-4fab-ba0f-66698535203a)

Hope this help
