### ISSUE TITLE
Feature request: Option to increase UI scaling

### ISSUE THREAD

**Issue by ben-shepherd** [TablePlus/TablePlus-Windows#681]
### Please answer the questions below, it helps us to track the issue.

It would be great to have an option to increase the UI scaling. The tables/functions sidebar and list of tables you have open are quite small on my screen size. I have tried increasing the font which helps with the data view.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

not applicable

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 276

5. The steps to reproduce this issue:

Monitor size: 1440 x 1080

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by sonswift** [comment]
Hello @ben-shepherd, have you tried this option in the Preferences window, it will increase the font size of the left side bar.

To open the Preferences window, you can open menu `Menu > Help > Preferences...` or use the shortcut `Ctrl ,`

![CleanShot 2024-09-08 at 08 10 43@2x](https://github.com/user-attachments/assets/ae7f86be-ff3e-4440-aa64-d0b904b52b77)

**Comment by ben-shepherd** [comment]
> Hello @ben-shepherd, have you tried this option in the Preferences window, it will increase the font size of the left side bar.
> 
> To open the Preferences window, you can open menu `Menu > Help > Preferences...` or use the shortcut `Ctrl ,`


Brilliant thank you. I think 'Preferences' being located in 'Help' is a bit unusual, probably why I couldn't find it. May be better if moved in to 'File' or 'Edit' sections
