### ISSUE TITLE
Pressing commit clears detail sidebar

### ISSUE THREAD

**Issue by rohanc** [TablePlus/TablePlus-Windows#69]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
postgres 9.6.8
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.2 (72)
3. The steps to reproduce this issue:
Switch to any table.
Open the detail panel
Put the cursor in a text field
Change the text
Press Ctrl+S to commit

The entire sidebar goes blank!
I have to click back into the central panel on the record I was editing to get the detail sidebar contents back.

What I expect to happen is for the cursor to stay in the field I was editing and for some visual indication that the commit was successful.

**Comment by huyphams** [comment]
it's fixed in the build 86.

**Comment by rohanc** [comment]
Brilliant, that's a great improvement.
This reveals a new bug though, in relation to the "Search for columns..." filter on the detail sidebar.:

Pressing Ctrl+S temporarily clears the filter and thus all fields are shown and the user loses their place. Going into the filter field and pressing Enter doesn't help, but going into the filter and removing the last character and putting it back again restores the filter.

**Comment by huyphams** [comment]
Thanks, I will fix it now.
