### ISSUE TITLE
The pretty option is missing for JSON columns, it's available if the column is a string for example

### ISSUE THREAD

**Issue by sse87** [TablePlus/TablePlus-Windows#692]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 15.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 288

3. The steps to reproduce this issue:

Steps: View a database table column with a JSON type. I don't see the pretty option, it is available in the mac version.

See gif:

![pretty-missing](https://github.com/user-attachments/assets/2c9dcbab-5c43-4a08-8907-383fee3f5cd8)

**Comment by sonswift** [comment]
Hi @sse87, thank for your feedback. I will check it now.

**Comment by sse87** [comment]
I got the [new update](https://tableplus.com/blog/2018/09/changelogs-windows.html), thanks for fixing it! 😄 👍
