### ISSUE TITLE
Cannot restore backup dump file (ERROR:  unrecognized configuration parameter "transaction_timeout")

### ISSUE THREAD

**Issue by ezio1404** [TablePlus/TablePlus-Windows#693]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
17.0
OS: Windows(WSL)
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
288
3. The steps to reproduce this issue:
>restore_pg_17.0: error: could not execute query: ERROR:  unrecognized configuration parameter "transaction_timeout" Command was: SET transaction_timeout = 0;

1. Menu > file > backup
2. Select any connection > select any database > select option `--format=custom` and PgSQL 17.0
3. Click Start backup
4. Rename and save
5. Click Menu > File >restore
6. Select same connection and same DB
7. Click Start restore
8. Select recently backup dump file
9. Error message will show
>Restore database 'db_name'
Restoring...
restore_pg_17.0: error: could not execute query: ERROR:  unrecognized configuration parameter "transaction_timeout"
Command was: SET transaction_timeout = 0;
Done

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by sonswift** [comment]
> restore_pg_17.0: error: could not execute query: ERROR: unrecognized configuration parameter "transaction_timeout" Command was: SET transaction_timeout = 0;

Hi @ezio1404, I think the issue is that your database is not PostgreSQL 17.0 or later, because of using PostgreSQL 17.0 to restore to database below 17.0 will get above error. 
You can check your PostgreSQL version by connecting to the database; the version information is displayed in the toolbar of the workspace then find a matched PostgreSQL version when backup or restore (see the image below)

![CleanShot 2024-12-12 at 21 06 46@2x](https://github.com/user-attachments/assets/b4021dba-f34f-4dea-8f47-e1801c171693)

**Comment by ezio1404** [comment]
@sonswift 
Thank you, for acknowledging,
I confirmed it is not the 17.0 version, and there is only specified options to choose from when creating back up.
I would appreciate if there are ways to backup, thank you again.

>   database:
    image: postgres:12.18-alpine

**Comment by sonswift** [comment]
Hi @ezio1404, you can try the PostgreSQL 12.1 to backup and restore your database. In Backup and Restore windows, we have already supported more PostgreSQL versions from 11.x to 17.x (see the image below)

![CleanShot 2024-12-12 at 21 41 58@2x](https://github.com/user-attachments/assets/a65c97cc-b85f-40f5-840c-b784cae1353a)

**Comment by ezio1404** [comment]
@sonswift 
Thank you, it works as long as when you backup have the same pgsql version
