### ISSUE TITLE
Schema dropdown not alphabetized

### ISSUE THREAD

**Issue by jharner11235** [TablePlus/TablePlus-Windows#71]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
PostgreSQL 11.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 72, Windows

3. The steps to reproduce this issue:
Open schemata dropdown list

I just migrated to Windows recently after running TablePlus on Apple (probably harder than learning to write with your opposite hand) so there are a lot of features I miss... however, this one is just a pain in the butt.

**Comment by huyphams** [comment]
Thanks, I fixed it, it will be available on the next update.
