### ISSUE TITLE
MSSQL Next/Prev Page Not Working

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#78]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server 2014

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
72

3. The steps to reproduce this issue:
Open table with more than 300 rows
Hit ">" or "<"
Page does not update

![image](https://user-images.githubusercontent.com/25158630/63622455-717c3600-c5bc-11e9-9ce4-ff48781a6caa.png)
![image](https://user-images.githubusercontent.com/25158630/63622485-848f0600-c5bc-11e9-86b2-0cb92cfea3b3.png)
![image](https://user-images.githubusercontent.com/25158630/63622535-a1c3d480-c5bc-11e9-9deb-33ae88d2e7df.png)

Also "Next" doesn't disable when you reach the end. 
![image](https://user-images.githubusercontent.com/25158630/63623679-d71df180-c5bf-11e9-9e59-11846cad4d1b.png)

**Comment by rwhirn** [comment]
@huyphams This bug is pretty critical - not being able to view any [age but the first one is a bug problem. Fortunately, I work with MySQL much more than MSSQL so its not affecting most of what I do, but if you could look into this soon it would be appreciated. 

I am also adding a new MSSQL bug today that may be related.

**Comment by huyphams** [comment]
I've fixed this issue, please download the hotfix update here: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
Let me know if you're still seeing it.

**Comment by rwhirn** [comment]
All good. Thx.
