### ISSUE TITLE
MSSQL Schema Dropdown defaulting and resetting to first item

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#79]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQL Express 2014

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
74

3. The steps to reproduce this issue:
Opening connection to MSSQL db I was surprised to have no tables listed in the tables pane. Took me awhile to figure out that the schema had been reset to the first item in the list. So I reset it to dbo (which should probably be the default as I would guess 99% of the time you will be accessing this schema). I clicked on a table, selected a record, made a change to the record, saved it and then the tables pane cleared out as the schema had reset itself to the first item in the list again.

Make a change to a field
![image](https://user-images.githubusercontent.com/25158630/63653907-baf19000-c738-11e9-9fb8-a8ed73b08272.png)

Ctrl-S to save it and the schema resets to first item in the list and tables pane clears
![image](https://user-images.githubusercontent.com/25158630/63653924-0e63de00-c739-11e9-8394-c1a23a6641f9.png)

**Comment by huyphams** [comment]
Thanks, let me fix it.
