### ISSUE TITLE
Right click on welcome screen connection list crashes

### ISSUE THREAD

**Issue by marksegalle** [TablePlus/TablePlus-Windows#8]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 10

3. The steps to reproduce this issue:
Right clicking on the connection list in the welcome doesn't show a context menu, then after clicking again it crashes

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I just fixed it, thanks. Actually, it's crashed when you clicked it for the first time.
