### ISSUE TITLE
Delay between editing a row field and next step

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#84]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
85

3. The steps to reproduce this issue:
Through many builds I have been experiencing a serious delay of about 5 seconds between the time when you change a field and a row before you can do anything else. I.e., either hit TAB to the next field, click on some other row, or CTRL-S to save - it takes 5 seconds before the curesor moves to the next spot or the save occurs. 

Also, this is not limited to changes - even if nothing changes, say I just want to TAB through 6 fields to get to the 7th, this will take 30 seconds for the 7th field to become editable.

The delay is slightly less on a MSSQL db which is located on my LAN (as opposed to the MySQL database which is located at AWS).

And it has seemed like the delay has been increasing over the course of new releases.

I just wonder what it could be doing that would cause a slowdown - theoretically it is just deciding what color to make the field when you leave it? Is it rereading the record from source to see if it changed? Is it checking every field in the table to see if any field changed? (Thus it would be longer if the table has many fields).

**Comment by huyphams** [comment]
Thanks @rwhirn, How many rows do you have on the single page?
<img width="1327" alt="row" src="https://user-images.githubusercontent.com/3654622/64204187-96e62b00-ce6b-11e9-89d9-dd242746fc6e.png">

**Comment by rwhirn** [comment]
Right now I'm looking at a filtered view of 4 rows. Normally I leave it at the default 350.

**Comment by huyphams** [comment]
Thanks for confirming, it shouldn't be a problem, let me take a look and improve it.

**Comment by huyphams** [comment]
Hi @rwhirn does it happen when the right sidebar closing or opening? If you close the sidebar, selecting will be faster.
<img width="1462" alt="aa" src="https://user-images.githubusercontent.com/3654622/64385396-b8cae380-d00c-11e9-91d3-74ac1f7636e7.png">

**Comment by rwhirn** [comment]
No, no right panel open.

It must be related to number of tables in left pane.
In a DB with few tables it doesn't happen.

**Comment by huyphams** [comment]
It's fixed on the build 86, which also comes with an installer, TablePlus now switch to installer instead of portable release. We're working on the Certification vendor to get a trusted cert for Windows.

**Comment by rwhirn** [comment]
Working great
