### ISSUE TITLE
Filter Option IS/IS NOT empty

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#86]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Any

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
85

3. The steps to reproduce this issue:
If you want to filter for records where a particular text field is or is not empty there is no option for that. You can do IN '' or NOT IN '', but that's not the proper usage of those. There real should be options: ='' and !=''

**Comment by huyphams** [comment]
the IN and NOT IN are using for array filter. If you want to use IS or NOT EMPTY you can use the `=` with the empty value.

**Comment by rwhirn** [comment]
I stand corrected. My query was being messed up by the clicking the "+" sign. I just noticed it is doing it even on new filters. I added a filter and applied then added a filter and the value of the previous filter went back to empty. So not noticing that I got no results and assumed the new "empty" filter I was trying to do was not working.
