### ISSUE TITLE
Filter Option value resetting when you click "+"

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#87]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
85

3. The steps to reproduce this issue:
Open a table that has a remembered filter from last visit
![image](https://user-images.githubusercontent.com/25158630/64295533-f3624c80-cf36-11e9-94ba-e0f0bf99381d.png)

Change that filter to something else
Click apply
![image](https://user-images.githubusercontent.com/25158630/64295591-168cfc00-cf37-11e9-99ae-c539c511ba45.png)

Add a filter by clicking that filter's "+"
The value of the existing filter switches back to its previous value 
![image](https://user-images.githubusercontent.com/25158630/64295639-3e7c5f80-cf37-11e9-9156-188a3a76cb5f.png)

**Comment by huyphams** [comment]
Thanks, I'm fixing it.

**Comment by huyphams** [comment]
Hey, I fixed it, I also make an installer for Windows now: https://www.dropbox.com/s/057zewf096xrzj1/tableplussetup.zip?dl=0 Currently it's displayed the publisher is unknown because we're verifying our certification.
You can remove the portable version and use the installer.
