### ISSUE TITLE
Paging needs to reset on "Apply"

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#88]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Any

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
85

3. The steps to reproduce this issue:
If you filter a table and get enough rows for multiple pages and then page forward to somewhere like the last page. Then change your filter to get fewer rows and fewer pages. If you went to a page number greater than the second filter returns you will be presented with a blank page (or pages) and will have to page back through every extra blank page to get to the results. And the row info at the bottom of the page will be wrong.
![image](https://user-images.githubusercontent.com/25158630/64467056-ce0e4380-d0da-11e9-8540-a8b2df5bef37.png)

**Comment by huyphams** [comment]
It's fixed now! Thanks!
