### ISSUE TITLE
date columns in cassandra results show as '1970-01-01 00:00:00'

### ISSUE THREAD

**Issue by TimAtAdaptive** [TablePlus/TablePlus-Windows#9]
did ```select * from table where utcdate > '2018-09-01'``` which returned the correct number of rows, but all of the columns containing a ```date``` show '1970-01-01 00:00:000'

Using Cassandra driver
Build 10
Title bar shows "Cassandra 3.11.2"

**Comment by huyphams** [comment]
Hi @TimAtAdaptive a lot of improvements will be pushed tomorrow includes this fixes. Thanks for letting me know.

**Comment by huyphams** [comment]
It's supported on build 11 now.
