### ISSUE TITLE
Table Tabs sized strangely when you get second row

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#91]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
86

3. The steps to reproduce this issue:
Open more tabs than can fit on one line
Once second line is displayed tab sizes are shown much larger than they really are and clicking on anything on the top row opens the tab on the bottom row. Clicking bottom row works as normal.

**Comment by huyphams** [comment]
Agree @rwhirn the current behavior is terrible, I don't know why Microsoft uses it in the first place. I will find a way to override it. Thank you!

**Comment by huyphams** [comment]
I've updated the tab behavior in this patch: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
If you have a chance, please try it and let me know if you're still seeing this issue.

**Comment by rwhirn** [comment]
Just opened it - I'm not crazy about it. Full screen width tabs always? That's not standard behavior for tabs. And the more tables you open the less of the name you get to see? 
![image](https://user-images.githubusercontent.com/25158630/67875056-d9428600-fb03-11e9-8c8d-85d51226843e.png)
That's not good.

No, I'm reverting back. Even with the second line spacing issue it was much better and much easier to use.

**Comment by rwhirn** [comment]
In my experience, programs that have mulitple tabs generally have it as an option whether you want "single row" or "multiple rows". Just FYI, I use PHPStorm and UltraEdit, both of which offer that. I used Sublime for awhile but didn't like it as much.

BTW, Google Search brings up many complaints about Sublime's behavior regarding this and this plugin:

> Multi-Line Tabbar for ST2 - Plugin Announcements - Sublime Forum ...
https://forum.sublimetext.com › multi-line-tabbar-for-st2

**Comment by huyphams** [comment]
Thanks @rwhirn I will improve it, I don't know if you have used this feature, but command + P can navigate to any opened tabs pretty quick.

**Comment by rwhirn** [comment]
FYI, the first tab loses its left margin when the name overflows the width of the tab
![image](https://user-images.githubusercontent.com/25158630/67900819-520d0680-fb33-11e9-856c-3a44d3ad5a27.png)

**Comment by rwhirn** [comment]
![image](https://user-images.githubusercontent.com/25158630/67984559-002cb500-fbf5-11e9-905c-647df6a9bd2d.png)
Which tab do I click on the first or the third? Every time I click the wrong one and it pisses me off. A truncated tab name is just not acceptable. I really hate this.

**Comment by huyphams** [comment]
Please rollback to the build 92 @rwhirn https://tableplus.com/blog/2018/09/changelogs-windows.html
as a temporary solution. I will update this thread as soon as I solve the issue or at least added an option for multiple line tabs.

**Comment by rwhirn** [comment]
No, I know I could have done that but I'll stick with you - I want to debug and provide feedback for you. Just letting you know my frustration at the current stage.

**Comment by rwhirn** [comment]
BTW, I think it should also allow you to drag and drop to rearrange tabs.

**Comment by huyphams** [comment]
We have it in our plan already, no worries

**Comment by huyphams** [comment]
It's not a solution but I've added a tooltip in this build: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
while waiting for the multiple lines tab solution, you can download this patch, it will show a tooltip when you hover mouse over the tab.

**Comment by huyphams** [comment]
Please try this build and see if it works as your expectation @rwhirn https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
Thank you!

**Comment by rwhirn** [comment]
That's absolutely perfect. I hope you can add the option for "single line or multi-line" for those who prefer the single, but this is definitely my preferred choice. Thanks!
