### ISSUE TITLE
Horizontal scroll

### ISSUE THREAD

**Issue by sweet-greg** [TablePlus/TablePlus-Windows#92]
build 86
Horizontall scrolling doesn't work with a mouse or trackpad. The only way is to drag the scrollbar.

**Comment by jim256** [comment]
I just experienced the same thing
Windows 10 1903
TablePlus Build 88

**Comment by dwyer14** [comment]
Same, currently on build 102 and Windows 10. Using a Logitech MX Master 3, though I doubt that matters—horizontal scrolling works in other applications. This would be a highly-appreciated fix, especially on tables with a boatload of columns. 😰

**Comment by huyphams** [comment]
This was a Windows Native View issue. They don't support horizontal scrolling with mouse or touchpad. 
I'm still finding a way to support it.

I've tested it on Dell XPS and Surface Laptop 3. it works with touch screen but not touchpad or mouse.

**Comment by dwyer14** [comment]
@huyphams thanks for looking into that!

**Comment by jim256** [comment]
@huyphams still watching this closely! Basically the only thing stopping me from using the product.

To add a few more details, I also cannot scroll horizontally using the horizontal scroll wheel on my Logitech MX Master mouse. It works fine in Devart DB Forge.

Windows 10 1909
TablePlus Build 110

**Comment by huyphams** [comment]
Hi guys, you might want to checkout this hot patch: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
I've added an attempt to fix the issue, we're still testing it in various devices before release it.
Please try it and see how's it going.

**Comment by sweet-greg** [comment]
Works like a charm @huyphams 
tested: shift+scroll, horizontal scroll wheel on my mouse, trackpad

**Comment by huyphams** [comment]
It's released in build 110. Thanks.

**Comment by nicolaib** [comment]
This is still an issue in build 120.

Lenovo Yoga 2 Pro
Windows 10 Pro 1903 Build 18362.720

I have already tried installing the build from the above link of 20 Dec 2019.
