### ISSUE TITLE
Double Clicking a Cell flags it as modified

### ISSUE THREAD

**Issue by bshea5** [TablePlus/TablePlus-Windows#93]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**MS SQL Server**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **87**

3. The steps to reproduce this issue:
**Double click a cell. This will color the cell orange, indicating a change. If you to try to save, it is including the double clicked cell. The only way for me to remove the flag, is to go to edit->Discard, which also removed all other pending changes.**

Noted: If the bug is related to data, please attach an example SQL data. **N/A**

**Comment by huyphams** [comment]
Hi @bshea5 did you double-clicking a field with NULL value or normal text value?

**Comment by bshea5** [comment]
I think it might have something to do with the data type. I'm seeing it occur with columns where the values are boolean, numeric, or datetime. It occurs whether there is value or if the cell is empty.

**Comment by huyphams** [comment]
Thanks, I'm fixing it.

**Comment by rwhirn** [comment]
Anything but a text field

**Comment by rwhirn** [comment]
Also if you double click on the cell again - it then EMPTIES the field. You lose the existing value entirely.

**Comment by huyphams** [comment]
Hi @rwhirn @bshea5  please upgrade to the build 88, it should fix the issue!

**Comment by bshea5** [comment]
Seems to work! Thanks for the rapid response. Closing!

**Comment by rwhirn** [comment]
This has appeared again on "enum" type fields (if that makes a difference)
![image](https://user-images.githubusercontent.com/25158630/66168508-0b46f200-e603-11e9-990f-bbcec12c9adf.png)

emboss, contentType and dblsided were "empty"

**Comment by rwhirn** [comment]
field structure FYI
![image](https://user-images.githubusercontent.com/25158630/66168996-81982400-e604-11e9-815c-41996745c994.png)

**Comment by huyphams** [comment]
Please try this hot patch @rwhirn https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by rwhirn** [comment]
Yup. That fixed it. Thx!
