### ISSUE TITLE
Can't click on current open table after save

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#94]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
88

3. The steps to reproduce this issue:
Open a table (note the table shows selected via highlighting)
make a change to a row (it shows changed via highlighting)
ctrl-s to Save changes
row is updated (and I think screen is reloaded?) (row highlighting goes away)
notice table highlighting has also gone away
try to click (or right click) on the table name again - you can't
table pane resets to first page of tables
scroll back down to the current table and try to click or right click again and it goes back to the top

**Comment by huyphams** [comment]
Thanks, I fixed it. It will be released in the next update!
Or you can download the hot patch here: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
