### ISSUE TITLE
Can't enter newline into database fields

### ISSUE THREAD

**Issue by rohanc** [TablePlus/TablePlus-Windows#95]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.9.2 Build 88
3. The steps to reproduce this issue:
Go into any TEXT field within the detail sidebar and try to enter a newline character.
I tried: Enter, Ctrl+Enter, Alt+Enter, Shift+Enter
Result: nothing happens - keypress is ignored.

You can't even successfully paste a string containing a newline from the clipboard. When I try that it only pastes the text up to the first newline character.

If I try to edit the field in a column value in the central section (that is, not in the detail sidebar), I still can't enter a newline character, but the Enter key has the effect of submitting the changes.

The ability to insert newlines is important when editing long text fields, such as those that contains fragments of HTML.

I would love it if I could insert a newline into fields by pressing Ctrl+Enter.

I would prefer it if in the detail sidebar, that the Enter key indicated to TablePlus that the user has finished editing that field. Perhaps it would also be appropriate to submit the changes immediately to the database backend, I don't know.

Having special behaviour for the unmodified Enter key, when editing multi-line text fields, might be appropriate, although I don't know what algorithm you would use to determine that a field is in multi-line mode.

**Comment by huyphams** [comment]
It's the default behavior of the Windows DataGrid, let me see if I can override it. Meanwhile, you can edit the data easier with the quick look. (Middle mouse click on the cell or right-click > Quick Look)
<img width="1079" alt="Screen Shot 2019-09-20 at 9 38 22 AM" src="https://user-images.githubusercontent.com/3654622/65327460-65b76b80-db8a-11e9-8588-1a6d4814e7b3.png">

**Comment by rohanc** [comment]
Seeing that you closed this issue, I just tried again using v4.3.5. The Enter on its own seems to enter newlines now, when working in the Detail sidebar. Not sure when this was fixed, but thankyou for doing it!
