### ISSUE TITLE
Vertical scrollbar missing from Detail sidebar

### ISSUE THREAD

**Issue by rohanc** [TablePlus/TablePlus-Windows#97]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.9.2 (88)
3. The steps to reproduce this issue:

I frequently have to edit tables with a high number of columns. For example, in one of my databases, one commonly used table has 56 columns. Whether or not this is great database design, it would be easier to manage if there was a vertical scrollbar in the Detail Sidebar.

The scroll-wheel on the mouse work just fine when there are only a few columns, but as the number of columns grow, I start to miss the ability to get to the bottom quickly by dragging the scrollbar.

**Comment by huyphams** [comment]
It will be released in the next update.
