### ISSUE TITLE
MSSQL popup SQL command not correct

### ISSUE THREAD

**Issue by rwhirn** [TablePlus/TablePlus-Windows#98]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MSSQL Server 2014 Express

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
88

3. The steps to reproduce this issue:
Set rows limit to 300
Displays rows 1-300
Click SQL button
It always shows "SELECT TOP 500" no matter what limit or range you selected.
![image](https://user-images.githubusercontent.com/25158630/65394321-e07eb300-dd51-11e9-848a-27b1e965ee0b.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
it's also fixed within this issue: https://github.com/TablePlus/TablePlus-Windows/issues/78

**Comment by rwhirn** [comment]
All good. Thx.
